// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuNode2D.mjs';
import * as __dependency1 from './wgpuQuadBatchWriter.mjs';

const api = compiled.flighthq.scene2dWgpu.WgpuCache;
function __syncDependencies() {
  compiled.flighthq.scene2dWgpu.WgpuNode2D.renderWgpuScene2D = __dependency0.renderWgpuScene2D;
  compiled.flighthq.scene2dWgpu.WgpuQuadBatchWriter.flushWgpuQuadBatchWriter = __dependency1.flushWgpuQuadBatchWriter;
}
__syncDependencies();

export const createWgpuCacheState = api.createWgpuCacheState;
export const defaultWgpuRenderCacheRenderer = api.defaultWgpuRenderCacheRenderer;
export const enableWgpuRenderCache = api.enableWgpuRenderCache;
export const ensureWgpuRenderCacheTarget = api.ensureWgpuRenderCacheTarget;
export const getWgpuRenderCacheScreenState = api.getWgpuRenderCacheScreenState;
export const getWgpuRenderCacheTarget = api.getWgpuRenderCacheTarget;
export const refreshWgpuRenderCache = api.refreshWgpuRenderCache;
export const releaseWgpuRenderCache = api.releaseWgpuRenderCache;
