// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/textlayout/contract';

const api = compiled.flight._Scene2DWgpu;
function __syncDependencies() {
  compiled.flight._TextLayout.computeTextLayout = __dependency0.computeTextLayout;
}
__syncDependencies();

export const defaultWgpuTextLabelRenderer = api.defaultWgpuTextLabelRenderer;
export function drawWgpuTextLabel(...args) { __syncDependencies(); const result = api.drawWgpuTextLabel(...args); return result; }
