// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene2dWgpu.WgpuTextInput;
function __syncDependencies() {}
__syncDependencies();

export const drawWgpuTextInputOverlay = api.drawWgpuTextInputOverlay;
export const enableWgpuTextInput = api.enableWgpuTextInput;
