// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/node/contract';

const api = compiled.flight._Scene2DWgpu;
function __syncDependencies() {
  compiled.flight._Node.getNodeLocalBoundsRectangle = __dependency0.getNodeLocalBoundsRectangle;
  compiled.flight._Node.getNodeLocalContentRevision = __dependency0.getNodeLocalContentRevision;
}
__syncDependencies();

export const defaultWgpuMorphShapeRenderer = api.defaultWgpuMorphShapeRenderer;
export const defaultWgpuShapeRenderer = api.defaultWgpuShapeRenderer;
export const drawWgpuShape = api.drawWgpuShape;
