// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuQuadBatchWriter.mjs';

const api = compiled.flight._Scene2DWgpu;
function __syncDependencies() {
  compiled.flight._Scene2DWgpu.flushWgpuQuadBatchWriter = __dependency0.flushWgpuQuadBatchWriter;
}
__syncDependencies();

export const defaultWgpuParticleEmitter2DRenderer = api.defaultWgpuParticleEmitter2DRenderer;
const __bridgeImplementation_drawWgpuParticleEmitter2D = api.drawWgpuParticleEmitter2D;
export function drawWgpuParticleEmitter2D(...args) { __syncDependencies(); const result = __bridgeImplementation_drawWgpuParticleEmitter2D(...args); return result; }
api.drawWgpuParticleEmitter2D = drawWgpuParticleEmitter2D;
compiled.flight.Scene2DWgpu.drawWgpuParticleEmitter2D = drawWgpuParticleEmitter2D;
