// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types.Abc;
function __syncDependencies() {}
__syncDependencies();

export const AbcMultinameKind = api.AbcMultinameKindValue;
export const AbcTraitKind = api.AbcTraitKindValue;
