// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types._internal._CubeTextureValues;
function __syncDependencies() {}
__syncDependencies();

export const CubeFaceNegativeX = api.CubeFaceNegativeX;
export const CubeFaceNegativeY = api.CubeFaceNegativeY;
export const CubeFaceNegativeZ = api.CubeFaceNegativeZ;
export const CubeFacePositiveX = api.CubeFacePositiveX;
export const CubeFacePositiveY = api.CubeFacePositiveY;
export const CubeFacePositiveZ = api.CubeFacePositiveZ;
