// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.Types;
function __syncDependencies() {}
__syncDependencies();

export const DeviceFormFactorCar = api.DeviceFormFactorCar;
export const DeviceFormFactorDesktop = api.DeviceFormFactorDesktop;
export const DeviceFormFactorPhone = api.DeviceFormFactorPhone;
export const DeviceFormFactorTablet = api.DeviceFormFactorTablet;
export const DeviceFormFactorTV = api.DeviceFormFactorTV;
export const DeviceFormFactorUnknown = api.DeviceFormFactorUnknown;
export const DeviceFormFactorWatch = api.DeviceFormFactorWatch;
