// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types.Layout;
function __syncDependencies() {}
__syncDependencies();

export const AnchorLayoutKind = api.AnchorLayoutKind;
export const FlexLayoutKind = api.FlexLayoutKind;
export const GridLayoutKind = api.GridLayoutKind;
export const LayoutResolutionFailureKind = api.LayoutResolutionFailureKindValue;
