// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types._internal._NodeValues;
function __syncDependencies() {}
__syncDependencies();

export const NodeKind = api.NodeKind;
export const NullScene = api.NullScene;
