// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types._internal._RectangleColliderValues;
function __syncDependencies() {}
__syncDependencies();

export const RectangleColliderKind = api.RectangleColliderKind;
