// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types._internal._Skeleton2DPathConstraintValues;
function __syncDependencies() {}
__syncDependencies();

export const Skeleton2DPathPositionMode = api.Skeleton2DPathPositionModeValue;
export const Skeleton2DPathRotateMode = api.Skeleton2DPathRotateModeValue;
export const Skeleton2DPathSpacingMode = api.Skeleton2DPathSpacingModeValue;
