// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.types._internal._TilemapValues;
function __syncDependencies() {}
__syncDependencies();

export const TilemapKind = api.TilemapKind;
