// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._SceneDocument;
function __syncDependencies() {}
__syncDependencies();

export const createFlightDocumentFromScene3D = api.createFlightDocumentFromScene3D;
export const createFlightDocumentScene3DMaterialization = api.createFlightDocumentScene3DMaterialization;
export const createFlightDocumentScene3DMaterializationFromText = api.createFlightDocumentScene3DMaterializationFromText;
export const explainFlightDocumentScene3DRefusal = api.explainFlightDocumentScene3DRefusal;
export const explainFlightDocumentScene3DRefusalFromText = api.explainFlightDocumentScene3DRefusalFromText;
