// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.toolCapture.CaptureFormat;
function __syncDependencies() {}
__syncDependencies();

export const formatDetailLine = api.formatDetailLine;
export const formatStatusLine = api.formatStatusLine;
export const formatSummaryCount = api.formatSummaryCount;
export const formatSummaryLine = api.formatSummaryLine;
