// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.layout.EnableLayoutGuards;
function __syncDependencies() {}
__syncDependencies();

export const enableLayoutGuards = api.enableLayoutGuards;
