// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneFormats.Md5Parse;
function __syncDependencies() {}
__syncDependencies();

export const createSceneFromMd5Mesh = api.createSceneFromMd5Mesh;
