// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.statechart.EnableStatechartGuards;
function __syncDependencies() {}
__syncDependencies();

export const areStatechartGuardsEnabled = api.areStatechartGuardsEnabled;
export const disableStatechartGuards = api.disableStatechartGuards;
export const enableStatechartGuards = api.enableStatechartGuards;
