// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.haptics.Haptics;
function __syncDependencies() {}
__syncDependencies();

export const cancelDeviceVibration = api.cancelDeviceVibration;
export const createWebHapticsBackend = api.createWebHapticsBackend;
export const explainHapticsBackend = api.explainHapticsBackend;
export const getHapticsBackend = api.getHapticsBackend;
export const getHapticsCapabilities = api.getHapticsCapabilities;
export const installHapticsHostBackend = api.installHapticsHostBackend;
export const isHapticsSupported = api.isHapticsSupported;
export const observeHapticsHostResult = api.observeHapticsHostResult;
export const prepareHaptics = api.prepareHaptics;
export const resetHapticsBackendForTest = api.resetHapticsBackendForTest;
export const setHapticsBackend = api.setHapticsBackend;
export const triggerHapticImpact = api.triggerHapticImpact;
export const triggerHapticNotification = api.triggerHapticNotification;
export const triggerHapticSelection = api.triggerHapticSelection;
export const vibrateDevice = api.vibrateDevice;
export const vibrateDevicePattern = api.vibrateDevicePattern;
export const vibrateDeviceWaveform = api.vibrateDeviceWaveform;
