// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostWeb;
function __syncDependencies() {}
__syncDependencies();

export const createWebBitmapReadbackBackend = api.createWebBitmapReadbackBackend;
export const initializeWebBitmapReadbackBackend = api.initializeWebBitmapReadbackBackend;
export const webBitmapReadbackBackend = api.webBitmapReadbackBackend;
