// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostWeb;
function __syncDependencies() {}
__syncDependencies();

export const webDirectoryOpenDialogBackend = api.webDirectoryOpenDialogBackend;
export const webFileOpenDialogBackend = api.webFileOpenDialogBackend;
export const webFileSaveDialogBackend = api.webFileSaveDialogBackend;
export { webMessageDialogBackend } from '@flighthq/dialog/contract';
export { webPromptDialogBackend } from '@flighthq/dialog/contract';
