// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostWeb;
function __syncDependencies() {}
__syncDependencies();

export const createWebGlyphRasterizerBackend = api.createWebGlyphRasterizerBackend;
export const initializeWebGlyphRasterizerBackend = api.initializeWebGlyphRasterizerBackend;
export const webGlyphRasterizerBackend = api.webGlyphRasterizerBackend;
