// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostWeb;
function __syncDependencies() {}
__syncDependencies();

export const createWebMediaSessionActionBackend = api.createWebMediaSessionActionBackend;
export const createWebMediaSessionBackend = api.createWebMediaSessionBackend;
export const webMediaSessionActionBackend = api.webMediaSessionActionBackend;
export const webMediaSessionBackend = api.webMediaSessionBackend;
