// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.hostWeb.WebWindow;
function __syncDependencies() {}
__syncDependencies();

export const enableHostWebWindow = api.enableHostWebWindow;
export const resetHostWebWindowForTest = api.resetHostWebWindowForTest;
