// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.interaction.CursorBackend;
function __syncDependencies() {}
__syncDependencies();

export const createWebCursorBackend = api.createWebCursorBackend;
