// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Interaction;
function __syncDependencies() {}
__syncDependencies();

export const clearFocus = api.clearFocus;
export const connectFocusNavigation = api.connectFocusNavigation;
export const createFocusManager = api.createFocusManager;
export const focusNextNode = api.focusNextNode;
export const focusNodeInDirection = api.focusNodeInDirection;
export const focusPreviousNode = api.focusPreviousNode;
export const getFocusedNode = api.getFocusedNode;
export const getFocusOrder = api.getFocusOrder;
export const isNodeFocused = api.isNodeFocused;
export const setFocusedNode = api.setFocusedNode;
