// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.displayobjectCanvas.CanvasScale9Shape;
function __syncDependencies() {}
__syncDependencies();

export const defaultCanvasScale9ShapeRenderer = api.defaultCanvasScale9ShapeRenderer;
export const drawCanvasScale9Shape = api.drawCanvasScale9Shape;
export const mapCanvasScale9ShapeCommands = api.mapCanvasScale9ShapeCommands;
