// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.displayobjectCanvas.CanvasTextMeasure;
function __syncDependencies() {}
__syncDependencies();

export const createCanvasTextMeasure = api.createCanvasTextMeasure;
