// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Scene3D;
function __syncDependencies() {}
__syncDependencies();

export const findScene3DMaterialByName = api.findScene3DMaterialByName;
export const getScene3DMaterials = api.getScene3DMaterials;
