// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.path.PathMorph;
function __syncDependencies() {}
__syncDependencies();

export const createPathMorph = api.createPathMorph;
export const samplePathMorph = api.samplePathMorph;
