// Generated by flight-hx. Do not edit.

function __syncDependencies() {}
__syncDependencies();

export { escapeDomHtmlString } from './domTextHelpers.mjs';
export { invalidateDomFontResource } from './domFontSource.mjs';
