// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene2dDom.DomTextHelpers;
function __syncDependencies() {}
__syncDependencies();

export const escapeDomHtmlString = api.escapeDomHtmlString;
