// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.collision.CollisionSupport3D;
function __syncDependencies() {}
__syncDependencies();

export const getCollisionPairTest3D = api.getCollisionPairTest3D;
export const getCollisionSupport3D = api.getCollisionSupport3D;
export const registerBuiltInCollisionSupports3D = api.registerBuiltInCollisionSupports3D;
export const registerCollisionPairTest3D = api.registerCollisionPairTest3D;
export const registerCollisionSupport3D = api.registerCollisionSupport3D;
export const supportCollisionAabb3D = api.supportCollisionAabb3D;
export const supportCollisionBox3D = api.supportCollisionBox3D;
export const supportCollisionCapsule3D = api.supportCollisionCapsule3D;
export const supportCollisionCone3D = api.supportCollisionCone3D;
export const supportCollisionConvex3D = api.supportCollisionConvex3D;
export const supportCollisionCylinder3D = api.supportCollisionCylinder3D;
export const supportCollisionSphere3D = api.supportCollisionSphere3D;
export const writeVertexListSupport3D = api.writeVertexListSupport3D;
