// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.collision.ExplainCollisionTest3D;
function __syncDependencies() {}
__syncDependencies();

export const explainCollisionTest3D = api.explainCollisionTest3D;
