// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.collision.PointContainment3D;
function __syncDependencies() {}
__syncDependencies();

export const getCollisionShapeContainsPoint3D = api.getCollisionShapeContainsPoint3D;
