// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Collision;
function __syncDependencies() {}
__syncDependencies();

export const createCollisionRaycastHit2D = api.createCollisionRaycastHit2D;
export const initializeCollisionRaycastHit2D = api.initializeCollisionRaycastHit2D;
export const raycastCollisionShape2D = api.raycastCollisionShape2D;
