// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.collision.RaycastCollisionShape;
function __syncDependencies() {}
__syncDependencies();

export const createCollisionRaycastHit = api.createCollisionRaycastHit;
export const raycastCollisionShape = api.raycastCollisionShape;
