// Generated by flight-hx. Do not edit.
package flighthq;

import Math as HxMath;
import flighthq.internal.FlightRuntime;
import flighthq.Signals.createSignal;
import flighthq.Signals.emitSignal;
import flighthq.Types.Socket;
import flighthq.Types.SocketBackend;
import flighthq.Types.SocketCloseInfo;
import flighthq.Types.SocketConnection;
import flighthq.Types.SocketEventSink;
import flighthq.Types.SocketMessage;
import flighthq.Types.SocketOptions;
import flighthq.Types.SocketReadyState;
import flighthq.Types.SocketRuntime;
import flighthq.Types.SocketSignals;

@:expose("flighthq.SocketApi")
class SocketApi {
  public static var _backend__socket:Null<SocketBackend> = FlightRuntime.explicitNull();

  public static function attachSocket(socket:Socket):Void {
    FlightRuntime.setField(FlightRuntime.field(socket, 'runtime'), 'delivering', true);
  }

  public static function closeSocket(socket:Socket, ?code:Float, ?reason:String):Void {
    var runtime:Dynamic = cast FlightRuntime.UNDEFINED;
    runtime = FlightRuntime.field(socket, 'runtime');
    if (FlightRuntime.truthy(FlightRuntime.orValue(FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'readyState'), 'closing'), function():Dynamic return cast FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'readyState'), 'closed')))) { return; }
    FlightRuntime.setField(runtime, 'readyState', 'closing');
    FlightRuntime.callOptionalProperty(FlightRuntime.field(runtime, 'connection'), 'closeSocketConnection', cast ([code, reason] : Array<Dynamic>));
  }

  public static function createSocket(options:SocketOptions):Socket {
    var runtime:SocketRuntime = cast FlightRuntime.UNDEFINED;
    var socket:Socket = cast FlightRuntime.UNDEFINED;
    runtime = { connection: null, signals: null, readyState: 'connecting', delivering: true };
    socket = { url: FlightRuntime.field(options, 'url'), runtime: runtime };
    FlightRuntime.setField(runtime, 'connection', FlightRuntime.callProperty(FlightRuntime.callValue(getSocketBackend, cast ([] : Array<Dynamic>)), 'openSocket', cast ([options, FlightRuntime.callValue(SocketApi.makeSocketEventSink__socket, cast ([runtime] : Array<Dynamic>))] : Array<Dynamic>)));
    return cast socket;
    return cast null;
  }

  public static function createWebSocketBackend():SocketBackend {
    return cast { openSocket: function(options:Dynamic, events:Dynamic) {
  var ws:Dynamic = cast FlightRuntime.UNDEFINED;
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.callProperty(FlightRuntime, 'typeofGlobal', cast (['WebSocket'] : Array<Dynamic>)), 'undefined'))) { return cast null; }
  ws = FlightRuntime.select(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'protocols'), FlightRuntime.UNDEFINED), function():Dynamic return cast FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['WebSocket'] : Array<Dynamic>)), [FlightRuntime.field(options, 'url'), (cast FlightRuntime.field(options, 'protocols') : Array<String>)]), function():Dynamic return cast FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['WebSocket'] : Array<Dynamic>)), [FlightRuntime.field(options, 'url')]));
  FlightRuntime.setField(ws, 'binaryType', FlightRuntime.coalesce(FlightRuntime.field(options, 'binaryType'), function():Dynamic return cast 'arraybuffer'));
  FlightRuntime.setField(ws, 'onopen', function() return FlightRuntime.callProperty(events, 'handleSocketOpen', cast ([] : Array<Dynamic>)));
  FlightRuntime.setField(ws, 'onmessage', function(event:Dynamic) return FlightRuntime.callProperty(events, 'handleSocketMessage', cast ([FlightRuntime.callValue(SocketApi.toSocketMessage__socket, cast ([FlightRuntime.field(event, 'data')] : Array<Dynamic>))] : Array<Dynamic>)));
  FlightRuntime.setField(ws, 'onclose', function(event:Dynamic) return FlightRuntime.callProperty(events, 'handleSocketClose', cast ([{ code: FlightRuntime.field(event, 'code'), reason: FlightRuntime.field(event, 'reason'), wasClean: FlightRuntime.field(event, 'wasClean') }] : Array<Dynamic>)));
  FlightRuntime.setField(ws, 'onerror', function() return FlightRuntime.callProperty(events, 'handleSocketError', cast ([] : Array<Dynamic>)));
  return cast { sendSocketFrame: function(data:Dynamic) {
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(ws, 'readyState'), FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['WebSocket'] : Array<Dynamic>)), 'OPEN')))) { return cast false; }
  FlightRuntime.callProperty(ws, 'send', cast ([data] : Array<Dynamic>));
  return cast true;
}, closeSocketConnection: function(code:Dynamic, reason:Dynamic) {
  FlightRuntime.callProperty(ws, 'close', cast ([code, reason] : Array<Dynamic>));
} };
} };
    return cast null;
  }

  public static function detachSocket(socket:Socket):Void {
    FlightRuntime.setField(FlightRuntime.field(socket, 'runtime'), 'delivering', false);
  }

  public static function disposeSocket(socket:Socket):Void {
    FlightRuntime.callValue(closeSocket, cast ([socket] : Array<Dynamic>));
    FlightRuntime.callValue(detachSocket, cast ([socket] : Array<Dynamic>));
    FlightRuntime.setField(FlightRuntime.field(socket, 'runtime'), 'signals', null);
  }

  public static function enableSocketSignals(socket:Socket):SocketSignals {
    var runtime:Dynamic = cast FlightRuntime.UNDEFINED;
    runtime = FlightRuntime.field(socket, 'runtime');
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'signals'), null))) {
  FlightRuntime.setField(runtime, 'signals', { onSocketOpen: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onSocketMessage: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onSocketClose: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onSocketError: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)) });
}
    return cast FlightRuntime.field(runtime, 'signals');
    return cast null;
  }

  public static function getSocketBackend():SocketBackend {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(SocketApi._backend__socket, null))) { (SocketApi._backend__socket = cast (FlightRuntime.callValue(createWebSocketBackend, cast ([] : Array<Dynamic>)) : Dynamic)); }
    return cast SocketApi._backend__socket;
    return cast null;
  }

  public static function getSocketReadyState(socket:Socket):SocketReadyState {
    return cast FlightRuntime.field(FlightRuntime.field(socket, 'runtime'), 'readyState');
    return cast null;
  }

  public static function makeSocketEventSink__socket(runtime:SocketRuntime):SocketEventSink {
    return cast { handleSocketOpen: function() {
  if (FlightRuntime.truthy(!FlightRuntime.truthy(FlightRuntime.field(runtime, 'delivering')))) { return; }
  FlightRuntime.setField(runtime, 'readyState', 'open');
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'signals'), null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(FlightRuntime.field(runtime, 'signals'), 'onSocketOpen')] : Array<Dynamic>)); }
}, handleSocketMessage: function(message:Dynamic) {
  if (FlightRuntime.truthy(!FlightRuntime.truthy(FlightRuntime.field(runtime, 'delivering')))) { return; }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'signals'), null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(FlightRuntime.field(runtime, 'signals'), 'onSocketMessage'), message] : Array<Dynamic>)); }
}, handleSocketClose: function(info:Dynamic) {
  if (FlightRuntime.truthy(!FlightRuntime.truthy(FlightRuntime.field(runtime, 'delivering')))) { return; }
  FlightRuntime.setField(runtime, 'readyState', 'closed');
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'signals'), null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(FlightRuntime.field(runtime, 'signals'), 'onSocketClose'), info] : Array<Dynamic>)); }
}, handleSocketError: function() {
  if (FlightRuntime.truthy(!FlightRuntime.truthy(FlightRuntime.field(runtime, 'delivering')))) { return; }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'signals'), null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(FlightRuntime.field(runtime, 'signals'), 'onSocketError')] : Array<Dynamic>)); }
} };
    return cast null;
  }

  public static function sendSocketMessage(socket:Socket, data:Dynamic):Bool {
    var runtime:Dynamic = cast FlightRuntime.UNDEFINED;
    runtime = FlightRuntime.field(socket, 'runtime');
    if (FlightRuntime.truthy(FlightRuntime.orValue(!FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'readyState'), 'open'), function():Dynamic return cast FlightRuntime.strictEquals(FlightRuntime.field(runtime, 'connection'), null)))) { return cast false; }
    return cast FlightRuntime.callProperty(FlightRuntime.field(runtime, 'connection'), 'sendSocketFrame', cast ([data] : Array<Dynamic>));
    return cast null;
  }

  public static function setSocketBackend(backend:Null<SocketBackend>):Void {
    (SocketApi._backend__socket = cast (backend : Dynamic));
  }

  public static function toSocketMessage__socket(data:Dynamic):SocketMessage {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.typeofValue(data), 'string'))) { return cast { data: data, binary: false }; }
    return cast { data: (cast data : haxe.io.Bytes), binary: true };
    return cast null;
  }
}
