// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.xml.XmlParse;
function __syncDependencies() {}
__syncDependencies();

export const parseXmlAttributes = api.parseXmlAttributes;
export const parseXmlDocument = api.parseXmlDocument;
