// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.bitmap.BitmapHistogram;
function __syncDependencies() {}
__syncDependencies();

export const equalizeBitmapHistogram = api.equalizeBitmapHistogram;
export const getBitmapHistogram = api.getBitmapHistogram;
