// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Bitmap;
function __syncDependencies() {}
__syncDependencies();

export const initializeBitmap__bitmapChannel = api.initializeBitmap__bitmapChannel;
export const mergeBitmapChannels = api.mergeBitmapChannels;
export const splitBitmapChannels = api.splitBitmapChannels;
