// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Bitmap;
function __syncDependencies() {}
__syncDependencies();

export const BITMAP_NOISE_CHANNEL_A = api.BITMAP_NOISE_CHANNEL_A;
export const BITMAP_NOISE_CHANNEL_B = api.BITMAP_NOISE_CHANNEL_B;
export const BITMAP_NOISE_CHANNEL_G = api.BITMAP_NOISE_CHANNEL_G;
export const BITMAP_NOISE_CHANNEL_R = api.BITMAP_NOISE_CHANNEL_R;
export const fillBitmapNoise = api.fillBitmapNoise;
export const fillBitmapPerlinNoise = api.fillBitmapPerlinNoise;
export const fillBitmapTurbulence = api.fillBitmapTurbulence;
