// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.bitmap.BitmapRotate;
function __syncDependencies() {}
__syncDependencies();

export const rotateBitmap = api.rotateBitmap;
export const rotateBitmap180 = api.rotateBitmap180;
export const rotateBitmapClockwise = api.rotateBitmapClockwise;
export const rotateBitmapCounterClockwise = api.rotateBitmapCounterClockwise;
