// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Bitmap;
function __syncDependencies() {}
__syncDependencies();

export const getBitmapReadbackBackend = api.getBitmapReadbackBackend;
export const hasBitmapReadbackHostBackend = api.hasBitmapReadbackHostBackend;
export const installBitmapReadbackHostBackend = api.installBitmapReadbackHostBackend;
export const resetBitmapReadbackBackendForTest = api.resetBitmapReadbackBackendForTest;
export const setBitmapReadbackBackend = api.setBitmapReadbackBackend;
