// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/scene-formats';

const api = compiled.flighthq.sceneResources.AwdLoad;
function __syncDependencies() {
  compiled.flighthq.sceneFormats.SceneFormats.parseAwd = __dependency0.parseAwd;
}
__syncDependencies();

export const loadSceneDocumentFromAwdUrl = api.loadSceneDocumentFromAwdUrl;
