// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneResources.SceneResourceSignals;
function __syncDependencies() {}
__syncDependencies();

export const createSceneResourceSignals = api.createSceneResourceSignals;
export const enableSceneResourceSignals = api.enableSceneResourceSignals;
export const getSceneResourceSignals = api.getSceneResourceSignals;
