// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostTauri;
function __syncDependencies() {}
__syncDependencies();

export const createTauriShortcutQueryBackend = api.createTauriShortcutQueryBackend;
export const createTauriShortcutTriggerBackend = api.createTauriShortcutTriggerBackend;
