// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneWgpu.ClearcoatPbrWgpuMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const clearcoatPbrWgpuMeshMaterialRenderer = api.clearcoatPbrWgpuMeshMaterialRenderer;
export const registerClearcoatPbrWgpuMaterial = api.registerClearcoatPbrWgpuMaterial;
