// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.SceneWgpu;
function __syncDependencies() {}
__syncDependencies();

export const bindWgpuClassicSurface = api.bindWgpuClassicSurface;
export const buildWgpuClassicDefineKey = api.buildWgpuClassicDefineKey;
export const compileWgpuClassicPipeline = api.compileWgpuClassicPipeline;
export const ensureWgpuClassicPipeline = api.ensureWgpuClassicPipeline;
export const getWgpuClassicModuleSourceForKey = api.getWgpuClassicModuleSourceForKey;
