// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.SceneWgpu;
function __syncDependencies() {}
__syncDependencies();

export const ensureWgpuWireframeUpload = api.ensureWgpuWireframeUpload;
