// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.SceneWgpu;
function __syncDependencies() {}
__syncDependencies();

export const beginWgpuMeshDraw = api.beginWgpuMeshDraw;
export const createWgpuMeshPipeline = api.createWgpuMeshPipeline;
export const drawWgpuMeshSubset = api.drawWgpuMeshSubset;
export const ensureWgpuFrameBindGroup = api.ensureWgpuFrameBindGroup;
export const ensureWgpuIblSampleBindGroup = api.ensureWgpuIblSampleBindGroup;
export const ensureWgpuIblSampleLayout = api.ensureWgpuIblSampleLayout;
export const ensureWgpuPbrSampleBindGroup = api.ensureWgpuPbrSampleBindGroup;
export const ensureWgpuPbrSampleLayout = api.ensureWgpuPbrSampleLayout;
export const ensureWgpuPlaceholderTextureView = api.ensureWgpuPlaceholderTextureView;
export const ensureWgpuSceneLayouts = api.ensureWgpuSceneLayouts;
export const ensureWgpuScenePipeline = api.ensureWgpuScenePipeline;
export const ensureWgpuShadowSampleBindGroup = api.ensureWgpuShadowSampleBindGroup;
export const ensureWgpuShadowSampleLayout = api.ensureWgpuShadowSampleLayout;
export const getWgpuMaterialSampler = api.getWgpuMaterialSampler;
export const isWgpuTextureReady = api.isWgpuTextureReady;
export const resolveWgpuMaterialTextureView = api.resolveWgpuMaterialTextureView;
export const SHADOW_DEPTH_FORMAT = api.SHADOW_DEPTH_FORMAT;
export const stashWgpuUvTransform = api.stashWgpuUvTransform;
export const WGPU_MESH_PRELUDE_WGSL = api.WGPU_MESH_PRELUDE_WGSL;
export const writeWgpuDrawUniform = api.writeWgpuDrawUniform;
export const writeWgpuFrameUniform = api.writeWgpuFrameUniform;
