// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.materials.SheenPbrExtension;
function __syncDependencies() {}
__syncDependencies();

export const createSheenPbrExtension = api.createSheenPbrExtension;
export const isValidSheenPbrExtension = api.isValidSheenPbrExtension;
