// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.Materials;
function __syncDependencies() {}
__syncDependencies();

export const createSurfaceMaterial = api.createSurfaceMaterial;
export const getMaterialAlphaMode = api.getMaterialAlphaMode;
export const isMaterialBlended = api.isMaterialBlended;
export const isMaterialMasked = api.isMaterialMasked;
export const isMaterialOpaque = api.isMaterialOpaque;
