// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._TextureAtlasFormats;
function __syncDependencies() {}
__syncDependencies();

export const parseTexturePackerAtlasDocument = api.parseTexturePackerAtlasDocument;
export const parseTexturePackerAtlasJson = api.parseTexturePackerAtlasJson;
