// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.picking.PickScene;
function __syncDependencies() {}
__syncDependencies();

export const createSceneHit = api.createSceneHit;
export const pickScene = api.pickScene;
export const pickSceneAll = api.pickSceneAll;
export const pickSceneAllWithRay3D = api.pickSceneAllWithRay3D;
export const pickSceneWithRay3D = api.pickSceneWithRay3D;
