// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.renderWgpu.WgpuRenderTexturePool;
function __syncDependencies() {}
__syncDependencies();

export const acquireWgpuRenderTexture = api.acquireWgpuRenderTexture;
export const createWgpuRenderTexturePool = api.createWgpuRenderTexturePool;
export const destroyWgpuRenderTexturePool = api.destroyWgpuRenderTexturePool;
export const releaseWgpuRenderTexture = api.releaseWgpuRenderTexture;
export const withWgpuRenderTextures = api.withWgpuRenderTextures;
