// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._RenderWgpu;
function __syncDependencies() {}
__syncDependencies();

export const applyWgpuScissorRect = api.applyWgpuScissorRect;
export const popWgpuScissorRect = api.popWgpuScissorRect;
export const pushWgpuScissorRect = api.pushWgpuScissorRect;
export const setWgpuRenderPassScissorRect = api.setWgpuRenderPassScissorRect;
