// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._RenderWgpu;
function __syncDependencies() {}
__syncDependencies();

export const acquireWgpuSurfaceAntialiasView = api.acquireWgpuSurfaceAntialiasView;
export const clearWgpuSurfacePresentation = api.clearWgpuSurfacePresentation;
export const encodeWgpuSurfaceAntialiasResolve = api.encodeWgpuSurfaceAntialiasResolve;
export const getWgpuSurfaceRenderExtent = api.getWgpuSurfaceRenderExtent;
export const getWgpuSurfaceRenderScale = api.getWgpuSurfaceRenderScale;
