// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._RenderWgpu;
function __syncDependencies() {}
__syncDependencies();

export const createReadyImageElementForTest = api.createReadyImageElementForTest;
export const createWgpuRenderStateForTest = api.createWgpuRenderStateForTest;
export const installWgpuMock = api.installWgpuMock;
