// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._GlyphAtlas;
function __syncDependencies() {}
__syncDependencies();

export const createGlyphAtlas = api.createGlyphAtlas;
export const deriveGlyphMetricsFromFontSize = api.deriveGlyphMetricsFromFontSize;
export const disposeGlyphAtlas = api.disposeGlyphAtlas;
export const getGlyphAtlasBitmap = api.getGlyphAtlasBitmap;
export const getGlyphAtlasLayoutVersion = api.getGlyphAtlasLayoutVersion;
export const initializeGlyphAtlas = api.initializeGlyphAtlas;
