// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Gui;
function __syncDependencies() {}
__syncDependencies();

export const createScrollBarController = api.createScrollBarController;
export const disposeScrollBarController = api.disposeScrollBarController;
export const getScrollBarControllerSignals = api.getScrollBarControllerSignals;
export const getScrollBarControllerValue = api.getScrollBarControllerValue;
export const setScrollBarControllerValue = api.setScrollBarControllerValue;
