// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Gui;
function __syncDependencies() {}
__syncDependencies();

export const createSplitPaneController = api.createSplitPaneController;
export const disposeSplitPaneController = api.disposeSplitPaneController;
export const getSplitPaneControllerPosition = api.getSplitPaneControllerPosition;
export const getSplitPaneControllerSignals = api.getSplitPaneControllerSignals;
export const setSplitPaneControllerPosition = api.setSplitPaneControllerPosition;
