// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Gui;
function __syncDependencies() {}
__syncDependencies();

export const createTooltipController = api.createTooltipController;
export const disposeTooltipController = api.disposeTooltipController;
export const hideTooltipController = api.hideTooltipController;
export const showTooltipController = api.showTooltipController;
