// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-wgpu/contract';
import * as __dependency1 from './wgpuEffectBlitShader.mjs';
import * as __dependency2 from './wgpuEffectBoxBlur.mjs';
import * as __dependency3 from './wgpuEffectGradientRamp.mjs';
import * as __dependency4 from './wgpuEffectPass.mjs';
import * as __dependency5 from './wgpuEffectTintShader.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._RenderWgpu.acquireWgpuRenderTarget = __dependency0.acquireWgpuRenderTarget;
  compiled.flight._RenderWgpu.releaseWgpuRenderTarget = __dependency0.releaseWgpuRenderTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectBlitPass = __dependency1.applyWgpuEffectBlitPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectErasePass = __dependency1.applyWgpuEffectErasePass;
  compiled.flight._EffectsWgpu.applyWgpuEffectBoxBlur = __dependency2.applyWgpuEffectBoxBlur;
  compiled.flight._EffectsWgpu.getWgpuEffectGradientRampTexture = __dependency3.getWgpuEffectGradientRampTexture;
  compiled.flight._EffectsWgpu.clearWgpuEffectTarget = __dependency4.clearWgpuEffectTarget;
  compiled.flight._EffectsWgpu.getWgpuEffectPassState = __dependency4.getWgpuEffectPassState;
  compiled.flight._EffectsWgpu.applyWgpuEffectTintPass = __dependency5.applyWgpuEffectTintPass;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency0.getWgpuRenderStateRuntime;
  compiled.flight._RenderWgpu.getWgpuSampler = __dependency0.getWgpuSampler;
  compiled.flight._RenderWgpu.resolveWgpuTexture = __dependency0.resolveWgpuTexture;
}
__syncDependencies();

const __bridgeImplementation_applyGradientGlowEffectToWgpu = api.applyGradientGlowEffectToWgpu;
export function applyGradientGlowEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyGradientGlowEffectToWgpu(...args); return result; }
api.applyGradientGlowEffectToWgpu = applyGradientGlowEffectToWgpu;
compiled.flight.EffectsWgpu.applyGradientGlowEffectToWgpu = applyGradientGlowEffectToWgpu;
const __bridgeImplementation_defaultWgpuGradientGlowEffectRunner = api.defaultWgpuGradientGlowEffectRunner;
export function defaultWgpuGradientGlowEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuGradientGlowEffectRunner(...args); }
api.defaultWgpuGradientGlowEffectRunner = defaultWgpuGradientGlowEffectRunner;
const __bridgeImplementation_registerWgpuGradientGlowEffect = api.registerWgpuGradientGlowEffect;
export function registerWgpuGradientGlowEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuGradientGlowEffect(...args); return result; }
api.registerWgpuGradientGlowEffect = registerWgpuGradientGlowEffect;
compiled.flight.EffectsWgpu.registerWgpuGradientGlowEffect = registerWgpuGradientGlowEffect;
