// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyWhiteBalanceEffectToWgpu = api.applyWhiteBalanceEffectToWgpu;
export function applyWhiteBalanceEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyWhiteBalanceEffectToWgpu(...args); return result; }
api.applyWhiteBalanceEffectToWgpu = applyWhiteBalanceEffectToWgpu;
compiled.flight.EffectsWgpu.applyWhiteBalanceEffectToWgpu = applyWhiteBalanceEffectToWgpu;
const __bridgeImplementation_defaultWgpuWhiteBalanceEffectRunner = api.defaultWgpuWhiteBalanceEffectRunner;
export function defaultWgpuWhiteBalanceEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuWhiteBalanceEffectRunner(...args); }
api.defaultWgpuWhiteBalanceEffectRunner = defaultWgpuWhiteBalanceEffectRunner;
const __bridgeImplementation_registerWgpuWhiteBalanceEffect = api.registerWgpuWhiteBalanceEffect;
export function registerWgpuWhiteBalanceEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuWhiteBalanceEffect(...args); return result; }
api.registerWgpuWhiteBalanceEffect = registerWgpuWhiteBalanceEffect;
compiled.flight.EffectsWgpu.registerWgpuWhiteBalanceEffect = registerWgpuWhiteBalanceEffect;
