// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.getWgpuEffectPassState = __dependency0.getWgpuEffectPassState;
}
__syncDependencies();

const __bridgeImplementation_applyColorLutPassToWgpu = api.applyColorLutPassToWgpu;
export function applyColorLutPassToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyColorLutPassToWgpu(...args); return result; }
api.applyColorLutPassToWgpu = applyColorLutPassToWgpu;
compiled.flight.EffectsWgpu.applyColorLutPassToWgpu = applyColorLutPassToWgpu;
