// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-wgpu/contract';
import * as __dependency1 from './wgpuEffectPass.mjs';
import * as __dependency2 from './wgpuEffectProgramCache.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._RenderWgpu.getWgpuSampler = __dependency0.getWgpuSampler;
  compiled.flight._RenderWgpu.resolveWgpuTexture = __dependency0.resolveWgpuTexture;
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency1.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPassState = __dependency1.getWgpuEffectPassState;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency2.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency0.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyBitmapDisplacementEffectToWgpu = api.applyBitmapDisplacementEffectToWgpu;
export function applyBitmapDisplacementEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyBitmapDisplacementEffectToWgpu(...args); return result; }
api.applyBitmapDisplacementEffectToWgpu = applyBitmapDisplacementEffectToWgpu;
compiled.flight.EffectsWgpu.applyBitmapDisplacementEffectToWgpu = applyBitmapDisplacementEffectToWgpu;
export const BITMAP_DISPLACEMENT_FRAGMENT_WGSL = api.BITMAP_DISPLACEMENT_FRAGMENT_WGSL;
const __bridgeImplementation_defaultWgpuBitmapDisplacementEffectRunner = api.defaultWgpuBitmapDisplacementEffectRunner;
export function defaultWgpuBitmapDisplacementEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuBitmapDisplacementEffectRunner(...args); }
api.defaultWgpuBitmapDisplacementEffectRunner = defaultWgpuBitmapDisplacementEffectRunner;
const __bridgeImplementation_initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect = api.initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect;
export function initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect(...args); return result; }
api.initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect = initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect;
compiled.flight.EffectsWgpu.initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect = initializeWgpuEffectPipeline__wgpuBitmapDisplacementEffect;
const __bridgeImplementation_isWgpuBitmapDisplacementEffectResolvable = api.isWgpuBitmapDisplacementEffectResolvable;
export function isWgpuBitmapDisplacementEffectResolvable(...args) { __syncDependencies(); const result = __bridgeImplementation_isWgpuBitmapDisplacementEffectResolvable(...args); return result; }
api.isWgpuBitmapDisplacementEffectResolvable = isWgpuBitmapDisplacementEffectResolvable;
compiled.flight.EffectsWgpu.isWgpuBitmapDisplacementEffectResolvable = isWgpuBitmapDisplacementEffectResolvable;
const __bridgeImplementation_registerWgpuBitmapDisplacementEffect = api.registerWgpuBitmapDisplacementEffect;
export function registerWgpuBitmapDisplacementEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuBitmapDisplacementEffect(...args); return result; }
api.registerWgpuBitmapDisplacementEffect = registerWgpuBitmapDisplacementEffect;
compiled.flight.EffectsWgpu.registerWgpuBitmapDisplacementEffect = registerWgpuBitmapDisplacementEffect;
