// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyDisplacementEffectToWgpu = api.applyDisplacementEffectToWgpu;
export function applyDisplacementEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyDisplacementEffectToWgpu(...args); return result; }
api.applyDisplacementEffectToWgpu = applyDisplacementEffectToWgpu;
compiled.flight.EffectsWgpu.applyDisplacementEffectToWgpu = applyDisplacementEffectToWgpu;
const __bridgeImplementation_defaultWgpuDisplacementEffectRunner = api.defaultWgpuDisplacementEffectRunner;
export function defaultWgpuDisplacementEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuDisplacementEffectRunner(...args); }
api.defaultWgpuDisplacementEffectRunner = defaultWgpuDisplacementEffectRunner;
const __bridgeImplementation_registerWgpuDisplacementEffect = api.registerWgpuDisplacementEffect;
export function registerWgpuDisplacementEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuDisplacementEffect(...args); return result; }
api.registerWgpuDisplacementEffect = registerWgpuDisplacementEffect;
compiled.flight.EffectsWgpu.registerWgpuDisplacementEffect = registerWgpuDisplacementEffect;
