// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyFilmGrainEffectToWgpu = api.applyFilmGrainEffectToWgpu;
export function applyFilmGrainEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyFilmGrainEffectToWgpu(...args); return result; }
api.applyFilmGrainEffectToWgpu = applyFilmGrainEffectToWgpu;
compiled.flight.EffectsWgpu.applyFilmGrainEffectToWgpu = applyFilmGrainEffectToWgpu;
const __bridgeImplementation_defaultWgpuFilmGrainEffectRunner = api.defaultWgpuFilmGrainEffectRunner;
export function defaultWgpuFilmGrainEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuFilmGrainEffectRunner(...args); }
api.defaultWgpuFilmGrainEffectRunner = defaultWgpuFilmGrainEffectRunner;
const __bridgeImplementation_registerWgpuFilmGrainEffect = api.registerWgpuFilmGrainEffect;
export function registerWgpuFilmGrainEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuFilmGrainEffect(...args); return result; }
api.registerWgpuFilmGrainEffect = registerWgpuFilmGrainEffect;
compiled.flight.EffectsWgpu.registerWgpuFilmGrainEffect = registerWgpuFilmGrainEffect;
