// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.EffectsWgpu;
function __syncDependencies() {}
__syncDependencies();

export const applyMedianEffectToWgpu = api.applyMedianEffectToWgpu;
export const defaultWgpuMedianEffectRunner = api.defaultWgpuMedianEffectRunner;
export const MAX_MEDIAN_EFFECT_WGPU_RADIUS = api.MAX_MEDIAN_EFFECT_WGPU_RADIUS;
