// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyDitherEffectToWgpu = api.applyDitherEffectToWgpu;
export function applyDitherEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyDitherEffectToWgpu(...args); return result; }
api.applyDitherEffectToWgpu = applyDitherEffectToWgpu;
compiled.flight.EffectsWgpu.applyDitherEffectToWgpu = applyDitherEffectToWgpu;
const __bridgeImplementation_defaultWgpuDitherEffectRunner = api.defaultWgpuDitherEffectRunner;
export function defaultWgpuDitherEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuDitherEffectRunner(...args); }
api.defaultWgpuDitherEffectRunner = defaultWgpuDitherEffectRunner;
const __bridgeImplementation_registerWgpuDitherEffect = api.registerWgpuDitherEffect;
export function registerWgpuDitherEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuDitherEffect(...args); return result; }
api.registerWgpuDitherEffect = registerWgpuDitherEffect;
compiled.flight.EffectsWgpu.registerWgpuDitherEffect = registerWgpuDitherEffect;
