// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsWgpu.WgpuLensFlareEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyLensFlareEffectToWgpu = api.applyLensFlareEffectToWgpu;
export const defaultWgpuLensFlareEffectRunner = api.defaultWgpuLensFlareEffectRunner;
