// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.createWgpuDualSourceEffectPipeline = __dependency0.createWgpuDualSourceEffectPipeline;
  compiled.flight._EffectsWgpu.drawWgpuDualSourceEffectPass = __dependency0.drawWgpuDualSourceEffectPass;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency1.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyBlendEffectToWgpu = api.applyBlendEffectToWgpu;
export function applyBlendEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyBlendEffectToWgpu(...args); return result; }
api.applyBlendEffectToWgpu = applyBlendEffectToWgpu;
compiled.flight.EffectsWgpu.applyBlendEffectToWgpu = applyBlendEffectToWgpu;
const __bridgeImplementation_defaultWgpuBlendEffectRunner = api.defaultWgpuBlendEffectRunner;
export function defaultWgpuBlendEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuBlendEffectRunner(...args); }
api.defaultWgpuBlendEffectRunner = defaultWgpuBlendEffectRunner;
const __bridgeImplementation_getWgpuBlendEffectBackdrop = api.getWgpuBlendEffectBackdrop;
export function getWgpuBlendEffectBackdrop(...args) { __syncDependencies(); const result = __bridgeImplementation_getWgpuBlendEffectBackdrop(...args); return result; }
api.getWgpuBlendEffectBackdrop = getWgpuBlendEffectBackdrop;
compiled.flight.EffectsWgpu.getWgpuBlendEffectBackdrop = getWgpuBlendEffectBackdrop;
const __bridgeImplementation_getWgpuBlendEffectModeIndex = api.getWgpuBlendEffectModeIndex;
export function getWgpuBlendEffectModeIndex(...args) { __syncDependencies(); const result = __bridgeImplementation_getWgpuBlendEffectModeIndex(...args); return result; }
api.getWgpuBlendEffectModeIndex = getWgpuBlendEffectModeIndex;
compiled.flight.EffectsWgpu.getWgpuBlendEffectModeIndex = getWgpuBlendEffectModeIndex;
const __bridgeImplementation_registerWgpuBlendEffect = api.registerWgpuBlendEffect;
export function registerWgpuBlendEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuBlendEffect(...args); return result; }
api.registerWgpuBlendEffect = registerWgpuBlendEffect;
compiled.flight.EffectsWgpu.registerWgpuBlendEffect = registerWgpuBlendEffect;
const __bridgeImplementation_registerWgpuBlendEffectBackdrop = api.registerWgpuBlendEffectBackdrop;
export function registerWgpuBlendEffectBackdrop(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuBlendEffectBackdrop(...args); return result; }
api.registerWgpuBlendEffectBackdrop = registerWgpuBlendEffectBackdrop;
compiled.flight.EffectsWgpu.registerWgpuBlendEffectBackdrop = registerWgpuBlendEffectBackdrop;
const __bridgeImplementation_unregisterWgpuBlendEffectBackdrop = api.unregisterWgpuBlendEffectBackdrop;
export function unregisterWgpuBlendEffectBackdrop(...args) { __syncDependencies(); const result = __bridgeImplementation_unregisterWgpuBlendEffectBackdrop(...args); return result; }
api.unregisterWgpuBlendEffectBackdrop = unregisterWgpuBlendEffectBackdrop;
compiled.flight.EffectsWgpu.unregisterWgpuBlendEffectBackdrop = unregisterWgpuBlendEffectBackdrop;
export const WGPU_BLEND_FRAGMENT_WGSL = api.WGPU_BLEND_FRAGMENT_WGSL;
