// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-wgpu/contract';
import * as __dependency1 from './wgpuEffectBlitShader.mjs';
import * as __dependency2 from './wgpuEffectBoxBlur.mjs';
import * as __dependency3 from './wgpuEffectPass.mjs';
import * as __dependency4 from './wgpuEffectTintShader.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._RenderWgpu.acquireWgpuRenderTarget = __dependency0.acquireWgpuRenderTarget;
  compiled.flight._RenderWgpu.releaseWgpuRenderTarget = __dependency0.releaseWgpuRenderTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectBlitPass = __dependency1.applyWgpuEffectBlitPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectBoxBlur = __dependency2.applyWgpuEffectBoxBlur;
  compiled.flight._EffectsWgpu.clearWgpuEffectTarget = __dependency3.clearWgpuEffectTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectInnerClipPass = __dependency4.applyWgpuEffectInnerClipPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectInvertTintPass = __dependency4.applyWgpuEffectInvertTintPass;
}
__syncDependencies();

export function applyInnerGlowEffectToWgpu(...args) { __syncDependencies(); const result = api.applyInnerGlowEffectToWgpu(...args); return result; }
const __bridgeImplementation_defaultWgpuInnerGlowEffectRunner = api.defaultWgpuInnerGlowEffectRunner;
export function defaultWgpuInnerGlowEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuInnerGlowEffectRunner(...args); }
api.defaultWgpuInnerGlowEffectRunner = defaultWgpuInnerGlowEffectRunner;
export function registerWgpuInnerGlowEffect(...args) { __syncDependencies(); const result = api.registerWgpuInnerGlowEffect(...args); return result; }
