// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-wgpu/contract';
import * as __dependency1 from './wgpuEffectBlitShader.mjs';
import * as __dependency2 from './wgpuEffectBoxBlur.mjs';
import * as __dependency3 from './wgpuEffectGradientRamp.mjs';
import * as __dependency4 from './wgpuEffectPass.mjs';
import * as __dependency5 from './wgpuEffectTintShader.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._RenderWgpu.acquireWgpuRenderTarget = __dependency0.acquireWgpuRenderTarget;
  compiled.flight._RenderWgpu.releaseWgpuRenderTarget = __dependency0.releaseWgpuRenderTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectBlitPass = __dependency1.applyWgpuEffectBlitPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectErasePass = __dependency1.applyWgpuEffectErasePass;
  compiled.flight._EffectsWgpu.applyWgpuEffectBoxBlur = __dependency2.applyWgpuEffectBoxBlur;
  compiled.flight._EffectsWgpu.getWgpuEffectGradientRampTexture = __dependency3.getWgpuEffectGradientRampTexture;
  compiled.flight._EffectsWgpu.clearWgpuEffectTarget = __dependency4.clearWgpuEffectTarget;
  compiled.flight._EffectsWgpu.EFFECT_VERTEX_WGSL = __dependency4.EFFECT_VERTEX_WGSL;
  compiled.flight._EffectsWgpu.getWgpuEffectPassState = __dependency4.getWgpuEffectPassState;
  compiled.flight._EffectsWgpu.applyWgpuEffectTintPass = __dependency5.applyWgpuEffectTintPass;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency0.getWgpuRenderStateRuntime;
}
__syncDependencies();

export const applyGradientBevelEffectToWgpu = api.applyGradientBevelEffectToWgpu;
export const defaultWgpuGradientBevelEffectRunner = api.defaultWgpuGradientBevelEffectRunner;
export const registerWgpuGradientBevelEffect = api.registerWgpuGradientBevelEffect;
