// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';

const api = compiled.flight.EffectsWgpu;
function __syncDependencies() {
  compiled.flight.EffectsWgpu.createWgpuDualSourceEffectPipeline = __dependency0.createWgpuDualSourceEffectPipeline;
  compiled.flight.EffectsWgpu.createWgpuEffectPipeline = __dependency0.createWgpuEffectPipeline;
  compiled.flight.EffectsWgpu.drawWgpuDualSourceEffectPass = __dependency0.drawWgpuDualSourceEffectPass;
  compiled.flight.EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
}
__syncDependencies();

export const applyWgpuEffectInnerClipPass = api.applyWgpuEffectInnerClipPass;
export const applyWgpuEffectInvertTintPass = api.applyWgpuEffectInvertTintPass;
export const applyWgpuEffectTintPass = api.applyWgpuEffectTintPass;
