// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsWgpu.WgpuCompositeEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyCompositeEffectToWgpu = api.applyCompositeEffectToWgpu;
export const defaultWgpuCompositeEffectRunner = api.defaultWgpuCompositeEffectRunner;
export const getWgpuCompositeEffectOperatorIndex = api.getWgpuCompositeEffectOperatorIndex;
export const registerWgpuCompositeEffect = api.registerWgpuCompositeEffect;
export const WGPU_COMPOSITE_FRAGMENT_WGSL = api.WGPU_COMPOSITE_FRAGMENT_WGSL;
