// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyPosterizeEffectToWgpu = api.applyPosterizeEffectToWgpu;
export function applyPosterizeEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyPosterizeEffectToWgpu(...args); return result; }
api.applyPosterizeEffectToWgpu = applyPosterizeEffectToWgpu;
compiled.flight.EffectsWgpu.applyPosterizeEffectToWgpu = applyPosterizeEffectToWgpu;
const __bridgeImplementation_defaultWgpuPosterizeEffectRunner = api.defaultWgpuPosterizeEffectRunner;
export function defaultWgpuPosterizeEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuPosterizeEffectRunner(...args); }
api.defaultWgpuPosterizeEffectRunner = defaultWgpuPosterizeEffectRunner;
const __bridgeImplementation_registerWgpuPosterizeEffect = api.registerWgpuPosterizeEffect;
export function registerWgpuPosterizeEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuPosterizeEffect(...args); return result; }
api.registerWgpuPosterizeEffect = registerWgpuPosterizeEffect;
compiled.flight.EffectsWgpu.registerWgpuPosterizeEffect = registerWgpuPosterizeEffect;
