// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectBlitShader.mjs';
import * as __dependency1 from './wgpuEffectBoxBlur.mjs';
import * as __dependency2 from './wgpuEffectPass.mjs';
import * as __dependency3 from './wgpuEffectTintShader.mjs';

const api = compiled.flighthq.effectsWgpu.WgpuDropShadowEffect;
function __syncDependencies() {
  compiled.flighthq.effectsWgpu.WgpuEffectBlitShader.applyWgpuEffectBlitOffsetPass = __dependency0.applyWgpuEffectBlitOffsetPass;
  compiled.flighthq.effectsWgpu.WgpuEffectBlitShader.applyWgpuEffectBlitPass = __dependency0.applyWgpuEffectBlitPass;
  compiled.flighthq.effectsWgpu.WgpuEffectBlitShader.applyWgpuEffectErasePass = __dependency0.applyWgpuEffectErasePass;
  compiled.flighthq.effectsWgpu.WgpuEffectBoxBlur.applyWgpuEffectBoxBlur = __dependency1.applyWgpuEffectBoxBlur;
  compiled.flighthq.effectsWgpu.WgpuEffectPass.clearWgpuEffectTarget = __dependency2.clearWgpuEffectTarget;
  compiled.flighthq.effectsWgpu.WgpuEffectTintShader.applyWgpuEffectTintPass = __dependency3.applyWgpuEffectTintPass;
}
__syncDependencies();

export const applyDropShadowEffectToWgpu = api.applyDropShadowEffectToWgpu;
export const defaultWgpuDropShadowEffectRunner = api.defaultWgpuDropShadowEffectRunner;
export const registerWgpuDropShadowEffect = api.registerWgpuDropShadowEffect;
