// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {}
__syncDependencies();

export const applyBlendEffectToWgpu = api.applyBlendEffectToWgpu;
export const defaultWgpuBlendEffectRunner = api.defaultWgpuBlendEffectRunner;
export const getWgpuBlendEffectBackdrop = api.getWgpuBlendEffectBackdrop;
export const getWgpuBlendEffectModeIndex = api.getWgpuBlendEffectModeIndex;
export const registerWgpuBlendEffect = api.registerWgpuBlendEffect;
export const registerWgpuBlendEffectBackdrop = api.registerWgpuBlendEffectBackdrop;
export const unregisterWgpuBlendEffectBackdrop = api.unregisterWgpuBlendEffectBackdrop;
export const WGPU_BLEND_FRAGMENT_WGSL = api.WGPU_BLEND_FRAGMENT_WGSL;
