// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
}
__syncDependencies();

export function applyGodRaysEffectToWgpu(...args) { __syncDependencies(); const result = api.applyGodRaysEffectToWgpu(...args); return result; }
const __bridgeImplementation_defaultWgpuGodRaysEffectRunner = api.defaultWgpuGodRaysEffectRunner;
export function defaultWgpuGodRaysEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuGodRaysEffectRunner(...args); }
api.defaultWgpuGodRaysEffectRunner = defaultWgpuGodRaysEffectRunner;
export function registerWgpuGodRaysEffect(...args) { __syncDependencies(); const result = api.registerWgpuGodRaysEffect(...args); return result; }
