// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-wgpu/contract';
import * as __dependency1 from './wgpuEffectBlitShader.mjs';
import * as __dependency2 from './wgpuEffectBoxBlur.mjs';
import * as __dependency3 from './wgpuEffectPass.mjs';
import * as __dependency4 from './wgpuEffectTintShader.mjs';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._RenderWgpu.acquireWgpuRenderTarget = __dependency0.acquireWgpuRenderTarget;
  compiled.flight._RenderWgpu.releaseWgpuRenderTarget = __dependency0.releaseWgpuRenderTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectBlitOffsetPass = __dependency1.applyWgpuEffectBlitOffsetPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectBlitPass = __dependency1.applyWgpuEffectBlitPass;
  compiled.flight._EffectsWgpu.applyWgpuEffectErasePass = __dependency1.applyWgpuEffectErasePass;
  compiled.flight._EffectsWgpu.applyWgpuEffectBoxBlur = __dependency2.applyWgpuEffectBoxBlur;
  compiled.flight._EffectsWgpu.clearWgpuEffectTarget = __dependency3.clearWgpuEffectTarget;
  compiled.flight._EffectsWgpu.applyWgpuEffectTintPass = __dependency4.applyWgpuEffectTintPass;
}
__syncDependencies();

export function applyDropShadowEffectToWgpu(...args) { __syncDependencies(); const result = api.applyDropShadowEffectToWgpu(...args); return result; }
const __bridgeImplementation_defaultWgpuDropShadowEffectRunner = api.defaultWgpuDropShadowEffectRunner;
export function defaultWgpuDropShadowEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuDropShadowEffectRunner(...args); }
api.defaultWgpuDropShadowEffectRunner = defaultWgpuDropShadowEffectRunner;
export function registerWgpuDropShadowEffect(...args) { __syncDependencies(); const result = api.registerWgpuDropShadowEffect(...args); return result; }
