// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './wgpuEffectPass.mjs';
import * as __dependency1 from './wgpuEffectProgramCache.mjs';
import * as __dependency2 from '@flighthq/render-wgpu/contract';

const api = compiled.flight._EffectsWgpu;
function __syncDependencies() {
  compiled.flight._EffectsWgpu.drawWgpuEffectPass = __dependency0.drawWgpuEffectPass;
  compiled.flight._EffectsWgpu.getWgpuEffectPipeline = __dependency1.getWgpuEffectPipeline;
  compiled.flight._RenderWgpu.getWgpuRenderStateRuntime = __dependency2.getWgpuRenderStateRuntime;
}
__syncDependencies();

const __bridgeImplementation_applyCrtEffectToWgpu = api.applyCrtEffectToWgpu;
export function applyCrtEffectToWgpu(...args) { __syncDependencies(); const result = __bridgeImplementation_applyCrtEffectToWgpu(...args); return result; }
api.applyCrtEffectToWgpu = applyCrtEffectToWgpu;
compiled.flight.EffectsWgpu.applyCrtEffectToWgpu = applyCrtEffectToWgpu;
const __bridgeImplementation_defaultWgpuCrtEffectRunner = api.defaultWgpuCrtEffectRunner;
export function defaultWgpuCrtEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultWgpuCrtEffectRunner(...args); }
api.defaultWgpuCrtEffectRunner = defaultWgpuCrtEffectRunner;
const __bridgeImplementation_registerWgpuCrtEffect = api.registerWgpuCrtEffect;
export function registerWgpuCrtEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerWgpuCrtEffect(...args); return result; }
api.registerWgpuCrtEffect = registerWgpuCrtEffect;
compiled.flight.EffectsWgpu.registerWgpuCrtEffect = registerWgpuCrtEffect;
