// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.CameraApi;
function __syncDependencies() {}
__syncDependencies();

export const getCameraFrustum = api.getCameraFrustum;
export const isBoxInCameraFrustum = api.isBoxInCameraFrustum;
export const isPointInCameraFrustum = api.isPointInCameraFrustum;
export const isSphereInCameraFrustum = api.isSphereInCameraFrustum;
