// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.CameraApi;
function __syncDependencies() {}
__syncDependencies();

export const getCameraLinearDepth = api.getCameraLinearDepth;
export const getCameraViewSpaceZ = api.getCameraViewSpaceZ;
