// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.camera.ExplainCamera3DView;
function __syncDependencies() {}
__syncDependencies();

export const explainCamera3DView = api.explainCamera3DView;
