// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.camera.FrustumCorners;
function __syncDependencies() {}
__syncDependencies();

export const getCameraFrustumCorners = api.getCameraFrustumCorners;
