// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.camera.Projection;
function __syncDependencies() {}
__syncDependencies();

export const createOrthographicProjection = api.createOrthographicProjection;
export const createPerspectiveProjection = api.createPerspectiveProjection;
export const isOrthographicProjection = api.isOrthographicProjection;
export const isPerspectiveProjection = api.isPerspectiveProjection;
export const setProjectionMatrix4 = api.setProjectionMatrix4;
