// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.camera.VisibleBounds;
function __syncDependencies() {}
__syncDependencies();

export const getCamera2DVisibleBounds = api.getCamera2DVisibleBounds;
