// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.skeleton2d.EnableSkeleton2DGuards;
function __syncDependencies() {}
__syncDependencies();

export const disableSkeleton2DGuards = api.disableSkeleton2DGuards;
export const enableSkeleton2DGuards = api.enableSkeleton2DGuards;
