// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.MeshApi;
function __syncDependencies() {}
__syncDependencies();

export const centerMeshGeometry = api.centerMeshGeometry;
export const scaleMeshGeometry = api.scaleMeshGeometry;
export const transformMeshGeometry = api.transformMeshGeometry;
export const transformMeshGeometryInto = api.transformMeshGeometryInto;
export const translateMeshGeometry = api.translateMeshGeometry;
