// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.mesh.MeshGeometryOperations;
function __syncDependencies() {}
__syncDependencies();

export const createMeshGeometryFromAttributes = api.createMeshGeometryFromAttributes;
export const getMeshGeometryTriangleCount = api.getMeshGeometryTriangleCount;
export const getMeshGeometryTriangleVertexIndices = api.getMeshGeometryTriangleVertexIndices;
export const mergeMeshGeometries = api.mergeMeshGeometries;
export const validateMeshGeometry = api.validateMeshGeometry;
