// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.MeshApi;
function __syncDependencies() {}
__syncDependencies();

export const createBoxMeshGeometry = api.createBoxMeshGeometry;
export const createCapsuleMeshGeometry = api.createCapsuleMeshGeometry;
export const createCircleMeshGeometry = api.createCircleMeshGeometry;
export const createConeMeshGeometry = api.createConeMeshGeometry;
export const createCylinderMeshGeometry = api.createCylinderMeshGeometry;
export const createDodecahedronMeshGeometry = api.createDodecahedronMeshGeometry;
export const createIcosahedronMeshGeometry = api.createIcosahedronMeshGeometry;
export const createIcosphereMeshGeometry = api.createIcosphereMeshGeometry;
export const createOctahedronMeshGeometry = api.createOctahedronMeshGeometry;
export const createPlaneMeshGeometry = api.createPlaneMeshGeometry;
export const createPolyhedronMeshGeometry = api.createPolyhedronMeshGeometry;
export const createQuadMeshGeometry = api.createQuadMeshGeometry;
export const createRingMeshGeometry = api.createRingMeshGeometry;
export const createSphereMeshGeometry = api.createSphereMeshGeometry;
export const createTetrahedronMeshGeometry = api.createTetrahedronMeshGeometry;
export const createTorusKnotMeshGeometry = api.createTorusKnotMeshGeometry;
export const createTorusMeshGeometry = api.createTorusMeshGeometry;
