// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Geometry;
function __syncDependencies() {}
__syncDependencies();

export const cloneAabb = api.cloneAabb;
export const containsAabbPoint = api.containsAabbPoint;
export const copyAabb = api.copyAabb;
export const createAabb = api.createAabb;
export const expandAabbByPoint = api.expandAabbByPoint;
export const expandAabbBySphere = api.expandAabbBySphere;
export const getAabbCenter = api.getAabbCenter;
export const getAabbExtents = api.getAabbExtents;
export const getAabbSize = api.getAabbSize;
export const getClosestPointOnAabb = api.getClosestPointOnAabb;
export const intersectAabb = api.intersectAabb;
export const isAabbIntersectingAabb = api.isAabbIntersectingAabb;
export const setAabb = api.setAabb;
export const setAabbFromPoints = api.setAabbFromPoints;
export const transformAabbByMatrix4 = api.transformAabbByMatrix4;
export const unionAabb = api.unionAabb;
