// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.geometry.Matrix3;
function __syncDependencies() {}
__syncDependencies();

export const cloneMatrix3 = api.cloneMatrix3;
export const copyMatrix3 = api.copyMatrix3;
export const copyMatrix3ColumnFromVector3 = api.copyMatrix3ColumnFromVector3;
export const copyMatrix3ColumnToVector3 = api.copyMatrix3ColumnToVector3;
export const copyMatrix3RowFromVector3 = api.copyMatrix3RowFromVector3;
export const copyMatrix3RowToVector3 = api.copyMatrix3RowToVector3;
export const createMatrix3 = api.createMatrix3;
export const equalsMatrix3 = api.equalsMatrix3;
export const getMatrix3Determinant = api.getMatrix3Determinant;
export const getMatrix3Element = api.getMatrix3Element;
export const inverseMatrix3 = api.inverseMatrix3;
export const isAffineMatrix3 = api.isAffineMatrix3;
export const multiplyMatrix3 = api.multiplyMatrix3;
export const rotateMatrix3 = api.rotateMatrix3;
export const scaleMatrix3 = api.scaleMatrix3;
export const setMatrix3 = api.setMatrix3;
export const setMatrix3Element = api.setMatrix3Element;
export const setMatrix3FromFloat32Array = api.setMatrix3FromFloat32Array;
export const setMatrix3FromMatrix = api.setMatrix3FromMatrix;
export const setMatrix3FromMatrix4 = api.setMatrix3FromMatrix4;
export const setMatrix3Identity = api.setMatrix3Identity;
export const setMatrix3NormalFromMatrix4 = api.setMatrix3NormalFromMatrix4;
export const translateMatrix3 = api.translateMatrix3;
export const transposeMatrix3 = api.transposeMatrix3;
export const writeMatrix3ToFloat32Array = api.writeMatrix3ToFloat32Array;
