// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.geometry.Rectangle;
function __syncDependencies() {}
__syncDependencies();

export const cloneRectangle = api.cloneRectangle;
export const computeRectangleIntersection = api.computeRectangleIntersection;
export const containsRectanglePoint = api.containsRectanglePoint;
export const containsRectanglePointXY = api.containsRectanglePointXY;
export const copyRectangle = api.copyRectangle;
export const createRectangle = api.createRectangle;
export const enclosesRectangle = api.enclosesRectangle;
export const equalsRectangle = api.equalsRectangle;
export const expandRectangleToPoint = api.expandRectangleToPoint;
export const getRectangleBottom = api.getRectangleBottom;
export const getRectangleBottomRight = api.getRectangleBottomRight;
export const getRectangleLeft = api.getRectangleLeft;
export const getRectangleMaxX = api.getRectangleMaxX;
export const getRectangleMaxY = api.getRectangleMaxY;
export const getRectangleMinX = api.getRectangleMinX;
export const getRectangleMinY = api.getRectangleMinY;
export const getRectangleNormalizedBottomRight = api.getRectangleNormalizedBottomRight;
export const getRectangleNormalizedTopLeft = api.getRectangleNormalizedTopLeft;
export const getRectangleRight = api.getRectangleRight;
export const getRectangleSize = api.getRectangleSize;
export const getRectangleTop = api.getRectangleTop;
export const getRectangleTopLeft = api.getRectangleTopLeft;
export const inflateRectangle = api.inflateRectangle;
export const intersectsRectangle = api.intersectsRectangle;
export const isEmptyRectangle = api.isEmptyRectangle;
export const isFlippedXRectangle = api.isFlippedXRectangle;
export const isFlippedYRectangle = api.isFlippedYRectangle;
export const mergeRectangle = api.mergeRectangle;
export const normalizeRectangle = api.normalizeRectangle;
export const offsetRectangle = api.offsetRectangle;
export const offsetRectangleByPoint = api.offsetRectangleByPoint;
export const setEmptyRectangle = api.setEmptyRectangle;
export const setRectangle = api.setRectangle;
export const setRectangleBottom = api.setRectangleBottom;
export const setRectangleBottomRight = api.setRectangleBottomRight;
export const setRectangleLeft = api.setRectangleLeft;
export const setRectangleRight = api.setRectangleRight;
export const setRectangleSize = api.setRectangleSize;
export const setRectangleTop = api.setRectangleTop;
export const setRectangleTopLeft = api.setRectangleTopLeft;
