// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.geometry.RectanglePool;
function __syncDependencies() {}
__syncDependencies();

export const acquireEmptyRectangle = api.acquireEmptyRectangle;
export const acquireRectangle = api.acquireRectangle;
export const clearRectanglePool = api.clearRectanglePool;
export const releaseRectangle = api.releaseRectangle;
