// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.math.Constants;
function __syncDependencies() {}
__syncDependencies();

export const DEG_TO_RAD = api.DEG_TO_RAD;
export const EPSILON = api.EPSILON;
export const HALF_PI = api.HALF_PI;
export const RAD_TO_DEG = api.RAD_TO_DEG;
export const TAU = api.TAU;
