// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Math;
function __syncDependencies() {}
__syncDependencies();

export const inverseLerp = api.inverseLerp;
export const lerp = api.lerp;
export const remap = api.remap;
export const smoothStep = api.smoothStep;
export const step = api.step;
