// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.math.RandomDistributions;
function __syncDependencies() {}
__syncDependencies();

export const pick = api.pick;
export const randomExponential = api.randomExponential;
export const randomGaussian = api.randomGaussian;
export const randomGaussianPair = api.randomGaussianPair;
export const randomInsideUnitDisc = api.randomInsideUnitDisc;
export const randomInsideUnitSphere = api.randomInsideUnitSphere;
export const randomOnUnitCircle = api.randomOnUnitCircle;
export const randomOnUnitSphere = api.randomOnUnitSphere;
export const randomPoisson = api.randomPoisson;
export const randomWeighted = api.randomWeighted;
export const shuffle = api.shuffle;
export const shuffleInPlace = api.shuffleInPlace;
