// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene.SceneNodeCulling;
function __syncDependencies() {}
__syncDependencies();

export const buildSceneFrustum = api.buildSceneFrustum;
export const cullSceneNodeByFrustum = api.cullSceneNodeByFrustum;
