// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Animation;
function __syncDependencies() {}
__syncDependencies();

export const advanceAnimationBlendTree = api.advanceAnimationBlendTree;
export const createAnimationBlendTree = api.createAnimationBlendTree;
export const createAnimationBlendTreeInput = api.createAnimationBlendTreeInput;
export const initializeAnimationBlendTree = api.initializeAnimationBlendTree;
export const initializeAnimationBlendTreeInput = api.initializeAnimationBlendTreeInput;
export const sampleAnimationBlendTree = api.sampleAnimationBlendTree;
export const sampleAnimationBlendTreeChannel = api.sampleAnimationBlendTreeChannel;
export const setAnimationBlendTreeInputWeight = api.setAnimationBlendTreeInputWeight;
