// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.skeleton2dFormats.SkeletonDetect;
function __syncDependencies() {}
__syncDependencies();

export const parseSkeleton2D = api.parseSkeleton2D;
export const registerSkeleton2DFormat = api.registerSkeleton2DFormat;
