// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.particles.ParticleEmitterState;
function __syncDependencies() {}
__syncDependencies();

export const createParticleEmitterState = api.createParticleEmitterState;
export const ensureParticleEmitterStateCapacity = api.ensureParticleEmitterStateCapacity;
export const PARTICLE_VELOCITY_STRIDE = api.PARTICLE_VELOCITY_STRIDE;
