// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/scene3d-formats/contract';
import * as __dependency1 from '@flighthq/net/contract';

const api = compiled.flighthq.scene3dResources.Md2Load;
function __syncDependencies() {
  compiled.flighthq.scene3dFormats.Md2Parse.parseMd2 = __dependency0.parseMd2;
  compiled.flighthq.net.Net.sendNetRequest = __dependency1.sendNetRequest;
}
__syncDependencies();

export const loadScene3DDocumentFromMd2Url = api.loadScene3DDocumentFromMd2Url;
