// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dResources.Md5Load;
function __syncDependencies() {}
__syncDependencies();

export const loadScene3DDocumentFromMd5MeshUrl = api.loadScene3DDocumentFromMd5MeshUrl;
