// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/image/contract';

const api = compiled.flight._Scene3DResources;
function __syncDependencies() {
  compiled.flight._Image.createImageResourceFailure = __dependency0.createImageResourceFailure;
  compiled.flight._Image.resolveImageResourceReference = __dependency0.resolveImageResourceReference;
}
__syncDependencies();

export const resolveOneScene3DResourceTexture = api.resolveOneScene3DResourceTexture;
export const resolveScene3DResources = api.resolveScene3DResources;
export const updateScene3DResourceStreaming = api.updateScene3DResourceStreaming;
