// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dResources.SheenPbrScene3DMaterialTextures;
function __syncDependencies() {}
__syncDependencies();

export const registerSheenPbrScene3DMaterialTextures = api.registerSheenPbrScene3DMaterialTextures;
