// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/scene3d-formats/contract';
import * as __dependency1 from '@flighthq/net/contract';

const api = compiled.flight._Scene3DResources;
function __syncDependencies() {
  compiled.flight._Scene3DFormats.parse3ds = __dependency0.parse3ds;
  compiled.flight._Net.sendNetRequest = __dependency1.sendNetRequest;
}
__syncDependencies();

export const loadScene3DDocumentFrom3dsUrl = api.loadScene3DDocumentFrom3dsUrl;
