// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.SensorsApi;
function __syncDependencies() {}
__syncDependencies();

export const attachSensors = api.attachSensors;
export const computeEulerFromQuaternion = api.computeEulerFromQuaternion;
export const computeGravityFromOrientation = api.computeGravityFromOrientation;
export const computeQuaternionFromOrientationReading = api.computeQuaternionFromOrientationReading;
export const computeRotationMatrixFromQuaternion = api.computeRotationMatrixFromQuaternion;
export const computeScreenRelativeOrientation = api.computeScreenRelativeOrientation;
export const computeWorldAccelerationFromDeviceAcceleration = api.computeWorldAccelerationFromDeviceAcceleration;
export const createAmbientLightReading = api.createAmbientLightReading;
export const createMotionReading = api.createMotionReading;
export const createOrientationReading = api.createOrientationReading;
export const createPressureReading = api.createPressureReading;
export const createProximityReading = api.createProximityReading;
export const createQuaternionReading = api.createQuaternionReading;
export const createRotationRateReading = api.createRotationRateReading;
export const createSensors = api.createSensors;
export const createWebSensorsBackend = api.createWebSensorsBackend;
export const detachSensors = api.detachSensors;
export const disposeSensors = api.disposeSensors;
export const getSensorsBackend = api.getSensorsBackend;
export const getSensorsPermissionState = api.getSensorsPermissionState;
export const hasAccelerometer = api.hasAccelerometer;
export const hasAmbientLightSensor = api.hasAmbientLightSensor;
export const hasBarometer = api.hasBarometer;
export const hasGravitySensor = api.hasGravitySensor;
export const hasGyroscope = api.hasGyroscope;
export const hasLinearAccelerationSensor = api.hasLinearAccelerationSensor;
export const hasMagnetometer = api.hasMagnetometer;
export const hasOrientationSensor = api.hasOrientationSensor;
export const hasProximitySensor = api.hasProximitySensor;
export const isSensorsSupported = api.isSensorsSupported;
export const requestSensorsPermission = api.requestSensorsPermission;
export const setSensorsBackend = api.setSensorsBackend;
