// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.RenderGl;
function __syncDependencies() {}
__syncDependencies();

export const getGlMaterialRenderer = api.getGlMaterialRenderer;
export const registerGlMaterialRenderer = api.registerGlMaterialRenderer;
export const resolveGlMaterialRenderer = api.resolveGlMaterialRenderer;
