// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.RenderGl;
function __syncDependencies() {}
__syncDependencies();

export const compileGlShader = api.compileGlShader;
export const createGlProgram = api.createGlProgram;
export const linkGlProgram = api.linkGlProgram;
