// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._RenderGl;
function __syncDependencies() {}
__syncDependencies();

export const compileDefaultGlProgram = api.compileDefaultGlProgram;
export const compileGlBitmapProgram = api.compileGlBitmapProgram;
export const createDefaultGlBitmapShader = api.createDefaultGlBitmapShader;
export const createGlBitmapShader = api.createGlBitmapShader;
export const ensureDefaultGlBitmapShader = api.ensureDefaultGlBitmapShader;
export const initializeDefaultGlBitmapShader = api.initializeDefaultGlBitmapShader;
export const initializeGlBitmapShader = api.initializeGlBitmapShader;
export const setGlAttributes = api.setGlAttributes;
export const setGlBaseUniforms = api.setGlBaseUniforms;
export const setGlMatrixFromTransform = api.setGlMatrixFromTransform;
export const setGlMatrixFromValues = api.setGlMatrixFromValues;
