// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.velocity.VelocityField;
function __syncDependencies() {}
__syncDependencies();

export const addVelocity = api.addVelocity;
export const beginVelocityFrame = api.beginVelocityFrame;
export const clampVelocity = api.clampVelocity;
export const contributeVelocity = api.contributeVelocity;
export const copyVelocity = api.copyVelocity;
export const createVelocityField = api.createVelocityField;
export const dampVelocity = api.dampVelocity;
export const ensureVelocitySample = api.ensureVelocitySample;
export const getVelocity = api.getVelocity;
export const hasVelocity = api.hasVelocity;
export const isVelocityZero = api.isVelocityZero;
export const lengthOfVelocity = api.lengthOfVelocity;
export const lerpVelocity = api.lerpVelocity;
export const normalizeVelocity = api.normalizeVelocity;
export const scaleVelocity = api.scaleVelocity;
export const subtractVelocity = api.subtractVelocity;
export const suppressVelocity = api.suppressVelocity;
export const zeroVelocity = api.zeroVelocity;
