// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Animation;
export const advanceAnimationPlayer = api.advanceAnimationPlayer;
export const cloneAnimationClip = api.cloneAnimationClip;
export const cloneAnimationPlayer = api.cloneAnimationPlayer;
export const cloneAnimationTrack = api.cloneAnimationTrack;
export const createAnimationChannel = api.createAnimationChannel;
export const createAnimationClip = api.createAnimationClip;
export const createAnimationPlayer = api.createAnimationPlayer;
export const createAnimationTrack = api.createAnimationTrack;
export const enableAnimationPlayerSignals = api.enableAnimationPlayerSignals;
export const getAnimationClipDuration = api.getAnimationClipDuration;
export const getAnimationPlayerNormalizedTime = api.getAnimationPlayerNormalizedTime;
export const playAnimationPlayer = api.playAnimationPlayer;
export const sampleAnimationClip = api.sampleAnimationClip;
export const sampleAnimationTrack = api.sampleAnimationTrack;
export const seekAnimationPlayer = api.seekAnimationPlayer;
export const stopAnimationPlayer = api.stopAnimationPlayer;
export const trimAnimationTrack = api.trimAnimationTrack;
export const validateAnimationTrack = api.validateAnimationTrack;
