// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Audio;
export const canPlayAudioType = api.canPlayAudioType;
export const cloneAudioResource = api.cloneAudioResource;
export const createAudioResource = api.createAudioResource;
export const createAudioResourceFromSamples = api.createAudioResourceFromSamples;
export const detectAudioMimeType = api.detectAudioMimeType;
export const disposeAudioResource = api.disposeAudioResource;
export const getAudioResourceByteSize = api.getAudioResourceByteSize;
export const getAudioResourceChannelCount = api.getAudioResourceChannelCount;
export const getAudioResourceChannelData = api.getAudioResourceChannelData;
export const getAudioResourceDuration = api.getAudioResourceDuration;
export const getAudioResourceSampleRate = api.getAudioResourceSampleRate;
export const hasAudioResourceBuffer = api.hasAudioResourceBuffer;
export const inferAudioMimeType = api.inferAudioMimeType;
export const isAudioResourceEmpty = api.isAudioResourceEmpty;
export const loadAudioResourceFromBase64 = api.loadAudioResourceFromBase64;
export const loadAudioResourceFromBlob = api.loadAudioResourceFromBlob;
export const loadAudioResourceFromBytes = api.loadAudioResourceFromBytes;
export const loadAudioResourceFromUrl = api.loadAudioResourceFromUrl;
export const loadAudioResourceFromUrls = api.loadAudioResourceFromUrls;
export const selectAudioResourceUrl = api.selectAudioResourceUrl;
