// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const createBitmapFont = compiled.flight.BitmapFont.createBitmapFont;
export const createBitmapFontFromGlyphAtlas = compiled.flight.BitmapFont.createBitmapFontFromGlyphAtlas;
export const createGlyphSourceFromBitmapFont = compiled.flight.BitmapFont.createGlyphSourceFromBitmapFont;
export const disableBitmapFontGuards = compiled.flight.BitmapFont.disableBitmapFontGuards;
export const enableBitmapFontGuards = compiled.flight.BitmapFont.enableBitmapFontGuards;
export const explainBitmapFontGlyph = compiled.flight.BitmapFont.explainBitmapFontGlyph;
export const getBitmapFontGlyph = compiled.flight.BitmapFont.getBitmapFontGlyph;
export const getBitmapFontKerning = compiled.flight.BitmapFont.getBitmapFontKerning;
export const getBitmapFontMetrics = compiled.flight.BitmapFont.getBitmapFontMetrics;
export const getBitmapFontPage = compiled.flight.BitmapFont.getBitmapFontPage;
export const getBitmapFontPages = compiled.flight.BitmapFont.getBitmapFontPages;
export const hasBitmapFontGlyph = compiled.flight.BitmapFont.hasBitmapFontGlyph;
export const summarizeBitmapFont = compiled.flight.BitmapFont.summarizeBitmapFont;
