// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const createBitmapFont = compiled.flighthq.bitmapfont.Bitmapfont.createBitmapFont;
export const createGlyphSourceFromBitmapFont = compiled.flighthq.bitmapfont.Bitmapfont.createGlyphSourceFromBitmapFont;
export const getBitmapFontGlyph = compiled.flighthq.bitmapfont.Bitmapfont.getBitmapFontGlyph;
export const getBitmapFontKerning = compiled.flighthq.bitmapfont.Bitmapfont.getBitmapFontKerning;
export const getBitmapFontMetrics = compiled.flighthq.bitmapfont.Bitmapfont.getBitmapFontMetrics;
export const getBitmapFontPage = compiled.flighthq.bitmapfont.Bitmapfont.getBitmapFontPage;
export const getBitmapFontPages = compiled.flighthq.bitmapfont.Bitmapfont.getBitmapFontPages;
