// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const attachClipboardWatch = compiled.flight.Clipboard.attachClipboardWatch;
export const clearClipboard = compiled.flight.Clipboard.clearClipboard;
export const createClipboardWatch = compiled.flight.Clipboard.createClipboardWatch;
export const detachClipboardWatch = compiled.flight.Clipboard.detachClipboardWatch;
export const disposeClipboardWatch = compiled.flight.Clipboard.disposeClipboardWatch;
export const getClipboardFormats = compiled.flight.Clipboard.getClipboardFormats;
export const hasClipboardBookmark = compiled.flight.Clipboard.hasClipboardBookmark;
export const hasClipboardFormat = compiled.flight.Clipboard.hasClipboardFormat;
export const hasClipboardHtml = compiled.flight.Clipboard.hasClipboardHtml;
export const hasClipboardImage = compiled.flight.Clipboard.hasClipboardImage;
export const hasClipboardRTF = compiled.flight.Clipboard.hasClipboardRTF;
export const hasClipboardText = compiled.flight.Clipboard.hasClipboardText;
export const readClipboard = compiled.flight.Clipboard.readClipboard;
export const readClipboardBookmark = compiled.flight.Clipboard.readClipboardBookmark;
export const readClipboardFormat = compiled.flight.Clipboard.readClipboardFormat;
export const readClipboardHtml = compiled.flight.Clipboard.readClipboardHtml;
export const readClipboardImage = compiled.flight.Clipboard.readClipboardImage;
export const readClipboardRTF = compiled.flight.Clipboard.readClipboardRTF;
export const readClipboardText = compiled.flight.Clipboard.readClipboardText;
export const writeClipboard = compiled.flight.Clipboard.writeClipboard;
export const writeClipboardBookmark = compiled.flight.Clipboard.writeClipboardBookmark;
export const writeClipboardFormat = compiled.flight.Clipboard.writeClipboardFormat;
export const writeClipboardHtml = compiled.flight.Clipboard.writeClipboardHtml;
export const writeClipboardImage = compiled.flight.Clipboard.writeClipboardImage;
export const writeClipboardRTF = compiled.flight.Clipboard.writeClipboardRTF;
export const writeClipboardText = compiled.flight.Clipboard.writeClipboardText;
