// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const addClockChild = compiled.flight.Clock.addClockChild;
export const advanceClock = compiled.flight.Clock.advanceClock;
export const createChildClock = compiled.flight.Clock.createChildClock;
export const createClock = compiled.flight.Clock.createClock;
export const disposeClock = compiled.flight.Clock.disposeClock;
export const enableClockSignals = compiled.flight.Clock.enableClockSignals;
export const getClockEffectiveScale = compiled.flight.Clock.getClockEffectiveScale;
export const getClockParent = compiled.flight.Clock.getClockParent;
export const isClockEffectivelyPaused = compiled.flight.Clock.isClockEffectivelyPaused;
export const pauseClock = compiled.flight.Clock.pauseClock;
export const removeClockChild = compiled.flight.Clock.removeClockChild;
export const resetClock = compiled.flight.Clock.resetClock;
export const resumeClock = compiled.flight.Clock.resumeClock;
export const setClockScale = compiled.flight.Clock.setClockScale;
