// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const createDeviceCapabilities = compiled.flight.Device.createDeviceCapabilities;
export const createDeviceDisplayMetrics = compiled.flight.Device.createDeviceDisplayMetrics;
export const createDeviceInfo = compiled.flight.Device.createDeviceInfo;
export const createSafeAreaInsets = compiled.flight.Device.createSafeAreaInsets;
export const getDeviceCapabilities = compiled.flight.Device.getDeviceCapabilities;
export const getDeviceDisplayMetrics = compiled.flight.Device.getDeviceDisplayMetrics;
export const getDeviceId = compiled.flight.Device.getDeviceId;
export const getDeviceInfo = compiled.flight.Device.getDeviceInfo;
export const getSafeAreaInsets = compiled.flight.Device.getSafeAreaInsets;
export const refreshDeviceInfo = compiled.flight.Device.refreshDeviceInfo;
