// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const explainDialogBackend = compiled.flight.Dialog.explainDialogBackend;
export const getWebDirectorySystemHandle = compiled.flight.Dialog.getWebDirectorySystemHandle;
export const getWebFileSystemHandle = compiled.flight.Dialog.getWebFileSystemHandle;
export const showConfirmDialog = compiled.flight.Dialog.showConfirmDialog;
export const showErrorBox = compiled.flight.Dialog.showErrorBox;
export const showErrorDialog = compiled.flight.Dialog.showErrorDialog;
export const showInfoDialog = compiled.flight.Dialog.showInfoDialog;
export const showMessageDialog = compiled.flight.Dialog.showMessageDialog;
export const showOpenDirectoryDialog = compiled.flight.Dialog.showOpenDirectoryDialog;
export const showOpenFileDialog = compiled.flight.Dialog.showOpenFileDialog;
export const showPromptDialog = compiled.flight.Dialog.showPromptDialog;
export const showSaveFileDialog = compiled.flight.Dialog.showSaveFileDialog;
export const showWarningDialog = compiled.flight.Dialog.showWarningDialog;
