// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const clearFlowStack = compiled.flighthq.flow.Flow.clearFlowStack;
export const createFlowStack = compiled.flighthq.flow.Flow.createFlowStack;
export const getActiveFlowState = compiled.flighthq.flow.Flow.getActiveFlowState;
export const getFlowStackDepth = compiled.flighthq.flow.Flow.getFlowStackDepth;
export const getFlowStackVisibleStates = compiled.flighthq.flow.Flow.getFlowStackVisibleStates;
export const popFlowState = compiled.flighthq.flow.Flow.popFlowState;
export const pushFlowState = compiled.flighthq.flow.Flow.pushFlowState;
export const replaceFlowState = compiled.flighthq.flow.Flow.replaceFlowState;
export const updateFlowStack = compiled.flighthq.flow.Flow.updateFlowStack;
