// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Flow;
export const clearFlowStack = api.clearFlowStack;
export const createFlowStack = api.createFlowStack;
export const getActiveFlowState = api.getActiveFlowState;
export const getFlowStackDepth = api.getFlowStackDepth;
export const getFlowStackVisibleStates = api.getFlowStackVisibleStates;
export const popFlowState = api.popFlowState;
export const pushFlowState = api.pushFlowState;
export const replaceFlowState = api.replaceFlowState;
export const updateFlowStack = api.updateFlowStack;
