// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const clearGeolocationWatch = compiled.flighthq.geolocation.Geolocation.clearGeolocationWatch;
export const createGeoPosition = compiled.flighthq.geolocation.Geolocation.createGeoPosition;
export const getCurrentGeoPosition = compiled.flighthq.geolocation.Geolocation.getCurrentGeoPosition;
export const getCurrentGeoPositionResult = compiled.flighthq.geolocation.Geolocation.getCurrentGeoPositionResult;
export const getGeolocationPermission = compiled.flighthq.geolocation.Geolocation.getGeolocationPermission;
export const isGeolocationAvailable = compiled.flighthq.geolocation.Geolocation.isGeolocationAvailable;
export const onGeolocationPermissionChange = compiled.flighthq.geolocation.Geolocation.onGeolocationPermissionChange;
export const requestGeolocationPermission = compiled.flighthq.geolocation.Geolocation.requestGeolocationPermission;
export const watchGeolocationPosition = compiled.flighthq.geolocation.Geolocation.watchGeolocationPosition;
