// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const collectImportDiagnostics = compiled.flight.ImportDiagnostics.collectImportDiagnostics;
export const formatImportDiagnostic = compiled.flight.ImportDiagnostics.formatImportDiagnostic;
export const reportImportDiagnostic = compiled.flight.ImportDiagnostics.reportImportDiagnostic;
