// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const attachMidiAccessStateSubscription = compiled.flight.Midi.attachMidiAccessStateSubscription;
export const attachMidiInputMessageSubscription = compiled.flight.Midi.attachMidiInputMessageSubscription;
export const attachMidiPortStateSubscription = compiled.flight.Midi.attachMidiPortStateSubscription;
export const closeMidiPort = compiled.flight.Midi.closeMidiPort;
export const createMidiAccessStateSubscription = compiled.flight.Midi.createMidiAccessStateSubscription;
export const createMidiInputMessageSubscription = compiled.flight.Midi.createMidiInputMessageSubscription;
export const createMidiPortStateSubscription = compiled.flight.Midi.createMidiPortStateSubscription;
export const detachMidiAccessStateSubscription = compiled.flight.Midi.detachMidiAccessStateSubscription;
export const detachMidiInputMessageSubscription = compiled.flight.Midi.detachMidiInputMessageSubscription;
export const detachMidiPortStateSubscription = compiled.flight.Midi.detachMidiPortStateSubscription;
export const disposeMidiAccess = compiled.flight.Midi.disposeMidiAccess;
export const disposeMidiAccessStateSubscription = compiled.flight.Midi.disposeMidiAccessStateSubscription;
export const disposeMidiInputMessageSubscription = compiled.flight.Midi.disposeMidiInputMessageSubscription;
export const disposeMidiPort = compiled.flight.Midi.disposeMidiPort;
export const disposeMidiPortStateSubscription = compiled.flight.Midi.disposeMidiPortStateSubscription;
export const getMidiAccessInputPorts = compiled.flight.Midi.getMidiAccessInputPorts;
export const getMidiAccessOutputPorts = compiled.flight.Midi.getMidiAccessOutputPorts;
export const getMidiPermission = compiled.flight.Midi.getMidiPermission;
export const getMidiPortConnection = compiled.flight.Midi.getMidiPortConnection;
export const getMidiPortState = compiled.flight.Midi.getMidiPortState;
export const openMidiPort = compiled.flight.Midi.openMidiPort;
export const requestMidiAccess = compiled.flight.Midi.requestMidiAccess;
export const sendMidiMessage = compiled.flight.Midi.sendMidiMessage;
