// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const appendQuadBatchInstance = compiled.flight.QuadBatch.appendQuadBatchInstance;
export const clearQuadBatch = compiled.flight.QuadBatch.clearQuadBatch;
export const cloneQuadBatch = compiled.flight.QuadBatch.cloneQuadBatch;
export const compactQuadBatch = compiled.flight.QuadBatch.compactQuadBatch;
export const computeQuadBatchLocalBoundsRectangle = compiled.flight.QuadBatch.computeQuadBatchLocalBoundsRectangle;
export const createQuadBatch = compiled.flight.QuadBatch.createQuadBatch;
export const enableQuadBatchSignals = compiled.flight.QuadBatch.enableQuadBatchSignals;
export const getQuadBatchCapacity = compiled.flight.QuadBatch.getQuadBatchCapacity;
export const getQuadBatchInstanceId = compiled.flight.QuadBatch.getQuadBatchInstanceId;
export const getQuadBatchInstanceTransform = compiled.flight.QuadBatch.getQuadBatchInstanceTransform;
export const getQuadBatchSignals = compiled.flight.QuadBatch.getQuadBatchSignals;
export const getQuadBatchTransformStride = compiled.flight.QuadBatch.getQuadBatchTransformStride;
export const hitTestQuadBatchPoint = compiled.flight.QuadBatch.hitTestQuadBatchPoint;
export const hitTestQuadBatchPointExact = compiled.flight.QuadBatch.hitTestQuadBatchPointExact;
export const hitTestQuadBatchPointExactXY = compiled.flight.QuadBatch.hitTestQuadBatchPointExactXY;
export const hitTestQuadBatchPointXY = compiled.flight.QuadBatch.hitTestQuadBatchPointXY;
export const iterateQuadBatchInstances = compiled.flight.QuadBatch.iterateQuadBatchInstances;
export const removeQuadBatchInstance = compiled.flight.QuadBatch.removeQuadBatchInstance;
export const reserveQuadBatch = compiled.flight.QuadBatch.reserveQuadBatch;
export const resizeQuadBatch = compiled.flight.QuadBatch.resizeQuadBatch;
export const setQuadBatchInstance = compiled.flight.QuadBatch.setQuadBatchInstance;
export const setQuadBatchInstanceMatrix = compiled.flight.QuadBatch.setQuadBatchInstanceMatrix;
export const setQuadBatchInstanceRange = compiled.flight.QuadBatch.setQuadBatchInstanceRange;
export const setQuadBatchInstanceTint = compiled.flight.QuadBatch.setQuadBatchInstanceTint;
export const setQuadBatchLocalBoundsRectangle = compiled.flight.QuadBatch.setQuadBatchLocalBoundsRectangle;
export const setQuadBatchTransformType = compiled.flight.QuadBatch.setQuadBatchTransformType;
