// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const defaultShapeCommandSchemas = compiled.flight.ShapeFormats.defaultShapeCommandSchemas;
export const formatShapeJson = compiled.flight.ShapeFormats.formatShapeJson;
export const parseShapeJson = compiled.flight.ShapeFormats.parseShapeJson;
