// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Share;
export const attachShareSignals = api.attachShareSignals;
export const canShareContent = api.canShareContent;
export const createWebShareBackend = api.createWebShareBackend;
export const detachShareSignals = api.detachShareSignals;
export const disposeShareSignals = api.disposeShareSignals;
export const enableShareSignals = api.enableShareSignals;
export const getShareBackend = api.getShareBackend;
export const hasShareContentFields = api.hasShareContentFields;
export const isShareAvailable = api.isShareAvailable;
export const setShareBackend = api.setShareBackend;
export const shareContent = api.shareContent;
export const shareContentWithResult = api.shareContentWithResult;
export const shareText = api.shareText;
export const shareUrl = api.shareUrl;
