// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const attachGlobalShortcut = compiled.flight.Shortcut.attachGlobalShortcut;
export const createGlobalShortcut = compiled.flight.Shortcut.createGlobalShortcut;
export const destroyShortcutTrigger = compiled.flight.Shortcut.destroyShortcutTrigger;
export const detachGlobalShortcut = compiled.flight.Shortcut.detachGlobalShortcut;
export const disposeGlobalShortcut = compiled.flight.Shortcut.disposeGlobalShortcut;
export const equalsAccelerator = compiled.flight.Shortcut.equalsAccelerator;
export const findAcceleratorConflict = compiled.flight.Shortcut.findAcceleratorConflict;
export const formatAcceleratorForDisplay = compiled.flight.Shortcut.formatAcceleratorForDisplay;
export const getAcceleratorKey = compiled.flight.Shortcut.getAcceleratorKey;
export const getAcceleratorKeyLabel = compiled.flight.Shortcut.getAcceleratorKeyLabel;
export const getAcceleratorModifierLabel = compiled.flight.Shortcut.getAcceleratorModifierLabel;
export const getAcceleratorModifiers = compiled.flight.Shortcut.getAcceleratorModifiers;
export const isAcceleratorValid = compiled.flight.Shortcut.isAcceleratorValid;
export const makeParsedAccelerator = compiled.flight.Shortcut.makeParsedAccelerator;
export const normalizeAccelerator = compiled.flight.Shortcut.normalizeAccelerator;
export const parseAccelerator = compiled.flight.Shortcut.parseAccelerator;
export const parseAcceleratorDetailed = compiled.flight.Shortcut.parseAcceleratorDetailed;
export const queryGlobalShortcutConflict = compiled.flight.Shortcut.queryGlobalShortcutConflict;
export const queryGlobalShortcutRegistration = compiled.flight.Shortcut.queryGlobalShortcutRegistration;
export const resolveCommandOrControlModifier = compiled.flight.Shortcut.resolveCommandOrControlModifier;
