// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flight.SnapshotApi;
export const captureSnapshot = api.captureSnapshot;
export const equalsSnapshot = api.equalsSnapshot;
export const interpolateSnapshots = api.interpolateSnapshots;
export const restoreSnapshot = api.restoreSnapshot;
