// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const detectTextureAtlasFormat = compiled.flight.TextureAtlasFormats.detectTextureAtlasFormat;
export const getTextureAtlasFormat = compiled.flight.TextureAtlasFormats.getTextureAtlasFormat;
export const getTextureAtlasFormatKinds = compiled.flight.TextureAtlasFormats.getTextureAtlasFormatKinds;
export const parseTextureAtlas = compiled.flight.TextureAtlasFormats.parseTextureAtlas;
export const parseTextureAtlasAsepriteDocument = compiled.flight.TextureAtlasFormats.parseTextureAtlasAsepriteDocument;
export const parseTextureAtlasAsepriteJson = compiled.flight.TextureAtlasFormats.parseTextureAtlasAsepriteJson;
export const parseTextureAtlasLibgdxAtlas = compiled.flight.TextureAtlasFormats.parseTextureAtlasLibgdxAtlas;
export const parseTextureAtlasPackerDocument = compiled.flight.TextureAtlasFormats.parseTextureAtlasPackerDocument;
export const parseTextureAtlasPackerJson = compiled.flight.TextureAtlasFormats.parseTextureAtlasPackerJson;
export const parseTextureAtlasStarlingXml = compiled.flight.TextureAtlasFormats.parseTextureAtlasStarlingXml;
export const registerTextureAtlasFormat = compiled.flight.TextureAtlasFormats.registerTextureAtlasFormat;
export const unregisterTextureAtlasFormat = compiled.flight.TextureAtlasFormats.unregisterTextureAtlasFormat;
