// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flight.TextureAtlasFormats;
export const detectTextureAtlasFormat = api.detectTextureAtlasFormat;
export const parseTextureAtlasAsepriteDocument = api.parseTextureAtlasAsepriteDocument;
export const parseTextureAtlasAsepriteJson = api.parseTextureAtlasAsepriteJson;
export const parseTextureAtlasLibgdxAtlas = api.parseTextureAtlasLibgdxAtlas;
export const parseTextureAtlasPackerDocument = api.parseTextureAtlasPackerDocument;
export const parseTextureAtlasPackerJson = api.parseTextureAtlasPackerJson;
export const parseTextureAtlasStarlingXml = api.parseTextureAtlasStarlingXml;
