// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.TilesetApi;
export const buildTilesetRegions = api.buildTilesetRegions;
export const createTileset = api.createTileset;
export const createTilesetFromAtlas = api.createTilesetFromAtlas;
export const createTilesetFromImageResource = api.createTilesetFromImageResource;
export const disposeTileset = api.disposeTileset;
export const loadTilesetFromBase64 = api.loadTilesetFromBase64;
export const loadTilesetFromBlob = api.loadTilesetFromBlob;
export const loadTilesetFromBytes = api.loadTilesetFromBytes;
export const loadTilesetFromUrl = api.loadTilesetFromUrl;
