// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const detectEndianness = compiled.flighthq.useragent.Useragent.detectEndianness;
export const parseUserAgentArch = compiled.flighthq.useragent.Useragent.parseUserAgentArch;
export const parseUserAgentEngine = compiled.flighthq.useragent.Useragent.parseUserAgentEngine;
export const parseUserAgentEngineVersion = compiled.flighthq.useragent.Useragent.parseUserAgentEngineVersion;
export const parseUserAgentFormFactor = compiled.flighthq.useragent.Useragent.parseUserAgentFormFactor;
export const parseUserAgentKind = compiled.flighthq.useragent.Useragent.parseUserAgentKind;
export const parseUserAgentName = compiled.flighthq.useragent.Useragent.parseUserAgentName;
export const parseUserAgentOsName = compiled.flighthq.useragent.Useragent.parseUserAgentOsName;
export const parseUserAgentOsVersion = compiled.flighthq.useragent.Useragent.parseUserAgentOsVersion;
export const parseUserAgentPointerWidth = compiled.flighthq.useragent.Useragent.parseUserAgentPointerWidth;
export const parseUserAgentRuntime = compiled.flighthq.useragent.Useragent.parseUserAgentRuntime;
export const parseUserAgentVersion = compiled.flighthq.useragent.Useragent.parseUserAgentVersion;
