// Generated by flight-hx. Do not edit.
import compiled from '../../build/haxe-js/flight.cjs';

export const getXmlElementAttribute = compiled.flighthq.xml.Xml.getXmlElementAttribute;
export const getXmlElementAttributeNumber = compiled.flighthq.xml.Xml.getXmlElementAttributeNumber;
export const getXmlElementChildByName = compiled.flighthq.xml.Xml.getXmlElementChildByName;
export const getXmlElementChildrenByName = compiled.flighthq.xml.Xml.getXmlElementChildrenByName;
export const parseXmlAttributes = compiled.flighthq.xml.Xml.parseXmlAttributes;
export const parseXmlDocument = compiled.flighthq.xml.Xml.parseXmlDocument;
