// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Menu;
function __syncDependencies() {}
__syncDependencies();

export const attachMenuHighlight = api.attachMenuHighlight;
export const attachMenuSelect = api.attachMenuSelect;
export const cloneMenuTemplate = api.cloneMenuTemplate;
export const createMenuHighlight = api.createMenuHighlight;
export const createMenuItemTemplate = api.createMenuItemTemplate;
export const createMenuSelect = api.createMenuSelect;
export const destroyMenuApplication = api.destroyMenuApplication;
export const detachMenuHighlight = api.detachMenuHighlight;
export const detachMenuSelect = api.detachMenuSelect;
export const disposeMenuHighlight = api.disposeMenuHighlight;
export const disposeMenuSelect = api.disposeMenuSelect;
export const enableMenuSignals = api.enableMenuSignals;
export const getMenuSignals = api.getMenuSignals;
export const setApplicationMenu = api.setApplicationMenu;
export const showContextMenu = api.showContextMenu;
export const validateMenuItemTemplate = api.validateMenuItemTemplate;
