// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.DisplayObjectApi;
function __syncDependencies() {}
__syncDependencies();

export const computeBitmapLocalBoundsRectangle = api.computeBitmapLocalBoundsRectangle;
export const createBitmap = api.createBitmap;
export const createBitmapData = api.createBitmapData;
export const createBitmapRuntime = api.createBitmapRuntime;
export const getBitmapRuntime = api.getBitmapRuntime;
export const setBitmapImage = api.setBitmapImage;
