// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._ApplicationGl;
function __syncDependencies() {}
__syncDependencies();

export const createGlApplicationRenderView = api.createGlApplicationRenderView;
export const destroyGlApplicationRenderView = api.destroyGlApplicationRenderView;
