// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.Easing;
function __syncDependencies() {}
__syncDependencies();

export const easeInBounce = api.easeInBounce;
export const easeInOutBounce = api.easeInOutBounce;
export const easeOutBounce = api.easeOutBounce;
