// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.easing.EaseElastic;
function __syncDependencies() {}
__syncDependencies();

export const easeInElastic = api.easeInElastic;
export const easeInOutElastic = api.easeInOutElastic;
export const easeOutElastic = api.easeOutElastic;
