// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.color.HslColor;
function __syncDependencies() {}
__syncDependencies();

export const allocateHslColor = api.allocateHslColor;
export const hslToRgb = api.hslToRgb;
export const rgbToHsl = api.rgbToHsl;
