// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.clock.CreateClock;
function __syncDependencies() {}
__syncDependencies();

export const createChildClock = api.createChildClock;
export const createClock = api.createClock;
