// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.clock.DisposeClock;
function __syncDependencies() {}
__syncDependencies();

export const disposeClock = api.disposeClock;
