// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.TextureFormats;
function __syncDependencies() {}
__syncDependencies();

export const createByteReader = api.createByteReader;
export const hasByteReaderBytes = api.hasByteReaderBytes;
export const readByteReaderU16 = api.readByteReaderU16;
export const readByteReaderU24BigEndian = api.readByteReaderU24BigEndian;
export const readByteReaderU32 = api.readByteReaderU32;
export const readByteReaderU32BigEndian = api.readByteReaderU32BigEndian;
export const readByteReaderU64 = api.readByteReaderU64;
export const readByteReaderU8 = api.readByteReaderU8;
export const skipByteReader = api.skipByteReader;
