// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Lighting;
function __syncDependencies() {}
__syncDependencies();

export const cloneAreaLight = api.cloneAreaLight;
export const createAreaLight = api.createAreaLight;
export const initializeAreaLight = api.initializeAreaLight;
export const setAreaLightOrientation = api.setAreaLightOrientation;
