// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.lighting.SceneForwardLights;
function __syncDependencies() {}
__syncDependencies();

export const selectScene3DForwardLights = api.selectScene3DForwardLights;
