// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.node.HasClip;
function __syncDependencies() {}
__syncDependencies();

export const initClipTrait = api.initClipTrait;
