// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effects.GaussianMath;
function __syncDependencies() {}
__syncDependencies();

export const computeGaussianRadiusFromSigma = api.computeGaussianRadiusFromSigma;
export const computeGaussianSigmaFromRadius = api.computeGaussianSigmaFromRadius;
export const computeSeparableBlurPassCount = api.computeSeparableBlurPassCount;
export const createGaussianKernelWeights = api.createGaussianKernelWeights;
