// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effects.InnerGlowEffect;
function __syncDependencies() {}
__syncDependencies();

export const createInnerGlowEffect = api.createInnerGlowEffect;
