// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effects.KuwaharaMath;
function __syncDependencies() {}
__syncDependencies();

export const computeKuwaharaGaussianWeights = api.computeKuwaharaGaussianWeights;
export const computeKuwaharaSectorOffsets = api.computeKuwaharaSectorOffsets;
export const computeKuwaharaSectorPixelCount = api.computeKuwaharaSectorPixelCount;
export const computeKuwaharaSectorSize = api.computeKuwaharaSectorSize;
