// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Effects;
function __syncDependencies() {}
__syncDependencies();

export const createLensDistortionEffect = api.createLensDistortionEffect;
export const initializeLensDistortionEffect = api.initializeLensDistortionEffect;
