// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.Effects;
function __syncDependencies() {}
__syncDependencies();

export const computeCrtMaskParams = api.computeCrtMaskParams;
export const computeHalftoneCellParams = api.computeHalftoneCellParams;
export const computeScanlineParams = api.computeScanlineParams;
export const createBayerMatrix = api.createBayerMatrix;
