// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Scene2DCanvas;
function __syncDependencies() {}
__syncDependencies();

export const defaultCanvasParticleEmitter2DRenderer = api.defaultCanvasParticleEmitter2DRenderer;
export const drawCanvasParticleEmitter2D = api.drawCanvasParticleEmitter2D;
