// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.TextShaper;
function __syncDependencies() {}
__syncDependencies();

export const clearShapedRun = api.clearShapedRun;
export const createShapedRun = api.createShapedRun;
export const getCodePointForGlyph = api.getCodePointForGlyph;
export const getFontMetrics = api.getFontMetrics;
export const getFontMetricsInto = api.getFontMetricsInto;
export const getFontUnitScale = api.getFontUnitScale;
export const getGlyphExtents = api.getGlyphExtents;
export const getGlyphExtentsBatch = api.getGlyphExtentsBatch;
export const getGlyphExtentsInto = api.getGlyphExtentsInto;
export const getGlyphIndexForCodePoint = api.getGlyphIndexForCodePoint;
export const getGlyphName = api.getGlyphName;
export const shapeTextRun = api.shapeTextRun;
export const shapeTextRunInto = api.shapeTextRunInto;
