// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.surface.SurfaceHistogram;
function __syncDependencies() {}
__syncDependencies();

export const equalizeSurfaceHistogram = api.equalizeSurfaceHistogram;
export const getSurfaceHistogram = api.getSurfaceHistogram;
