// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.surface.SurfaceRotate;
function __syncDependencies() {}
__syncDependencies();

export const rotateSurface = api.rotateSurface;
export const rotateSurface180 = api.rotateSurface180;
export const rotateSurfaceClockwise = api.rotateSurfaceClockwise;
export const rotateSurfaceCounterClockwise = api.rotateSurfaceCounterClockwise;
