// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.cameraControls.OrbitCameraController;
function __syncDependencies() {}
__syncDependencies();

export const cloneOrbitCameraController = api.cloneOrbitCameraController;
export const copyOrbitCameraController = api.copyOrbitCameraController;
export const createOrbitCameraController = api.createOrbitCameraController;
export const dollyCameraController = api.dollyCameraController;
export const orbitCameraController = api.orbitCameraController;
export const panCameraController = api.panCameraController;
export const panOrbitCameraControllerInViewPlane = api.panOrbitCameraControllerInViewPlane;
export const resetOrbitCameraController = api.resetOrbitCameraController;
export const snapOrbitCameraController = api.snapOrbitCameraController;
export const updateOrbitCameraController = api.updateOrbitCameraController;
