// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Command;
function __syncDependencies() {}
__syncDependencies();

export const canRedoCommand = api.canRedoCommand;
export const canUndoCommand = api.canUndoCommand;
export const clearCommandHistory = api.clearCommandHistory;
export const createCommandHistory = api.createCommandHistory;
export const executeCommand = api.executeCommand;
export const getCommandHistoryEntries = api.getCommandHistoryEntries;
export const getCommandHistoryIndex = api.getCommandHistoryIndex;
export const getCommandHistoryRedoLabel = api.getCommandHistoryRedoLabel;
export const getCommandHistoryUndoLabel = api.getCommandHistoryUndoLabel;
export const notifyCommandHistoryChanged = api.notifyCommandHistoryChanged;
export const redoCommand = api.redoCommand;
export const undoCommand = api.undoCommand;
