// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Command;
function __syncDependencies() {}
__syncDependencies();

export const abortCommandTransaction = api.abortCommandTransaction;
export const beginCommandTransaction = api.beginCommandTransaction;
export const endCommandTransaction = api.endCommandTransaction;
export const isCommandTransactionOpen = api.isCommandTransactionOpen;
