// Generated by flight-hx. Do not edit.
package flight;

import Math as HxMath;
import flight.internal.FlightRuntime;
import flight.Geometry.intersectsRectangle;
import flight.Types.BinPackOptions;
import flight.Types.PackResult;
import flight.Types.PackableRectangle;
import flight.Types.PackedRectangle;
import flight.Types.RectangleId;

typedef FreeRectangle__packRectangles = { var x:Float; var y:Float; var width:Float; var height:Float; };

typedef Placement__packRectangles = { var x:Float; var y:Float; var footprintWidth:Float; var footprintHeight:Float; var rotated:Bool; };

@:expose("flight.Binpack")
class Binpack {
  public static function ceilToPowerOfTwo__packRectangles(value:Float):Float {
    var result:Dynamic = cast FlightRuntime.UNDEFINED;
    if (FlightRuntime.truthy(FlightRuntime.compare(value, 1.0, '<='))) { return cast 1.0; }
    result = 1.0;
    while (FlightRuntime.truthy(FlightRuntime.compare(result, value, '<'))) { (result = cast ((result * 2.0) : Dynamic)); }
    return cast result;
    return cast null;
  }

  public static function compareRectangleId__packRectangles(a:RectangleId, b:RectangleId):Float {
    var aNumber:Dynamic = cast FlightRuntime.UNDEFINED;
    var bNumber:Dynamic = cast FlightRuntime.UNDEFINED;
    aNumber = FlightRuntime.strictEquals(FlightRuntime.typeofValue(a), 'number');
    bNumber = FlightRuntime.strictEquals(FlightRuntime.typeofValue(b), 'number');
    if (FlightRuntime.truthy(FlightRuntime.andValue(aNumber, function():Dynamic return cast bNumber))) { return cast (a - b); }
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(aNumber, bNumber))) { return cast FlightRuntime.select(aNumber, function():Dynamic return cast -1.0, function():Dynamic return cast 1.0); }
    return cast FlightRuntime.select(FlightRuntime.compare(Std.string(a), Std.string(b), '<'), function():Dynamic return cast -1.0, function():Dynamic return cast FlightRuntime.select(FlightRuntime.compare(Std.string(a), Std.string(b), '>'), function():Dynamic return cast 1.0, function():Dynamic return cast 0.0));
    return cast null;
  }

  public static final DEFAULT_MAX_EXTENT__packRectangles:Dynamic = 16384.0;

  public static function finalizeExtent__packRectangles(value:Float, powerOfTwo:Bool):Float {
    return cast FlightRuntime.select(FlightRuntime.andValue(powerOfTwo, function():Dynamic return cast FlightRuntime.compare(value, 0.0, '>')), function():Dynamic return cast FlightRuntime.callValue(Binpack.ceilToPowerOfTwo__packRectangles, cast ([value] : Array<Dynamic>)), function():Dynamic return cast value);
    return cast null;
  }

  public static function finalizeResult__packRectangles(packed:{ var placements:Array<PackedRectangle>; var unpacked:Array<RectangleId>; }, border:Float, powerOfTwo:Bool, square:Bool):PackResult {
    var contentRight:Dynamic = cast FlightRuntime.UNDEFINED;
    var contentBottom:Dynamic = cast FlightRuntime.UNDEFINED;
    var width:Dynamic = cast FlightRuntime.UNDEFINED;
    var height:Dynamic = cast FlightRuntime.UNDEFINED;
    contentRight = 0.0;
    contentBottom = 0.0;
    for (placement in FlightRuntime.iterable(FlightRuntime.field(packed, 'placements'))) {
      (contentRight = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([contentRight, (FlightRuntime.field(placement, 'x') + FlightRuntime.field(placement, 'width'))] : Array<Dynamic>)) : Dynamic));
      (contentBottom = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([contentBottom, (FlightRuntime.field(placement, 'y') + FlightRuntime.field(placement, 'height'))] : Array<Dynamic>)) : Dynamic));
    }
    width = FlightRuntime.select(FlightRuntime.compare(FlightRuntime.field(FlightRuntime.field(packed, 'placements'), 'length'), 0.0, '>'), function():Dynamic return cast (contentRight + border), function():Dynamic return cast 0.0);
    height = FlightRuntime.select(FlightRuntime.compare(FlightRuntime.field(FlightRuntime.field(packed, 'placements'), 'length'), 0.0, '>'), function():Dynamic return cast (contentBottom + border), function():Dynamic return cast 0.0);
    if (FlightRuntime.truthy(square)) {
  (width = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([width, height] : Array<Dynamic>)) : Dynamic));
  (height = cast (width : Dynamic));
}
    (width = cast (FlightRuntime.callValue(Binpack.finalizeExtent__packRectangles, cast ([width, powerOfTwo] : Array<Dynamic>)) : Dynamic));
    (height = cast (FlightRuntime.callValue(Binpack.finalizeExtent__packRectangles, cast ([height, powerOfTwo] : Array<Dynamic>)) : Dynamic));
    if (FlightRuntime.truthy(square)) {
  (width = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([width, height] : Array<Dynamic>)) : Dynamic));
  (height = cast (width : Dynamic));
}
    return cast { placements: FlightRuntime.callProperty(FlightRuntime.field(packed, 'placements'), 'map', cast ([function(placement:Dynamic) return FlightRuntime.mergeObjects([placement])] : Array<Dynamic>)), width: width, height: height, unpacked: FlightRuntime.concatArrays([FlightRuntime.toArray(FlightRuntime.field(packed, 'unpacked'))]) };
    return cast null;
  }

  public static function findBestPlacement__packRectangles(free:Array<FreeRectangle__packRectangles>, pieceWidth:Float, pieceHeight:Float, allowRotation:Bool):Null<Placement__packRectangles> {
    var best:Null<Placement__packRectangles> = cast FlightRuntime.UNDEFINED;
    var bestShort:Dynamic = cast FlightRuntime.UNDEFINED;
    var bestLong:Dynamic = cast FlightRuntime.UNDEFINED;
    best = null;
    bestShort = FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Number'] : Array<Dynamic>)), 'POSITIVE_INFINITY');
    bestLong = FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Number'] : Array<Dynamic>)), 'POSITIVE_INFINITY');
    for (node in FlightRuntime.iterable(free)) {
      {
        var rotated:Dynamic = 0.0;
        while (FlightRuntime.truthy(FlightRuntime.compare(rotated, FlightRuntime.select(allowRotation, function():Dynamic return cast 1.0, function():Dynamic return cast 0.0), '<='))) {
          var width:Dynamic = FlightRuntime.select(rotated, function():Dynamic return cast pieceHeight, function():Dynamic return cast pieceWidth);
          var height:Dynamic = FlightRuntime.select(rotated, function():Dynamic return cast pieceWidth, function():Dynamic return cast pieceHeight);
          if (FlightRuntime.truthy(FlightRuntime.orValue(FlightRuntime.compare(width, FlightRuntime.field(node, 'width'), '>'), function():Dynamic return cast FlightRuntime.compare(height, FlightRuntime.field(node, 'height'), '>')))) { rotated++; continue; }
          var leftoverHorizontal:Dynamic = (FlightRuntime.field(node, 'width') - width);
          var leftoverVertical:Dynamic = (FlightRuntime.field(node, 'height') - height);
          var shortSide:Dynamic = FlightRuntime.callProperty(HxMath, 'min', cast ([leftoverHorizontal, leftoverVertical] : Array<Dynamic>));
          var longSide:Dynamic = FlightRuntime.callProperty(HxMath, 'max', cast ([leftoverHorizontal, leftoverVertical] : Array<Dynamic>));
          if (FlightRuntime.truthy(FlightRuntime.orValue(FlightRuntime.orValue(FlightRuntime.strictEquals(best, null), function():Dynamic return cast FlightRuntime.compare(shortSide, bestShort, '<')), function():Dynamic return cast FlightRuntime.andValue(FlightRuntime.strictEquals(shortSide, bestShort), function():Dynamic return cast FlightRuntime.compare(longSide, bestLong, '<'))))) {
  (best = cast ({ x: FlightRuntime.field(node, 'x'), y: FlightRuntime.field(node, 'y'), footprintWidth: width, footprintHeight: height, rotated: FlightRuntime.strictEquals(rotated, 1.0) } : Dynamic));
  (bestShort = cast (shortSide : Dynamic));
  (bestLong = cast (longSide : Dynamic));
}
          rotated++;
        }
      }
    }
    return cast best;
    return cast null;
  }

  public static function isFreeRectangleContained__packRectangles(inner:FreeRectangle__packRectangles, outer:FreeRectangle__packRectangles):Bool {
    return cast FlightRuntime.andValue(FlightRuntime.andValue(FlightRuntime.andValue(FlightRuntime.compare(FlightRuntime.field(inner, 'x'), FlightRuntime.field(outer, 'x'), '>='), function():Dynamic return cast FlightRuntime.compare(FlightRuntime.field(inner, 'y'), FlightRuntime.field(outer, 'y'), '>=')), function():Dynamic return cast FlightRuntime.compare((FlightRuntime.field(inner, 'x') + FlightRuntime.field(inner, 'width')), (FlightRuntime.field(outer, 'x') + FlightRuntime.field(outer, 'width')), '<=')), function():Dynamic return cast FlightRuntime.compare((FlightRuntime.field(inner, 'y') + FlightRuntime.field(inner, 'height')), (FlightRuntime.field(outer, 'y') + FlightRuntime.field(outer, 'height')), '<='));
    return cast null;
  }

  public static function packIntoBin__packRectangles(sorted:Array<PackableRectangle>, binWidth:Float, binHeight:Float, padding:Float, border:Float, allowRotation:Bool):{ var placements:Array<PackedRectangle>; var unpacked:Array<RectangleId>; } {
    var usableWidth:Dynamic = cast FlightRuntime.UNDEFINED;
    var usableHeight:Dynamic = cast FlightRuntime.UNDEFINED;
    var placements:Array<PackedRectangle> = cast FlightRuntime.UNDEFINED;
    var unpacked:Array<RectangleId> = cast FlightRuntime.UNDEFINED;
    var free:Array<FreeRectangle__packRectangles> = cast FlightRuntime.UNDEFINED;
    usableWidth = ((binWidth - (2.0 * border)) + padding);
    usableHeight = ((binHeight - (2.0 * border)) + padding);
    placements = cast ([] : Array<Dynamic>);
    unpacked = cast ([] : Array<Dynamic>);
    if (FlightRuntime.truthy(FlightRuntime.orValue(FlightRuntime.compare(usableWidth, 0.0, '<='), function():Dynamic return cast FlightRuntime.compare(usableHeight, 0.0, '<=')))) {
  for (rect in FlightRuntime.iterable(sorted)) {
    FlightRuntime.callProperty(unpacked, 'push', cast ([FlightRuntime.field(rect, 'id')] : Array<Dynamic>));
  }
  return cast { placements: placements, unpacked: unpacked };
}
    free = cast ([{ x: 0.0, y: 0.0, width: usableWidth, height: usableHeight }] : Array<Dynamic>);
    for (rect in FlightRuntime.iterable(sorted)) {
      var pieceWidth:Dynamic = (FlightRuntime.field(rect, 'width') + padding);
      var pieceHeight:Dynamic = (FlightRuntime.field(rect, 'height') + padding);
      var placement:Dynamic = FlightRuntime.callValue(Binpack.findBestPlacement__packRectangles, cast ([free, pieceWidth, pieceHeight, allowRotation] : Array<Dynamic>));
      if (FlightRuntime.truthy(FlightRuntime.strictEquals(placement, null))) {
  FlightRuntime.callProperty(unpacked, 'push', cast ([FlightRuntime.field(rect, 'id')] : Array<Dynamic>));
  continue;
}
      FlightRuntime.callProperty(placements, 'push', cast ([{ id: FlightRuntime.field(rect, 'id'), x: (FlightRuntime.field(placement, 'x') + border), y: (FlightRuntime.field(placement, 'y') + border), width: FlightRuntime.select(FlightRuntime.field(placement, 'rotated'), function():Dynamic return cast FlightRuntime.field(rect, 'height'), function():Dynamic return cast FlightRuntime.field(rect, 'width')), height: FlightRuntime.select(FlightRuntime.field(placement, 'rotated'), function():Dynamic return cast FlightRuntime.field(rect, 'width'), function():Dynamic return cast FlightRuntime.field(rect, 'height')), rotated: FlightRuntime.field(placement, 'rotated') }] : Array<Dynamic>));
      FlightRuntime.callValue(Binpack.splitFreeRectangles__packRectangles, cast ([free, placement] : Array<Dynamic>));
      FlightRuntime.callValue(Binpack.pruneFreeRectangles__packRectangles, cast ([free] : Array<Dynamic>));
    }
    return cast { placements: placements, unpacked: unpacked };
    return cast null;
  }

  public static function packRectangles(rects:Array<PackableRectangle>, ?options:BinPackOptions):PackResult {
    var padding:Dynamic = cast FlightRuntime.UNDEFINED;
    var border:Dynamic = cast FlightRuntime.UNDEFINED;
    var allowRotation:Dynamic = cast FlightRuntime.UNDEFINED;
    var growable:Dynamic = cast FlightRuntime.UNDEFINED;
    var powerOfTwo:Dynamic = cast FlightRuntime.UNDEFINED;
    var square:Dynamic = cast FlightRuntime.UNDEFINED;
    var maxWidth:Dynamic = cast FlightRuntime.UNDEFINED;
    var maxHeight:Dynamic = cast FlightRuntime.UNDEFINED;
    var sorted:Dynamic = cast FlightRuntime.UNDEFINED;
    var needWidth:Dynamic = cast FlightRuntime.UNDEFINED;
    var needHeight:Dynamic = cast FlightRuntime.UNDEFINED;
    var totalArea:Dynamic = cast FlightRuntime.UNDEFINED;
    var seed:Dynamic = cast FlightRuntime.UNDEFINED;
    var binWidth:Dynamic = cast FlightRuntime.UNDEFINED;
    var binHeight:Dynamic = cast FlightRuntime.UNDEFINED;
    var attempt:Dynamic = cast FlightRuntime.UNDEFINED;
    padding = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'padding'), function():Dynamic return cast 0.0);
    border = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'border'), function():Dynamic return cast 0.0);
    allowRotation = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'allowRotation'), function():Dynamic return cast false);
    growable = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'growable'), function():Dynamic return cast true);
    powerOfTwo = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'powerOfTwo'), function():Dynamic return cast false);
    square = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'square'), function():Dynamic return cast false);
    maxWidth = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'maxWidth'), function():Dynamic return cast Binpack.DEFAULT_MAX_EXTENT__packRectangles);
    maxHeight = FlightRuntime.coalesce(FlightRuntime.optionalField(options, 'maxHeight'), function():Dynamic return cast Binpack.DEFAULT_MAX_EXTENT__packRectangles);
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(rects, 'length'), 0.0))) {
  return cast { placements: cast ([] : Array<Dynamic>), width: FlightRuntime.callValue(Binpack.finalizeExtent__packRectangles, cast ([0.0, powerOfTwo] : Array<Dynamic>)), height: FlightRuntime.callValue(Binpack.finalizeExtent__packRectangles, cast ([0.0, powerOfTwo] : Array<Dynamic>)), unpacked: cast ([] : Array<Dynamic>) };
}
    sorted = FlightRuntime.callValue(Binpack.sortRectanglesForPacking__packRectangles, cast ([rects] : Array<Dynamic>));
    needWidth = (2.0 * border);
    needHeight = (2.0 * border);
    totalArea = 0.0;
    for (rect in FlightRuntime.iterable(sorted)) {
      var shortSide:Dynamic = FlightRuntime.callProperty(HxMath, 'min', cast ([FlightRuntime.field(rect, 'width'), FlightRuntime.field(rect, 'height')] : Array<Dynamic>));
      var requiredWidth:Dynamic = (FlightRuntime.select(allowRotation, function():Dynamic return cast shortSide, function():Dynamic return cast FlightRuntime.field(rect, 'width')) + (2.0 * border));
      var requiredHeight:Dynamic = (FlightRuntime.select(allowRotation, function():Dynamic return cast shortSide, function():Dynamic return cast FlightRuntime.field(rect, 'height')) + (2.0 * border));
      (needWidth = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([needWidth, requiredWidth] : Array<Dynamic>)) : Dynamic));
      (needHeight = cast (FlightRuntime.callProperty(HxMath, 'max', cast ([needHeight, requiredHeight] : Array<Dynamic>)) : Dynamic));
      (totalArea = cast ((totalArea + ((FlightRuntime.field(rect, 'width') + padding) * (FlightRuntime.field(rect, 'height') + padding))) : Dynamic));
    }
    seed = (FlightRuntime.callProperty(HxMath, 'ceil', cast ([FlightRuntime.callProperty(HxMath, 'sqrt', cast ([totalArea] : Array<Dynamic>))] : Array<Dynamic>)) + (2.0 * border));
    binWidth = FlightRuntime.select(growable, function():Dynamic return cast FlightRuntime.callProperty(HxMath, 'min', cast ([FlightRuntime.callProperty(HxMath, 'max', cast ([seed, needWidth] : Array<Dynamic>)), maxWidth] : Array<Dynamic>)), function():Dynamic return cast maxWidth);
    binHeight = FlightRuntime.select(growable, function():Dynamic return cast FlightRuntime.callProperty(HxMath, 'min', cast ([FlightRuntime.callProperty(HxMath, 'max', cast ([seed, needHeight] : Array<Dynamic>)), maxHeight] : Array<Dynamic>)), function():Dynamic return cast maxHeight);
    attempt = FlightRuntime.callValue(Binpack.packIntoBin__packRectangles, cast ([sorted, binWidth, binHeight, padding, border, allowRotation] : Array<Dynamic>));
    while (FlightRuntime.truthy(FlightRuntime.andValue(FlightRuntime.andValue(FlightRuntime.compare(FlightRuntime.field(FlightRuntime.field(attempt, 'unpacked'), 'length'), 0.0, '>'), function():Dynamic return cast growable), function():Dynamic return cast FlightRuntime.orValue(FlightRuntime.compare(binWidth, maxWidth, '<'), function():Dynamic return cast FlightRuntime.compare(binHeight, maxHeight, '<'))))) {
  if (FlightRuntime.truthy(FlightRuntime.andValue(FlightRuntime.compare(binWidth, binHeight, '<='), function():Dynamic return cast FlightRuntime.compare(binWidth, maxWidth, '<')))) {
  (binWidth = cast (FlightRuntime.callProperty(HxMath, 'min', cast ([(binWidth * 2.0), maxWidth] : Array<Dynamic>)) : Dynamic));
} else { if (FlightRuntime.truthy(FlightRuntime.compare(binHeight, maxHeight, '<'))) {
  (binHeight = cast (FlightRuntime.callProperty(HxMath, 'min', cast ([(binHeight * 2.0), maxHeight] : Array<Dynamic>)) : Dynamic));
} else {
  (binWidth = cast (FlightRuntime.callProperty(HxMath, 'min', cast ([(binWidth * 2.0), maxWidth] : Array<Dynamic>)) : Dynamic));
} }
  (attempt = cast (FlightRuntime.callValue(Binpack.packIntoBin__packRectangles, cast ([sorted, binWidth, binHeight, padding, border, allowRotation] : Array<Dynamic>)) : Dynamic));
}
    return cast FlightRuntime.callValue(Binpack.finalizeResult__packRectangles, cast ([attempt, border, powerOfTwo, square] : Array<Dynamic>));
    return cast null;
  }

  public static function pruneFreeRectangles__packRectangles(free:Array<FreeRectangle__packRectangles>):Void {
    {
      var i:Dynamic = 0.0;
      while (FlightRuntime.truthy(FlightRuntime.compare(i, FlightRuntime.field(free, 'length'), '<'))) {
        {
          var j:Dynamic = (i + 1.0);
          while (FlightRuntime.truthy(FlightRuntime.compare(j, FlightRuntime.field(free, 'length'), '<'))) {
            if (FlightRuntime.truthy(FlightRuntime.callValue(Binpack.isFreeRectangleContained__packRectangles, cast ([FlightRuntime.getIndex(free, i), FlightRuntime.getIndex(free, j)] : Array<Dynamic>)))) {
  FlightRuntime.splice(free, Std.int(i), Std.int(1.0), []);
  i--;
  break;
}
            if (FlightRuntime.truthy(FlightRuntime.callValue(Binpack.isFreeRectangleContained__packRectangles, cast ([FlightRuntime.getIndex(free, j), FlightRuntime.getIndex(free, i)] : Array<Dynamic>)))) {
  FlightRuntime.splice(free, Std.int(j), Std.int(1.0), []);
  j--;
}
            j++;
          }
        }
        i++;
      }
    }
  }

  public static function sortRectanglesForPacking__packRectangles(rects:Array<PackableRectangle>):Array<PackableRectangle> {
    return cast FlightRuntime.callProperty(FlightRuntime.concatArrays([FlightRuntime.toArray(rects)]), 'sort', cast ([function(a:Dynamic, b:Dynamic) {
  var areaA:Dynamic = cast FlightRuntime.UNDEFINED;
  var areaB:Dynamic = cast FlightRuntime.UNDEFINED;
  areaA = (FlightRuntime.field(a, 'width') * FlightRuntime.field(a, 'height'));
  areaB = (FlightRuntime.field(b, 'width') * FlightRuntime.field(b, 'height'));
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(areaA, areaB))) { return cast (areaB - areaA); }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(a, 'height'), FlightRuntime.field(b, 'height')))) { return cast (FlightRuntime.field(b, 'height') - FlightRuntime.field(a, 'height')); }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(a, 'width'), FlightRuntime.field(b, 'width')))) { return cast (FlightRuntime.field(b, 'width') - FlightRuntime.field(a, 'width')); }
  return cast FlightRuntime.callValue(Binpack.compareRectangleId__packRectangles, cast ([FlightRuntime.field(a, 'id'), FlightRuntime.field(b, 'id')] : Array<Dynamic>));
}] : Array<Dynamic>));
    return cast null;
  }

  public static function splitFreeRectangles__packRectangles(free:Array<FreeRectangle__packRectangles>, placement:Placement__packRectangles):Void {
    var usedX:Dynamic = cast FlightRuntime.UNDEFINED;
    var usedY:Dynamic = cast FlightRuntime.UNDEFINED;
    var usedRight:Dynamic = cast FlightRuntime.UNDEFINED;
    var usedBottom:Dynamic = cast FlightRuntime.UNDEFINED;
    var used:FreeRectangle__packRectangles = cast FlightRuntime.UNDEFINED;
    usedX = FlightRuntime.field(placement, 'x');
    usedY = FlightRuntime.field(placement, 'y');
    usedRight = (FlightRuntime.field(placement, 'x') + FlightRuntime.field(placement, 'footprintWidth'));
    usedBottom = (FlightRuntime.field(placement, 'y') + FlightRuntime.field(placement, 'footprintHeight'));
    used = { x: usedX, y: usedY, width: FlightRuntime.field(placement, 'footprintWidth'), height: FlightRuntime.field(placement, 'footprintHeight') };
    {
      var i:Dynamic = (FlightRuntime.field(free, 'length') - 1.0);
      while (FlightRuntime.truthy(FlightRuntime.compare(i, 0.0, '>='))) {
        var node:Dynamic = FlightRuntime.getIndex(free, i);
        if (FlightRuntime.truthy(!FlightRuntime.truthy(FlightRuntime.callValue(intersectsRectangle, cast ([node, used] : Array<Dynamic>))))) { i--; continue; }
        var nodeRight:Dynamic = (FlightRuntime.field(node, 'x') + FlightRuntime.field(node, 'width'));
        var nodeBottom:Dynamic = (FlightRuntime.field(node, 'y') + FlightRuntime.field(node, 'height'));
        FlightRuntime.splice(free, Std.int(i), Std.int(1.0), []);
        if (FlightRuntime.truthy(FlightRuntime.compare(usedX, FlightRuntime.field(node, 'x'), '>'))) { FlightRuntime.callProperty(free, 'push', cast ([{ x: FlightRuntime.field(node, 'x'), y: FlightRuntime.field(node, 'y'), width: (usedX - FlightRuntime.field(node, 'x')), height: FlightRuntime.field(node, 'height') }] : Array<Dynamic>)); }
        if (FlightRuntime.truthy(FlightRuntime.compare(usedRight, nodeRight, '<'))) { FlightRuntime.callProperty(free, 'push', cast ([{ x: usedRight, y: FlightRuntime.field(node, 'y'), width: (nodeRight - usedRight), height: FlightRuntime.field(node, 'height') }] : Array<Dynamic>)); }
        if (FlightRuntime.truthy(FlightRuntime.compare(usedY, FlightRuntime.field(node, 'y'), '>'))) { FlightRuntime.callProperty(free, 'push', cast ([{ x: FlightRuntime.field(node, 'x'), y: FlightRuntime.field(node, 'y'), width: FlightRuntime.field(node, 'width'), height: (usedY - FlightRuntime.field(node, 'y')) }] : Array<Dynamic>)); }
        if (FlightRuntime.truthy(FlightRuntime.compare(usedBottom, nodeBottom, '<'))) {
  FlightRuntime.callProperty(free, 'push', cast ([{ x: FlightRuntime.field(node, 'x'), y: usedBottom, width: FlightRuntime.field(node, 'width'), height: (nodeBottom - usedBottom) }] : Array<Dynamic>));
}
        i--;
      }
    }
  }
}
