// Generated by flight-hx. Do not edit.
package flight;

import Math as HxMath;
import flight.internal.FlightRuntime;
import flight.AppApi.setAppBackend;
import flight.ApplicationApi.setWindowBackend;
import flight.Clipboard.setClipboardBackend;
import flight.Dialog.setDialogBackend;
import flight.Menu.setMenuBackend;
import flight.Notification.setNotificationBackend;
import flight.Platform.setPlatformBackend;
import flight.Shell.setShellBackend;
import flight.Shortcut.setShortcutBackend;
import flight.Signals.emitSignal;
import flight.Tray.setTrayBackend;
import flight.Types.AppBackend;
import flight.Types.AppLoginItem;
import flight.Types.ApplicationWindow;
import flight.Types.ClipboardBackend;
import flight.Types.DialogBackend;
import flight.Types.FileDialogFilter;
import flight.Types.FileDialogHandle;
import flight.Types.MenuBackend;
import flight.Types.MenuItemTemplate;
import flight.Types.MessageDialogKind;
import flight.Types.NotificationBackend;
import flight.Types.NotificationCapabilities;
import flight.Types.NotificationPermission;
import flight.Types.PlatformBackend;
import flight.Types.PlatformName;
import flight.Types.ShellBackend;
import flight.Types.ShortcutBackend;
import flight.Types.TrayBackend;
import flight.Types.TrayEventData;
import flight.Types.TrayEventType;
import flight.Types.WindowBackend;

typedef TauriApi = { var app:TauriAppModule; var clipboard:TauriClipboardManager; var dialog:TauriDialogPlugin; var globalShortcut:TauriGlobalShortcutPlugin; var menu:TauriMenuModule; var notification:TauriNotificationPlugin; var opener:TauriOpenerPlugin; var os:TauriOsModule; var process:TauriProcessPlugin; var tray:TauriTrayModule; var window:TauriWindowModule; };

typedef TauriAppModule = { var getName:Dynamic; var getVersion:Dynamic; var hide:Dynamic; var show:Dynamic; };

typedef TauriClipboardManager = { var clear:Dynamic; var readText:Dynamic; var writeText:Dynamic; };

typedef TauriCloseRequestedEvent = { var preventDefault:Dynamic; };

typedef TauriDialogFilter = { var extensions:Array<String>; var name:String; };

typedef TauriDialogMessageOptions = { @:optional var cancelLabel:String; @:optional var kind:String; @:optional var okLabel:String; @:optional var title:String; };

typedef TauriDialogOpenOptions = { @:optional var defaultPath:String; @:optional var directory:Bool; @:optional var filters:Array<TauriDialogFilter>; @:optional var multiple:Bool; @:optional var title:String; };

typedef TauriDialogPlugin = { var ask:Dynamic; var confirm:Dynamic; var message:Dynamic; var open:Dynamic; var save:Dynamic; };

typedef TauriDialogSaveOptions = { @:optional var defaultPath:String; @:optional var filters:Array<TauriDialogFilter>; @:optional var title:String; };

typedef TauriGlobalShortcutPlugin = { var isRegistered:Dynamic; var register:Dynamic; var unregister:Dynamic; var unregisterAll:Dynamic; };

typedef TauriLogicalPositionConstructor = { @:optional var __construct:Dynamic; };

typedef TauriLogicalSizeConstructor = { @:optional var __construct:Dynamic; };

typedef TauriLogicalSizeLike = { var height:Float; var width:Float; };

typedef TauriMenu = { var popup:Dynamic; var setAsAppMenu:Dynamic; };

typedef TauriMenuFactory = { var new_:Dynamic; };

typedef TauriMenuItemFactory = { var new_:Dynamic; };

typedef TauriMenuItemHandle = { var id:String; };

typedef TauriMenuItemOptions = { @:optional var accelerator:String; @:optional var action:Dynamic; @:optional var enabled:Bool; @:optional var id:String; @:optional var text:String; };

typedef TauriMenuModule = { var Menu:TauriMenuFactory; var MenuItem:TauriMenuItemFactory; var PredefinedMenuItem:TauriPredefinedMenuItemFactory; var Submenu:TauriSubmenuFactory; };

typedef TauriMenuOptions = { @:optional var items:Array<TauriMenuItemHandle>; };

typedef TauriNotificationOptions = { @:optional var body:String; @:optional var icon:String; var title:String; };

typedef TauriNotificationPermission = String;

typedef TauriNotificationPlugin = { var isPermissionGranted:Dynamic; var requestPermission:Dynamic; var sendNotification:Dynamic; };

typedef TauriOpenerPlugin = { var openPath:Dynamic; var openUrl:Dynamic; var revealItemInDir:Dynamic; };

typedef TauriOsModule = { var arch:Dynamic; var locale:Dynamic; var platform:Dynamic; var version:Dynamic; };

typedef TauriPhysicalPositionLike = { var x:Float; var y:Float; };

typedef TauriPredefinedMenuItemFactory = { var new_:Dynamic; };

typedef TauriPredefinedMenuItemOptions = { var item:String; };

typedef TauriProcessPlugin = { var exit:Dynamic; var relaunch:Dynamic; };

typedef TauriShortcutEvent = { var shortcut:String; var state:String; };

typedef TauriSubmenuFactory = { var new_:Dynamic; };

typedef TauriSubmenuOptions = { @:optional var enabled:Bool; @:optional var items:Array<TauriMenuItemHandle>; @:optional var text:String; };

typedef TauriTrayIcon = { var close:Dynamic; var setIcon:Dynamic; var setMenu:Dynamic; var setTitle:Dynamic; var setTooltip:Dynamic; };

typedef TauriTrayIconEvent = { @:optional var button:String; var type:String; };

typedef TauriTrayIconFactory = { var new_:Dynamic; };

typedef TauriTrayIconOptions = { @:optional var action:Dynamic; @:optional var icon:String; @:optional var menu:TauriMenu; @:optional var title:String; @:optional var tooltip:String; };

typedef TauriTrayModule = { var TrayIcon:TauriTrayIconFactory; };

typedef TauriUnlisten = Dynamic;

typedef TauriWindow = { var center:Dynamic; var close:Dynamic; var hide:Dynamic; var maximize:Dynamic; var minimize:Dynamic; var onCloseRequested:Dynamic; var onFocusChanged:Dynamic; var onMoved:Dynamic; var onResized:Dynamic; var requestUserAttention:Dynamic; var setAlwaysOnTop:Dynamic; var setContentProtected:Dynamic; var setFocus:Dynamic; var setFullscreen:Dynamic; var setIcon:Dynamic; var setMaxSize:Dynamic; var setMinSize:Dynamic; var setPosition:Dynamic; var setResizable:Dynamic; var setShadow:Dynamic; var setSize:Dynamic; var setSkipTaskbar:Dynamic; var setTitle:Dynamic; var show:Dynamic; var unmaximize:Dynamic; };

typedef TauriWindowModule = { var getCurrentWindow:Dynamic; var LogicalPosition:TauriLogicalPositionConstructor; var LogicalSize:TauriLogicalSizeConstructor; };

typedef TrayRecord__tauriTray = { var icon:Null<TauriTrayIcon>; var title:String; var tooltip:String; };

#if js
@:build(jsasync.JSAsync.build())
#end
@:expose("flight.HostTauri")
class HostTauri {
  @:keep public static function basename__tauriDialog(path:String):String {
    var normalized:Dynamic = cast FlightRuntime.UNDEFINED;
    var index:Dynamic = cast FlightRuntime.UNDEFINED;
    normalized = FlightRuntime.replace(path, FlightRuntime.regexp('[/\\\\]+$$', ''), '', false);
    index = FlightRuntime.callProperty(HxMath, 'max', cast ([FlightRuntime.callProperty(normalized, 'lastIndexOf', cast (['/'] : Array<Dynamic>)), FlightRuntime.callProperty(normalized, 'lastIndexOf', cast (['\\'] : Array<Dynamic>))] : Array<Dynamic>));
    return cast FlightRuntime.select(FlightRuntime.compare(index, 0.0, '>='), function():Dynamic return cast FlightRuntime.slice(normalized, (index + 1.0), null), function():Dynamic return cast normalized);
    return cast null;
  }

  #if js
  @:jsasync
  #end
  @:keep public static function buildItem__tauriMenu(menuModule:Dynamic, item:MenuItemTemplate, onSelect:Dynamic):flight.internal.FlightPromise<TauriMenuItemHandle> {
    var id:Dynamic = cast FlightRuntime.UNDEFINED;
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'separator'))) {
  return cast FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'PredefinedMenuItem'), 'new', cast ([{ item: 'Separator' }] : Array<Dynamic>));
}
    if (FlightRuntime.truthy(FlightRuntime.field(item, 'submenu'))) {
  var children:Dynamic = flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildItems__tauriMenu, cast ([menuModule, FlightRuntime.field(item, 'submenu'), onSelect] : Array<Dynamic>)));
  return cast FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'Submenu'), 'new', cast ([{ text: FlightRuntime.field(item, 'label'), enabled: FlightRuntime.field(item, 'enabled'), items: children }] : Array<Dynamic>));
}
    id = FlightRuntime.field(item, 'id');
    return cast FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'MenuItem'), 'new', cast ([{ id: id, text: FlightRuntime.field(item, 'label'), enabled: FlightRuntime.field(item, 'enabled'), accelerator: FlightRuntime.field(item, 'accelerator'), action: FlightRuntime.select(!FlightRuntime.strictEquals(id, FlightRuntime.UNDEFINED), function():Dynamic return cast function() return FlightRuntime.callValue(onSelect, cast ([id] : Array<Dynamic>)), function():Dynamic return cast FlightRuntime.UNDEFINED) }] : Array<Dynamic>));
    return cast null;
  }

  #if js
  @:jsasync
  #end
  @:keep public static function buildItems__tauriMenu(menuModule:Dynamic, items:Array<MenuItemTemplate>, onSelect:Dynamic):flight.internal.FlightPromise<Array<TauriMenuItemHandle>> {
    var built:Array<TauriMenuItemHandle> = cast FlightRuntime.UNDEFINED;
    built = cast ([] : Array<Dynamic>);
    for (item in FlightRuntime.iterable(items)) {
      FlightRuntime.callProperty(built, 'push', cast ([flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildItem__tauriMenu, cast ([menuModule, item, onSelect] : Array<Dynamic>)))] : Array<Dynamic>));
    }
    return cast built;
    return cast null;
  }

  #if js
  @:jsasync
  #end
  @:keep public static function buildTrayItems__tauriTray(menuModule:Dynamic, items:Array<MenuItemTemplate>):flight.internal.FlightPromise<Array<TauriMenuItemHandle>> {
    var built:Array<TauriMenuItemHandle> = cast FlightRuntime.UNDEFINED;
    built = cast ([] : Array<Dynamic>);
    for (item in FlightRuntime.iterable(items)) {
      if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'separator'))) {
  FlightRuntime.callProperty(built, 'push', cast ([flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'PredefinedMenuItem'), 'new', cast ([{ item: 'Separator' }] : Array<Dynamic>)))] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(FlightRuntime.field(item, 'submenu'))) {
  FlightRuntime.callProperty(built, 'push', cast ([flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'Submenu'), 'new', cast ([{ text: FlightRuntime.field(item, 'label'), enabled: FlightRuntime.field(item, 'enabled'), items: flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildTrayItems__tauriTray, cast ([menuModule, FlightRuntime.field(item, 'submenu')] : Array<Dynamic>))) }] : Array<Dynamic>)))] : Array<Dynamic>));
} else {
  FlightRuntime.callProperty(built, 'push', cast ([flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'MenuItem'), 'new', cast ([{ id: FlightRuntime.field(item, 'id'), text: FlightRuntime.field(item, 'label'), enabled: FlightRuntime.field(item, 'enabled') }] : Array<Dynamic>)))] : Array<Dynamic>));
} }
    }
    return cast built;
    return cast null;
  }

  @:keep public static function createTauriAppBackend(tauri:TauriApi):AppBackend {
    var app:Dynamic = cast FlightRuntime.UNDEFINED;
    var os:Dynamic = cast FlightRuntime.UNDEFINED;
    var process:Dynamic = cast FlightRuntime.UNDEFINED;
    var cachedName:Dynamic = cast FlightRuntime.UNDEFINED;
    var cachedVersion:Dynamic = cast FlightRuntime.UNDEFINED;
    app = FlightRuntime.field(tauri, 'app');
    os = FlightRuntime.field(tauri, 'os');
    process = FlightRuntime.field(tauri, 'process');
    cachedName = '';
    cachedVersion = '';
    FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime.callProperty(app, 'getName', cast ([] : Array<Dynamic>)), 'then', cast ([function(name:Dynamic) {
  (cachedName = cast (name : Dynamic));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
    FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime.callProperty(app, 'getVersion', cast ([] : Array<Dynamic>)), 'then', cast ([function(version:Dynamic) {
  (cachedVersion = cast (version : Dynamic));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
    return cast { addRecentDocument: function() {

}, bounceDock: function() {
  return cast -1.0;
}, cancelAttention: function() {

}, cancelDockBounce: function() {

}, clearRecentDocuments: function() {

}, focus: function() {

}, getAppDirectoryPath: function() {
  return cast '';
}, getAppPath: function() {
  return cast '';
}, getCommandLine: function() {
  return cast cast ([] : Array<Dynamic>);
}, getExecutablePath: function() {
  return cast '';
}, getLocale: function() {
  return cast FlightRuntime.coalesce(FlightRuntime.callProperty(os, 'locale', cast ([] : Array<Dynamic>)), function():Dynamic return cast '');
}, getLoginItem: function() {
  var out:AppLoginItem = cast FlightRuntime.UNDEFINED;
  out = { openAtLogin: false, openAsHidden: false, path: '', args: cast ([] : Array<Dynamic>) };
  return cast out;
}, getName: function() {
  return cast cachedName;
}, getPreferredSystemLanguages: function() {
  var locale:Dynamic = cast FlightRuntime.UNDEFINED;
  locale = FlightRuntime.callProperty(os, 'locale', cast ([] : Array<Dynamic>));
  return cast FlightRuntime.select(locale, function():Dynamic return cast cast ([locale] : Array<Dynamic>), function():Dynamic return cast cast ([] : Array<Dynamic>));
}, getSystemLocale: function() {
  return cast FlightRuntime.coalesce(FlightRuntime.callProperty(os, 'locale', cast ([] : Array<Dynamic>)), function():Dynamic return cast '');
}, getVersion: function() {
  return cast cachedVersion;
}, hasSingleInstanceLock: function() {
  return cast false;
}, hideApp: function() {
  FlightRuntime.callProperty(FlightRuntime.callProperty(app, 'hide', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  return cast true;
}, isAppHidden: function() {
  return cast false;
}, quit: function() {
  FlightRuntime.callProperty(FlightRuntime.callProperty(process, 'exit', cast ([0.0] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}, relaunch: function() {
  FlightRuntime.callProperty(FlightRuntime.callProperty(process, 'relaunch', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}, releaseSingleInstanceLock: function() {

}, requestAttention: function() {
  return cast -1.0;
}, requestSingleInstanceLock: function() {
  return cast true;
}, setActivationPolicy: function() {

}, setBadgeCount: function() {
  return cast false;
}, setDockBadge: function() {

}, setDockMenu: function() {

}, setLoginItem: function() {
  return cast false;
}, setName: function() {
  return cast false;
}, setUserModelId: function() {
  return cast false;
}, showApp: function() {
  FlightRuntime.callProperty(FlightRuntime.callProperty(app, 'show', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  return cast true;
}, subscribeActivate: function() {
  return cast function() {

};
}, subscribeAllWindowsClosed: function() {
  return cast function() {

};
}, subscribeOpenFile: function() {
  return cast function() {

};
}, subscribeQuitRequest: function() {
  return cast function() {

};
}, subscribeReady: function() {
  return cast function() {

};
}, subscribeSecondInstance: function() {
  return cast function() {

};
} };
    return cast null;
  }

  @:keep public static function createTauriClipboardBackend(tauri:TauriApi):ClipboardBackend {
    var clipboard:Dynamic = cast FlightRuntime.UNDEFINED;
    clipboard = FlightRuntime.field(tauri, 'clipboard');
    return cast { readText: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  try {
  return cast flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(clipboard, 'readText', cast ([] : Array<Dynamic>)));
} catch (__error:Dynamic) {
  return cast '';
}
  return cast null;
}), writeText: flight.internal.FlightAsync.make(function(text:Dynamic):flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(clipboard, 'writeText', cast ([text] : Array<Dynamic>)));
  return cast true;
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), readHtml: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast '';
  return cast null;
}), writeHtml: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), hasText: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  try {
  return cast FlightRuntime.compare(FlightRuntime.field(flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(clipboard, 'readText', cast ([] : Array<Dynamic>))), 'length'), 0.0, '>');
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), readImage: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast '';
  return cast null;
}), writeImage: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), hasImage: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), readRTF: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast '';
  return cast null;
}), writeRTF: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), readBookmark: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast null;
  return cast null;
}), writeBookmark: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), readFormat: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast '';
  return cast null;
}), writeFormat: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), hasFormat: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), getFormats: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast cast ([] : Array<Dynamic>);
  return cast null;
}), readItems: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast {  };
  return cast null;
}), writeItems: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), readFiles: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast cast ([] : Array<Dynamic>);
  return cast null;
}), writeFiles: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), clear: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(clipboard, 'clear', cast ([] : Array<Dynamic>)));
  return cast true;
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), getChangeCount: function() {
  return cast -1.0;
}, subscribeClipboardChange: function() {
  return cast function() {

};
} };
    return cast null;
  }

  @:keep public static function createTauriDialogBackend(tauri:TauriApi):DialogBackend {
    var dialog:Dynamic = cast FlightRuntime.UNDEFINED;
    dialog = FlightRuntime.field(tauri, 'dialog');
    return cast { openFile: flight.internal.FlightAsync.make(function(options:Dynamic):flight.internal.FlightPromise<Dynamic> {
  var result:Dynamic = cast FlightRuntime.UNDEFINED;
  var kind:Dynamic = cast FlightRuntime.UNDEFINED;
  result = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(dialog, 'open', cast ([{ title: FlightRuntime.field(options, 'title'), defaultPath: FlightRuntime.field(options, 'defaultPath'), multiple: FlightRuntime.field(options, 'multiple'), directory: FlightRuntime.field(options, 'directory'), filters: FlightRuntime.callOptionalProperty(FlightRuntime.field(options, 'filters'), 'map', cast ([HostTauri.toTauriFilter__tauriDialog] : Array<Dynamic>)) }] : Array<Dynamic>)));
  kind = FlightRuntime.select(FlightRuntime.field(options, 'directory'), function():Dynamic return cast 'Directory', function():Dynamic return cast 'File');
  return cast FlightRuntime.callValue(HostTauri.toHandles__tauriDialog, cast ([result, kind] : Array<Dynamic>));
  return cast null;
}), openDirectory: flight.internal.FlightAsync.make(function(options:Dynamic):flight.internal.FlightPromise<Dynamic> {
  var result:Dynamic = cast FlightRuntime.UNDEFINED;
  result = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(dialog, 'open', cast ([{ title: FlightRuntime.field(options, 'title'), multiple: FlightRuntime.field(options, 'multiple'), directory: true }] : Array<Dynamic>)));
  return cast FlightRuntime.callValue(HostTauri.toHandles__tauriDialog, cast ([result, 'Directory'] : Array<Dynamic>));
  return cast null;
}), saveFile: flight.internal.FlightAsync.make(function(options:Dynamic):flight.internal.FlightPromise<Dynamic> {
  var path:Dynamic = cast FlightRuntime.UNDEFINED;
  path = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(dialog, 'save', cast ([{ title: FlightRuntime.field(options, 'title'), defaultPath: FlightRuntime.field(options, 'defaultPath'), filters: FlightRuntime.callOptionalProperty(FlightRuntime.field(options, 'filters'), 'map', cast ([HostTauri.toTauriFilter__tauriDialog] : Array<Dynamic>)) }] : Array<Dynamic>)));
  return cast FlightRuntime.select(FlightRuntime.strictEquals(path, null), function():Dynamic return cast null, function():Dynamic return cast FlightRuntime.callValue(HostTauri.toFileHandle__tauriDialog, cast ([path, 'File'] : Array<Dynamic>)));
  return cast null;
}), message: flight.internal.FlightAsync.make(function(options:Dynamic):flight.internal.FlightPromise<Dynamic> {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(dialog, 'message', cast ([FlightRuntime.field(options, 'message'), { title: FlightRuntime.field(options, 'title'), kind: FlightRuntime.callValue(HostTauri.toTauriMessageKind__tauriDialog, cast ([FlightRuntime.field(options, 'kind')] : Array<Dynamic>)) }] : Array<Dynamic>)));
  return cast { buttonIndex: 0.0, cancelled: false, checkboxChecked: false };
  return cast null;
}), confirm: flight.internal.FlightAsync.make(function(options:Dynamic):flight.internal.FlightPromise<Dynamic> {
  return cast FlightRuntime.callProperty(dialog, 'confirm', cast ([FlightRuntime.field(options, 'message'), { title: FlightRuntime.field(options, 'title'), kind: FlightRuntime.callValue(HostTauri.toTauriMessageKind__tauriDialog, cast ([FlightRuntime.field(options, 'kind')] : Array<Dynamic>)) }] : Array<Dynamic>));
  return cast null;
}), prompt: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast null;
  return cast null;
}) };
    return cast null;
  }

  @:keep public static function createTauriMenuBackend(tauri:TauriApi):MenuBackend {
    var menuModule:Dynamic = cast FlightRuntime.UNDEFINED;
    var selectListener:Null<Dynamic> = cast FlightRuntime.UNDEFINED;
    menuModule = FlightRuntime.field(tauri, 'menu');
    selectListener = null;
    return cast { setApplicationMenu: function(items:Dynamic) {
  FlightRuntime.voidValue(FlightRuntime.callProperty(FlightRuntime.callValue(flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  var built:Dynamic = cast FlightRuntime.UNDEFINED;
  var menu:Dynamic = cast FlightRuntime.UNDEFINED;
  built = flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildItems__tauriMenu, cast ([menuModule, items, function(id:Dynamic) return FlightRuntime.callOptionalValue(selectListener, cast ([id] : Array<Dynamic>))] : Array<Dynamic>)));
  menu = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'Menu'), 'new', cast ([{ items: built }] : Array<Dynamic>)));
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(menu, 'setAsAppMenu', cast ([] : Array<Dynamic>)));
  return cast null;
}), cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)));
  return cast true;
}, popupContextMenu: function(items:Dynamic, x:Dynamic, y:Dynamic) {
  return cast FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Promise'] : Array<Dynamic>)), [function(resolve:Dynamic) {
  FlightRuntime.voidValue(FlightRuntime.callProperty(FlightRuntime.callValue(flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  var built:Dynamic = cast FlightRuntime.UNDEFINED;
  var menu:Dynamic = cast FlightRuntime.UNDEFINED;
  built = flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildItems__tauriMenu, cast ([menuModule, items, function(id:Dynamic) return FlightRuntime.callValue(resolve, cast ([id] : Array<Dynamic>))] : Array<Dynamic>)));
  menu = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'Menu'), 'new', cast ([{ items: built }] : Array<Dynamic>)));
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(menu, 'popup', cast ([FlightRuntime.construct(FlightRuntime.field(FlightRuntime.field(tauri, 'window'), 'LogicalPosition'), [x, y])] : Array<Dynamic>)));
  return cast null;
}), cast ([] : Array<Dynamic>)), 'catch', cast ([function() return FlightRuntime.callValue(resolve, cast ([null] : Array<Dynamic>))] : Array<Dynamic>)));
}]);
}, subscribeSelect: function(listener:Dynamic) {
  (selectListener = cast (listener : Dynamic));
  return cast function() {
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(selectListener, listener))) { (selectListener = cast (null : Dynamic)); }
};
} };
    return cast null;
  }

  @:keep public static function createTauriNotificationBackend(tauri:TauriApi):NotificationBackend {
    var notification:Dynamic = cast FlightRuntime.UNDEFINED;
    var nextId:Dynamic = cast FlightRuntime.UNDEFINED;
    var cachedPermission:Dynamic = cast FlightRuntime.UNDEFINED;
    notification = FlightRuntime.field(tauri, 'notification');
    nextId = 0.0;
    cachedPermission = 'default';
    FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime.callProperty(notification, 'isPermissionGranted', cast ([] : Array<Dynamic>)), 'then', cast ([function(granted:Dynamic) {
  (cachedPermission = cast (FlightRuntime.select(granted, function():Dynamic return cast 'granted', function():Dynamic return cast 'default') : Dynamic));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
    return cast { notify: flight.internal.FlightAsync.make(function(request:Dynamic):flight.internal.FlightPromise<Dynamic> {
  var id:Dynamic = cast FlightRuntime.UNDEFINED;
  id = FlightRuntime.coalesce(FlightRuntime.field(request, 'id'), function():Dynamic return cast 'notification-' + Std.string(nextId++) + '');
  try {
  FlightRuntime.callProperty(notification, 'sendNotification', cast ([{ title: FlightRuntime.field(request, 'title'), body: FlightRuntime.field(request, 'body'), icon: FlightRuntime.field(request, 'icon') }] : Array<Dynamic>));
  return cast id;
} catch (__error:Dynamic) {
  return cast '';
}
  return cast null;
}), requestPermission: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  try {
  var permission:Dynamic = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(notification, 'requestPermission', cast ([] : Array<Dynamic>)));
  (cachedPermission = cast (FlightRuntime.select(FlightRuntime.strictEquals(permission, 'granted'), function():Dynamic return cast 'granted', function():Dynamic return cast FlightRuntime.select(FlightRuntime.strictEquals(permission, 'denied'), function():Dynamic return cast 'denied', function():Dynamic return cast 'default')) : Dynamic));
  return cast cachedPermission;
} catch (__error:Dynamic) {
  return cast 'denied';
}
  return cast null;
}), getPermission: function() {
  return cast cachedPermission;
}, isSupported: function() {
  return cast true;
}, getCapabilities: function() {
  return cast { actions: false, channels: false, coldStart: false, image: false, listActive: false, scheduling: false, textReply: false };
}, getLaunchNotification: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast null;
  return cast null;
}), getActiveNotifications: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast cast ([] : Array<Dynamic>);
  return cast null;
}), getPendingNotifications: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast cast ([] : Array<Dynamic>);
  return cast null;
}), scheduleNotification: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast '';
  return cast null;
}), cancelScheduledNotification: function() {

}, closeNotification: function() {

}, closeAllNotifications: function() {

}, updateNotification: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), subscribeClick: function() {
  return cast function() {

};
}, subscribeAction: function() {
  return cast function() {

};
}, subscribeDismiss: function() {
  return cast function() {

};
}, subscribeReply: function() {
  return cast function() {

};
}, subscribeShow: function() {
  return cast function() {

};
} };
    return cast null;
  }

  @:keep public static function createTauriPlatformBackend(tauri:TauriApi):PlatformBackend {
    var os:Dynamic = cast FlightRuntime.UNDEFINED;
    os = FlightRuntime.field(tauri, 'os');
    return cast { getInfo: function(out:Dynamic) {
  FlightRuntime.setField(out, 'name', FlightRuntime.callValue(HostTauri.toPlatformName__tauriPlatform, cast ([FlightRuntime.callProperty(os, 'platform', cast ([] : Array<Dynamic>))] : Array<Dynamic>)));
  FlightRuntime.setField(out, 'kind', 'desktop');
  FlightRuntime.setField(out, 'version', FlightRuntime.callProperty(os, 'version', cast ([] : Array<Dynamic>)));
  FlightRuntime.setField(out, 'arch', FlightRuntime.callProperty(os, 'arch', cast ([] : Array<Dynamic>)));
  FlightRuntime.setField(out, 'locale', FlightRuntime.coalesce(FlightRuntime.callProperty(os, 'locale', cast ([] : Array<Dynamic>)), function():Dynamic return cast ''));
  FlightRuntime.setField(out, 'isTouch', false);
  FlightRuntime.setField(out, 'runtime', 'tauri');
  return cast out;
} };
    return cast null;
  }

  @:keep public static function createTauriShellBackend(tauri:TauriApi):ShellBackend {
    var opener:Dynamic = cast FlightRuntime.UNDEFINED;
    opener = FlightRuntime.field(tauri, 'opener');
    return cast { openExternal: flight.internal.FlightAsync.make(function(url:Dynamic):flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(opener, 'openUrl', cast ([url] : Array<Dynamic>)));
  return cast true;
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), openPath: flight.internal.FlightAsync.make(function(path:Dynamic):flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(opener, 'openPath', cast ([path] : Array<Dynamic>)));
  return cast true;
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), openPathResult: flight.internal.FlightAsync.make(function(path:Dynamic):flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(opener, 'openPath', cast ([path] : Array<Dynamic>)));
  return cast '';
} catch (error:Dynamic) {
  return cast FlightRuntime.select(FlightRuntime.isError(error), function():Dynamic return cast FlightRuntime.field(error, 'message'), function():Dynamic return cast Std.string(error));
}
  return cast null;
}), showItemInFolder: flight.internal.FlightAsync.make(function(path:Dynamic):flight.internal.FlightPromise<Dynamic> {
  try {
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(opener, 'revealItemInDir', cast ([path] : Array<Dynamic>)));
  return cast true;
} catch (__error:Dynamic) {
  return cast false;
}
  return cast null;
}), moveToTrash: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), moveItemsToTrash: flight.internal.FlightAsync.make(function(paths:Dynamic):flight.internal.FlightPromise<Dynamic> {
  return cast FlightRuntime.callProperty(paths, 'map', cast ([function() return false] : Array<Dynamic>));
  return cast null;
}), readShortcutLink: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast null;
  return cast null;
}), writeShortcutLink: flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  return cast false;
  return cast null;
}), beep: function() {

} };
    return cast null;
  }

  @:keep public static function createTauriShortcutBackend(tauri:TauriApi):ShortcutBackend {
    var globalShortcut:Dynamic = cast FlightRuntime.UNDEFINED;
    var registered:Dynamic = cast FlightRuntime.UNDEFINED;
    globalShortcut = FlightRuntime.field(tauri, 'globalShortcut');
    registered = FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Set'] : Array<Dynamic>)), []);
    return cast { getRegistered: function() {
  return cast FlightRuntime.concatArrays([FlightRuntime.toArray(registered)]);
}, isRegistered: function(accelerator:Dynamic) {
  return cast FlightRuntime.callProperty(registered, 'has', cast ([accelerator] : Array<Dynamic>));
}, register: function(accelerator:Dynamic, listener:Dynamic) {
  FlightRuntime.callProperty(registered, 'add', cast ([accelerator] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(globalShortcut, 'register', cast ([accelerator, function(event:Dynamic) {
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(event, 'state'), 'Pressed'))) { FlightRuntime.callValue(listener, cast ([{ accelerator: accelerator }] : Array<Dynamic>)); }
}] : Array<Dynamic>)), 'catch', cast ([function() {
  FlightRuntime.callProperty(registered, 'delete', cast ([accelerator] : Array<Dynamic>));
}] : Array<Dynamic>));
  return cast true;
}, setAllEnabled: function() {

}, setEnabled: function() {
  return cast false;
}, unregister: function(accelerator:Dynamic) {
  FlightRuntime.callProperty(registered, 'delete', cast ([accelerator] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(globalShortcut, 'unregister', cast ([accelerator] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  return cast true;
}, unregisterAll: function() {
  FlightRuntime.callProperty(registered, 'clear', cast ([] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(globalShortcut, 'unregisterAll', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
} };
    return cast null;
  }

  @:keep public static function createTauriTrayBackend(tauri:TauriApi):TrayBackend {
    var trayModule:Dynamic = cast FlightRuntime.UNDEFINED;
    var menuModule:Dynamic = cast FlightRuntime.UNDEFINED;
    var trays:Dynamic = cast FlightRuntime.UNDEFINED;
    var nextId:Dynamic = cast FlightRuntime.UNDEFINED;
    var eventListener:Null<Dynamic> = cast FlightRuntime.UNDEFINED;
    var emit:Dynamic = cast FlightRuntime.UNDEFINED;
    trayModule = FlightRuntime.field(tauri, 'tray');
    menuModule = FlightRuntime.field(tauri, 'menu');
    trays = FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Map'] : Array<Dynamic>)), []);
    nextId = 0.0;
    eventListener = null;
    emit = function(id:Float, type:TrayEventType) {
  FlightRuntime.callOptionalValue(eventListener, cast ([{ altKey: false, bounds: null, ctrlKey: false, dropFiles: null, dropText: null, id: id, metaKey: false, position: null, shiftKey: false, type: type }] : Array<Dynamic>));
};
    return cast { create: function(options:Dynamic) {
  var id:Dynamic = cast FlightRuntime.UNDEFINED;
  var record:TrayRecord__tauriTray = cast FlightRuntime.UNDEFINED;
  id = nextId++;
  record = { icon: null, title: FlightRuntime.coalesce(FlightRuntime.field(options, 'title'), function():Dynamic return cast ''), tooltip: FlightRuntime.coalesce(FlightRuntime.field(options, 'tooltip'), function():Dynamic return cast '') };
  FlightRuntime.callProperty(trays, 'set', cast ([id, record] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime.field(trayModule, 'TrayIcon'), 'new', cast ([{ icon: FlightRuntime.field(options, 'icon'), title: FlightRuntime.field(options, 'title'), tooltip: FlightRuntime.field(options, 'tooltip'), action: function(event:Dynamic) {
  var type:Dynamic = cast FlightRuntime.UNDEFINED;
  type = FlightRuntime.callValue(HostTauri.toTrayEventType__tauriTray, cast ([event] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(type, null))) { FlightRuntime.callValue(emit, cast ([id, type] : Array<Dynamic>)); }
} }] : Array<Dynamic>)), 'then', cast ([function(icon:Dynamic) {
  FlightRuntime.setField(record, 'icon', icon);
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  return cast id;
}, destroy: function(id:Dynamic) {
  var record:Dynamic = cast FlightRuntime.UNDEFINED;
  record = FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.truthy(record))) { return; }
  FlightRuntime.callOptionalProperty(FlightRuntime.callOptionalProperty(FlightRuntime.field(record, 'icon'), 'close', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  FlightRuntime.callProperty(trays, 'delete', cast ([id] : Array<Dynamic>));
}, displayBalloon: function() {

}, removeBalloon: function() {

}, getBounds: function() {
  return cast null;
}, getCapabilities: function() {
  return cast { balloon: false, bounds: false, clickEvents: true, dropFiles: false, pressedIcon: false, title: true };
}, getTitle: function(id:Dynamic) {
  return cast FlightRuntime.coalesce(FlightRuntime.optionalField(FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>)), 'title'), function():Dynamic return cast '');
}, getTooltip: function(id:Dynamic) {
  return cast FlightRuntime.coalesce(FlightRuntime.optionalField(FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>)), 'tooltip'), function():Dynamic return cast '');
}, isDestroyed: function(id:Dynamic) {
  return cast !FlightRuntime.truthy(FlightRuntime.callProperty(trays, 'has', cast ([id] : Array<Dynamic>)));
}, listIds: function() {
  return cast FlightRuntime.concatArrays([FlightRuntime.toArray(FlightRuntime.callProperty(trays, 'keys', cast ([] : Array<Dynamic>)))]);
}, popUpContextMenu: function(id:Dynamic) {
  FlightRuntime.voidValue(id);
}, setContextMenu: function(id:Dynamic, items:Dynamic) {
  var record:Dynamic = cast FlightRuntime.UNDEFINED;
  record = FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.truthy(record))) { return; }
  FlightRuntime.voidValue(FlightRuntime.callProperty(FlightRuntime.callValue(flight.internal.FlightAsync.make(function():flight.internal.FlightPromise<Dynamic> {
  var built:Dynamic = cast FlightRuntime.UNDEFINED;
  var menu:Dynamic = cast FlightRuntime.UNDEFINED;
  built = flight.internal.FlightAsync.awaitValue(FlightRuntime.callValue(HostTauri.buildTrayItems__tauriTray, cast ([menuModule, items] : Array<Dynamic>)));
  menu = flight.internal.FlightAsync.awaitValue(FlightRuntime.callProperty(FlightRuntime.field(menuModule, 'Menu'), 'new', cast ([{ items: built }] : Array<Dynamic>)));
  flight.internal.FlightAsync.awaitValue(FlightRuntime.callOptionalProperty(FlightRuntime.field(record, 'icon'), 'setMenu', cast ([menu] : Array<Dynamic>)));
  return cast null;
}), cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)));
}, setIcon: function(id:Dynamic, icon:Dynamic) {
  FlightRuntime.callOptionalProperty(FlightRuntime.callOptionalProperty(FlightRuntime.optionalField(FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>)), 'icon'), 'setIcon', cast ([icon] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}, setIgnoreDoubleClickEvents: function() {

}, setPressedIcon: function() {

}, setTemplate: function() {

}, setTitle: function(id:Dynamic, title:Dynamic) {
  var record:Dynamic = cast FlightRuntime.UNDEFINED;
  record = FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.truthy(record))) { return; }
  FlightRuntime.setField(record, 'title', title);
  FlightRuntime.callOptionalProperty(FlightRuntime.callOptionalProperty(FlightRuntime.field(record, 'icon'), 'setTitle', cast ([title] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}, setTooltip: function(id:Dynamic, tooltip:Dynamic) {
  var record:Dynamic = cast FlightRuntime.UNDEFINED;
  record = FlightRuntime.callProperty(trays, 'get', cast ([id] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.truthy(record))) { return; }
  FlightRuntime.setField(record, 'tooltip', tooltip);
  FlightRuntime.callOptionalProperty(FlightRuntime.callOptionalProperty(FlightRuntime.field(record, 'icon'), 'setTooltip', cast ([tooltip] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}, subscribe: function(listener:Dynamic) {
  (eventListener = cast (listener : Dynamic));
  return cast function() {
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(eventListener, listener))) { (eventListener = cast (null : Dynamic)); }
};
} };
    return cast null;
  }

  @:keep public static function createTauriWindowBackend(tauri:TauriApi):WindowBackend {
    var windowModule:Dynamic = cast FlightRuntime.UNDEFINED;
    var windows:Dynamic = cast FlightRuntime.UNDEFINED;
    var run:Dynamic = cast FlightRuntime.UNDEFINED;
    windowModule = FlightRuntime.field(tauri, 'window');
    windows = FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['WeakMap'] : Array<Dynamic>)), []);
    run = function(win:ApplicationWindow, fn:Dynamic) {
  var w:Dynamic = cast FlightRuntime.UNDEFINED;
  w = FlightRuntime.callProperty(windows, 'get', cast ([win] : Array<Dynamic>));
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(w, FlightRuntime.UNDEFINED))) { return; }
  FlightRuntime.callProperty(FlightRuntime.callValue(fn, cast ([w] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
};
    return cast { open: function(win:Dynamic, options:Dynamic) {
  var w:Dynamic = cast FlightRuntime.UNDEFINED;
  w = FlightRuntime.callProperty(windowModule, 'getCurrentWindow', cast ([] : Array<Dynamic>));
  FlightRuntime.callProperty(windows, 'set', cast ([win, w] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'title'), FlightRuntime.UNDEFINED))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setTitle', cast ([FlightRuntime.field(options, 'title')] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'width'), FlightRuntime.UNDEFINED), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(options, 'height'), FlightRuntime.UNDEFINED)))) {
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [FlightRuntime.field(options, 'width'), FlightRuntime.field(options, 'height')])] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'x'), FlightRuntime.UNDEFINED), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(options, 'y'), FlightRuntime.UNDEFINED)))) {
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setPosition', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalPosition'), [FlightRuntime.field(options, 'x'), FlightRuntime.field(options, 'y')])] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'resizable'), FlightRuntime.UNDEFINED))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setResizable', cast ([FlightRuntime.field(options, 'resizable')] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'alwaysOnTop'), FlightRuntime.UNDEFINED))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setAlwaysOnTop', cast ([FlightRuntime.field(options, 'alwaysOnTop')] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'fullscreen'), FlightRuntime.UNDEFINED))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setFullscreen', cast ([FlightRuntime.field(options, 'fullscreen')] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'minWidth'), FlightRuntime.UNDEFINED), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(options, 'minHeight'), FlightRuntime.UNDEFINED)))) {
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setMinSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [FlightRuntime.field(options, 'minWidth'), FlightRuntime.field(options, 'minHeight')])] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}
  if (FlightRuntime.truthy(FlightRuntime.andValue(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(options, 'maxWidth'), FlightRuntime.UNDEFINED), function():Dynamic return cast FlightRuntime.compare(FlightRuntime.field(options, 'maxWidth'), 0.0, '>=')), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(options, 'maxHeight'), FlightRuntime.UNDEFINED)))) {
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'setMaxSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [FlightRuntime.field(options, 'maxWidth'), FlightRuntime.field(options, 'maxHeight')])] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
}
  if (FlightRuntime.truthy(FlightRuntime.field(options, 'center'))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'center', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(FlightRuntime.field(options, 'maximized'))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'maximize', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(FlightRuntime.field(options, 'minimized'))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'minimize', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(options, 'visible'), false))) { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'hide', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); } else { FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'show', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>)); }
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'onMoved', cast ([function(event:Dynamic) {
  FlightRuntime.setField(win, 'x', FlightRuntime.field(FlightRuntime.field(event, 'payload'), 'x'));
  FlightRuntime.setField(win, 'y', FlightRuntime.field(FlightRuntime.field(event, 'payload'), 'y'));
  FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(win, 'onMove')] : Array<Dynamic>));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'onResized', cast ([function(event:Dynamic) {
  FlightRuntime.setField(win, 'width', FlightRuntime.field(FlightRuntime.field(event, 'payload'), 'width'));
  FlightRuntime.setField(win, 'height', FlightRuntime.field(FlightRuntime.field(event, 'payload'), 'height'));
  FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(win, 'onResize')] : Array<Dynamic>));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'onFocusChanged', cast ([function(event:Dynamic) {
  FlightRuntime.setField(win, 'focused', FlightRuntime.field(event, 'payload'));
  FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.select(FlightRuntime.field(event, 'payload'), function():Dynamic return cast FlightRuntime.field(win, 'onFocusIn'), function():Dynamic return cast FlightRuntime.field(win, 'onFocusOut'))] : Array<Dynamic>));
}] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'onCloseRequested', cast ([function() return FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(win, 'onClose')] : Array<Dynamic>))] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  return cast true;
}, close: function(win:Dynamic) {
  var w:Dynamic = cast FlightRuntime.UNDEFINED;
  w = FlightRuntime.callProperty(windows, 'get', cast ([win] : Array<Dynamic>));
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(w, FlightRuntime.UNDEFINED))) { return; }
  FlightRuntime.callProperty(FlightRuntime.callProperty(w, 'close', cast ([] : Array<Dynamic>)), 'catch', cast ([function() {

}] : Array<Dynamic>));
  FlightRuntime.callProperty(windows, 'delete', cast ([win] : Array<Dynamic>));
}, setTitle: function(win:Dynamic, title:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setTitle', cast ([title] : Array<Dynamic>))] : Array<Dynamic>));
}, setPosition: function(win:Dynamic, x:Dynamic, y:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setPosition', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalPosition'), [x, y])] : Array<Dynamic>))] : Array<Dynamic>));
}, setSize: function(win:Dynamic, width:Dynamic, height:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [width, height])] : Array<Dynamic>))] : Array<Dynamic>));
}, getBounds: function(win:Dynamic, out:Dynamic) {
  FlightRuntime.setField(out, 'x', FlightRuntime.field(win, 'x'));
  FlightRuntime.setField(out, 'y', FlightRuntime.field(win, 'y'));
  FlightRuntime.setField(out, 'width', FlightRuntime.field(win, 'width'));
  FlightRuntime.setField(out, 'height', FlightRuntime.field(win, 'height'));
  return cast out;
}, minimize: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'minimize', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, maximize: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'maximize', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, restore: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'unmaximize', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, focus: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setFocus', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, show: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'show', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, hide: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'hide', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, center: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'center', cast ([] : Array<Dynamic>))] : Array<Dynamic>));
}, setResizable: function(win:Dynamic, resizable:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setResizable', cast ([resizable] : Array<Dynamic>))] : Array<Dynamic>));
}, setAlwaysOnTop: function(win:Dynamic, alwaysOnTop:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setAlwaysOnTop', cast ([alwaysOnTop] : Array<Dynamic>))] : Array<Dynamic>));
}, setMinimumSize: function(win:Dynamic, width:Dynamic, height:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setMinSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [width, height])] : Array<Dynamic>))] : Array<Dynamic>));
}, setMaximumSize: function(win:Dynamic, width:Dynamic, height:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setMaxSize', cast ([FlightRuntime.construct(FlightRuntime.field(windowModule, 'LogicalSize'), [width, height])] : Array<Dynamic>))] : Array<Dynamic>));
}, setFullscreen: function(win:Dynamic, fullscreen:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setFullscreen', cast ([fullscreen] : Array<Dynamic>))] : Array<Dynamic>));
}, setIcon: function(win:Dynamic, icon:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setIcon', cast ([icon] : Array<Dynamic>))] : Array<Dynamic>));
}, setOpacity: function() {

}, setSkipTaskbar: function(win:Dynamic, skip:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setSkipTaskbar', cast ([skip] : Array<Dynamic>))] : Array<Dynamic>));
}, setMenuBarVisible: function() {

}, setParent: function() {

}, setProgress: function() {

}, requestAttention: function(win:Dynamic, attention:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'requestUserAttention', cast ([FlightRuntime.select(attention, function():Dynamic return cast 1.0, function():Dynamic return cast null)] : Array<Dynamic>))] : Array<Dynamic>));
}, setContentProtection: function(win:Dynamic, enabled:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setContentProtected', cast ([enabled] : Array<Dynamic>))] : Array<Dynamic>));
}, flashWindowFrame: function(win:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'requestUserAttention', cast ([2.0] : Array<Dynamic>))] : Array<Dynamic>));
}, setHasShadow: function(win:Dynamic, hasShadow:Dynamic) {
  FlightRuntime.callValue(run, cast ([win, function(w:Dynamic) return FlightRuntime.callProperty(w, 'setShadow', cast ([hasShadow] : Array<Dynamic>))] : Array<Dynamic>));
} };
    return cast null;
  }

  @:keep public static function registerTauriBackends(tauri:TauriApi):Void {
    FlightRuntime.callValue(setPlatformBackend, cast ([FlightRuntime.callValue(createTauriPlatformBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setAppBackend, cast ([FlightRuntime.callValue(createTauriAppBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setWindowBackend, cast ([FlightRuntime.callValue(createTauriWindowBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setDialogBackend, cast ([FlightRuntime.callValue(createTauriDialogBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setClipboardBackend, cast ([FlightRuntime.callValue(createTauriClipboardBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setMenuBackend, cast ([FlightRuntime.callValue(createTauriMenuBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setTrayBackend, cast ([FlightRuntime.callValue(createTauriTrayBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setShortcutBackend, cast ([FlightRuntime.callValue(createTauriShortcutBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setNotificationBackend, cast ([FlightRuntime.callValue(createTauriNotificationBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
    FlightRuntime.callValue(setShellBackend, cast ([FlightRuntime.callValue(createTauriShellBackend, cast ([tauri] : Array<Dynamic>))] : Array<Dynamic>));
  }

  @:keep public static function toFileHandle__tauriDialog(path:String, kind:String):FileDialogHandle {
    return cast { kind: kind, name: FlightRuntime.callValue(HostTauri.basename__tauriDialog, cast ([path] : Array<Dynamic>)), path: path };
    return cast null;
  }

  @:keep public static function toHandles__tauriDialog(result:Null<Dynamic>, kind:String):Array<FileDialogHandle> {
    var paths:Dynamic = cast FlightRuntime.UNDEFINED;
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(result, null))) { return cast cast ([] : Array<Dynamic>); }
    paths = FlightRuntime.select(FlightRuntime.isArray(result), function():Dynamic return cast result, function():Dynamic return cast cast ([result] : Array<Dynamic>));
    return cast FlightRuntime.callProperty(paths, 'map', cast ([function(path:Dynamic) return FlightRuntime.callValue(HostTauri.toFileHandle__tauriDialog, cast ([path, kind] : Array<Dynamic>))] : Array<Dynamic>));
    return cast null;
  }

  @:keep public static function toPlatformName__tauriPlatform(platform:String):PlatformName {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(platform, 'windows'))) { return cast 'windows'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(platform, 'macos'))) { return cast 'macos'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(platform, 'linux'))) { return cast 'linux'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(platform, 'ios'))) { return cast 'ios'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(platform, 'android'))) { return cast 'android'; }
    return cast 'unknown';
    return cast null;
  }

  @:keep public static function toTauriFilter__tauriDialog(filter:FileDialogFilter):TauriDialogFilter {
    return cast { name: FlightRuntime.field(filter, 'name'), extensions: FlightRuntime.concatArrays([FlightRuntime.toArray(FlightRuntime.field(filter, 'extensions'))]) };
    return cast null;
  }

  @:keep public static function toTauriMessageKind__tauriDialog(kind:Null<MessageDialogKind>):String {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(kind, 'warning'))) { return cast 'warning'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(kind, 'error'))) { return cast 'error'; }
    return cast 'info';
    return cast null;
  }

  @:keep public static function toTrayEventType__tauriTray(event:Dynamic):Null<TrayEventType> {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(event, 'type'), 'DoubleClick'))) { return cast 'doubleClick'; }
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(event, 'type'), 'Click'))) { return cast FlightRuntime.select(FlightRuntime.strictEquals(FlightRuntime.field(event, 'button'), 'Right'), function():Dynamic return cast 'rightClick', function():Dynamic return cast 'click'); }
    return cast null;
    return cast null;
  }
}
