// Generated by flight-hx. Do not edit.
package flight;

import Math as HxMath;
import flight.internal.FlightRuntime;
import flight.Signals.createSignal;
import flight.Signals.emitSignal;
import flight.Types.MenuBackend;
import flight.Types.MenuItemTemplate;
import flight.Types.MenuSignals;

#if js
@:build(jsasync.JSAsync.build())
#end
@:expose("flight.Menu")
class Menu {
  public static var _backend__menu:Null<MenuBackend> = FlightRuntime.explicitNull();

  public static var _menuSignals__menu:Null<MenuSignals> = FlightRuntime.explicitNull();

  @:keep public static function _validateItem__menu(item:MenuItemTemplate, seen:Dynamic):Null<String> {
    if (FlightRuntime.truthy(FlightRuntime.callProperty(seen, 'has', cast ([item] : Array<Dynamic>)))) {
  throw FlightRuntime.error('validateMenuItemTemplate: cyclic submenu reference detected');
}
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'separator'))) {
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'label'), FlightRuntime.UNDEFINED), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(item, 'label'), '')))) {
  return cast 'separator item has a label: "' + Std.string(FlightRuntime.field(item, 'label')) + '" (separators should not have labels)';
}
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'accelerator'), FlightRuntime.UNDEFINED))) {
  return cast 'separator item has an accelerator: "' + Std.string(FlightRuntime.field(item, 'accelerator')) + '"';
}
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'submenu'), FlightRuntime.UNDEFINED))) {
  return cast 'separator item has a submenu';
}
  return cast null;
}
    if (FlightRuntime.truthy(FlightRuntime.andValue(FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'submenu'), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(item, 'submenu'), FlightRuntime.UNDEFINED)), function():Dynamic return cast FlightRuntime.compare(FlightRuntime.field(FlightRuntime.field(item, 'submenu'), 'length'), 0.0, '>')))) {
  return cast 'item type "' + Std.string(FlightRuntime.coalesce(FlightRuntime.field(item, 'type'), function():Dynamic return cast 'normal')) + '" has a submenu (only type "submenu" should carry children)';
}
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'submenu'), FlightRuntime.UNDEFINED))) {
  FlightRuntime.callProperty(seen, 'add', cast ([item] : Array<Dynamic>));
  for (child in FlightRuntime.iterable(FlightRuntime.field(item, 'submenu'))) {
    var err:Dynamic = FlightRuntime.callValue(Menu._validateItem__menu, cast ([child, seen] : Array<Dynamic>));
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(err, null))) { return cast err; }
  }
  FlightRuntime.callProperty(seen, 'delete', cast ([item] : Array<Dynamic>));
}
    return cast null;
    return cast null;
  }

  @:keep public static function buildWebMenuElement__menu(items:Array<MenuItemTemplate>, onSelect:Dynamic):Dynamic {
    var menu:Dynamic = cast FlightRuntime.UNDEFINED;
    menu = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['ul'] : Array<Dynamic>));
    FlightRuntime.setField(FlightRuntime.field(menu, 'style'), 'cssText', FlightRuntime.join(cast (['position:fixed', 'z-index:2147483647', 'margin:0', 'padding:4px 0', 'list-style:none', 'background:#fff', 'border:1px solid #ccc', 'border-radius:4px', 'box-shadow:0 4px 12px rgba(0,0,0,.15)', 'min-width:160px', 'font:13px/1.4 system-ui,sans-serif', 'color:#111', 'user-select:none'] : Array<Dynamic>), ';'));
    for (item in FlightRuntime.iterable(items)) {
      var li:Dynamic = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['li'] : Array<Dynamic>));
      if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'separator'))) {
  FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'cssText', 'height:1px;margin:4px 8px;background:#e0e0e0;');
  FlightRuntime.callProperty(menu, 'appendChild', cast ([li] : Array<Dynamic>));
  continue;
}
      var enabled:Dynamic = !FlightRuntime.strictEquals(FlightRuntime.field(item, 'enabled'), false);
      var hasSubmenu:Dynamic = FlightRuntime.andValue(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'submenu'), FlightRuntime.UNDEFINED), function():Dynamic return cast FlightRuntime.compare(FlightRuntime.field(FlightRuntime.field(item, 'submenu'), 'length'), 0.0, '>'));
      FlightRuntime.callProperty(li, 'setAttribute', cast (['data-enabled', FlightRuntime.select(enabled, function():Dynamic return cast 'true', function():Dynamic return cast 'false')] : Array<Dynamic>));
      if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'id'), FlightRuntime.UNDEFINED))) { FlightRuntime.setIndex(FlightRuntime.field(li, 'dataset'), 'itemId', FlightRuntime.field(item, 'id')); }
      FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'cssText', FlightRuntime.join(cast (['display:flex', 'align-items:center', 'padding:5px 12px 5px 28px', ('cursor:' + FlightRuntime.select(enabled, function():Dynamic return cast 'default', function():Dynamic return cast 'not-allowed')), ('color:' + FlightRuntime.select(enabled, function():Dynamic return cast '#111', function():Dynamic return cast '#999')), 'position:relative'] : Array<Dynamic>), ';'));
      if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(item, 'checked'), true))) {
  var mark:Dynamic = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['span'] : Array<Dynamic>));
  FlightRuntime.setField(mark, 'textContent', FlightRuntime.select(FlightRuntime.strictEquals(FlightRuntime.field(item, 'type'), 'radio'), function():Dynamic return cast '●', function():Dynamic return cast '✓'));
  FlightRuntime.setField(FlightRuntime.field(mark, 'style'), 'cssText', 'position:absolute;left:8px;font-size:11px;');
  FlightRuntime.callProperty(li, 'appendChild', cast ([mark] : Array<Dynamic>));
}
      var labelEl:Dynamic = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['span'] : Array<Dynamic>));
      FlightRuntime.setField(labelEl, 'textContent', FlightRuntime.coalesce(FlightRuntime.field(item, 'label'), function():Dynamic return cast ''));
      FlightRuntime.setField(FlightRuntime.field(labelEl, 'style'), 'cssText', 'flex:1;');
      FlightRuntime.callProperty(li, 'appendChild', cast ([labelEl] : Array<Dynamic>));
      if (FlightRuntime.truthy(hasSubmenu)) {
  var arrow:Dynamic = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['span'] : Array<Dynamic>));
  FlightRuntime.setField(arrow, 'textContent', '▶');
  FlightRuntime.setField(FlightRuntime.field(arrow, 'style'), 'cssText', 'margin-left:8px;font-size:9px;color:#888;');
  FlightRuntime.callProperty(li, 'appendChild', cast ([arrow] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'accelerator'), FlightRuntime.UNDEFINED))) {
  var accel:Dynamic = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['span'] : Array<Dynamic>));
  FlightRuntime.setField(accel, 'textContent', FlightRuntime.field(item, 'accelerator'));
  FlightRuntime.setField(FlightRuntime.field(accel, 'style'), 'cssText', 'margin-left:24px;color:#888;font-size:11px;');
  FlightRuntime.callProperty(li, 'appendChild', cast ([accel] : Array<Dynamic>));
} }
      if (FlightRuntime.truthy(enabled)) {
  FlightRuntime.callProperty(li, 'addEventListener', cast (['mouseenter', function() {
  var accelEl:Dynamic = cast FlightRuntime.UNDEFINED;
  FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'background', '#0066cc');
  FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'color', '#fff');
  accelEl = FlightRuntime.callProperty(li, 'querySelector', cast (['span:last-child'] : Array<Dynamic>));
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(accelEl, null), function():Dynamic return cast !FlightRuntime.strictEquals(accelEl, labelEl)))) { FlightRuntime.setField(FlightRuntime.field(accelEl, 'style'), 'color', 'rgba(255,255,255,.7)'); }
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(Menu._menuSignals__menu, null), function():Dynamic return cast !FlightRuntime.strictEquals(FlightRuntime.field(item, 'id'), FlightRuntime.UNDEFINED)))) {
  FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(Menu._menuSignals__menu, 'onMenuItemHighlight'), FlightRuntime.field(item, 'id')] : Array<Dynamic>));
}
}] : Array<Dynamic>));
  FlightRuntime.callProperty(li, 'addEventListener', cast (['mouseleave', function() {
  var accelEl:Dynamic = cast FlightRuntime.UNDEFINED;
  FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'background', '');
  FlightRuntime.setField(FlightRuntime.field(li, 'style'), 'color', '#111');
  accelEl = FlightRuntime.callProperty(li, 'querySelector', cast (['span:last-child'] : Array<Dynamic>));
  if (FlightRuntime.truthy(FlightRuntime.andValue(!FlightRuntime.strictEquals(accelEl, null), function():Dynamic return cast !FlightRuntime.strictEquals(accelEl, labelEl)))) { FlightRuntime.setField(FlightRuntime.field(accelEl, 'style'), 'color', '#888'); }
}] : Array<Dynamic>));
  if (FlightRuntime.truthy(hasSubmenu)) {
  var submenuEl:Dynamic = FlightRuntime.callValue(Menu.buildWebMenuElement__menu, cast ([FlightRuntime.field(item, 'submenu'), onSelect] : Array<Dynamic>));
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'position', 'absolute');
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'top', '0');
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'left', '100%');
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'display', 'none');
  FlightRuntime.callProperty(li, 'appendChild', cast ([submenuEl] : Array<Dynamic>));
  FlightRuntime.callProperty(li, 'addEventListener', cast (['mouseenter', function() {
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'display', 'block');
}] : Array<Dynamic>));
  FlightRuntime.callProperty(li, 'addEventListener', cast (['mouseleave', function() {
  FlightRuntime.setField(FlightRuntime.field(submenuEl, 'style'), 'display', 'none');
}] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'id'), FlightRuntime.UNDEFINED))) {
  var itemId:Dynamic = FlightRuntime.field(item, 'id');
  FlightRuntime.callProperty(li, 'addEventListener', cast (['click', function(e:Dynamic) {
  FlightRuntime.callProperty(e, 'stopPropagation', cast ([] : Array<Dynamic>));
  FlightRuntime.callValue(onSelect, cast ([itemId] : Array<Dynamic>));
}] : Array<Dynamic>));
} }
}
      FlightRuntime.callProperty(menu, 'appendChild', cast ([li] : Array<Dynamic>));
    }
    return cast menu;
    return cast null;
  }

  @:keep public static function cloneMenuTemplate(template:MenuItemTemplate):MenuItemTemplate {
    var clone:MenuItemTemplate = cast FlightRuntime.UNDEFINED;
    clone = FlightRuntime.mergeObjects([template]);
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(template, 'submenu'), FlightRuntime.UNDEFINED))) {
  FlightRuntime.setField(clone, 'submenu', FlightRuntime.callProperty(FlightRuntime.field(template, 'submenu'), 'map', cast ([cloneMenuTemplate] : Array<Dynamic>)));
}
    return cast clone;
    return cast null;
  }

  @:keep public static function createDefaultAppMenuTemplate(appName:String):MenuItemTemplate {
    return cast { label: appName, role: Types.WellKnownMenuItemRole.appMenu, type: 'submenu', submenu: cast ([{ id: 'about', label: 'About ' + Std.string(appName) + '', role: Types.WellKnownMenuItemRole.about, type: 'normal', enabled: true }, { type: 'separator', enabled: true }, { id: 'services', label: 'Services', role: Types.WellKnownMenuItemRole.services, type: 'submenu', submenu: cast ([] : Array<Dynamic>), enabled: true }, { type: 'separator', enabled: true }, { id: 'hide', label: 'Hide ' + Std.string(appName) + '', role: Types.WellKnownMenuItemRole.hide, accelerator: 'CmdOrCtrl+H', type: 'normal', enabled: true }, { id: 'hideOthers', label: 'Hide Others', role: Types.WellKnownMenuItemRole.hideOthers, accelerator: 'CmdOrCtrl+Alt+H', type: 'normal', enabled: true }, { id: 'unhide', label: 'Show All', role: Types.WellKnownMenuItemRole.unhide, type: 'normal', enabled: true }, { type: 'separator', enabled: true }, { id: 'quit', label: 'Quit ' + Std.string(appName) + '', role: Types.WellKnownMenuItemRole.quit, accelerator: 'CmdOrCtrl+Q', type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createDefaultEditMenuTemplate():MenuItemTemplate {
    return cast { label: 'Edit', role: Types.WellKnownMenuItemRole.editMenu, type: 'submenu', submenu: cast ([{ id: 'undo', label: 'Undo', role: Types.WellKnownMenuItemRole.undo, accelerator: 'CmdOrCtrl+Z', type: 'normal', enabled: true }, { id: 'redo', label: 'Redo', role: Types.WellKnownMenuItemRole.redo, accelerator: 'Shift+CmdOrCtrl+Z', type: 'normal', enabled: true }, { type: 'separator', enabled: true }, { id: 'cut', label: 'Cut', role: Types.WellKnownMenuItemRole.cut, accelerator: 'CmdOrCtrl+X', type: 'normal', enabled: true }, { id: 'copy', label: 'Copy', role: Types.WellKnownMenuItemRole.copy, accelerator: 'CmdOrCtrl+C', type: 'normal', enabled: true }, { id: 'paste', label: 'Paste', role: Types.WellKnownMenuItemRole.paste, accelerator: 'CmdOrCtrl+V', type: 'normal', enabled: true }, { id: 'pasteAndMatchStyle', label: 'Paste and Match Style', role: Types.WellKnownMenuItemRole.pasteAndMatchStyle, accelerator: 'Shift+CmdOrCtrl+V', type: 'normal', enabled: true }, { id: 'delete', label: 'Delete', role: Types.WellKnownMenuItemRole.delete, type: 'normal', enabled: true }, { id: 'selectAll', label: 'Select All', role: Types.WellKnownMenuItemRole.selectAll, accelerator: 'CmdOrCtrl+A', type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createDefaultFileMenuTemplate():MenuItemTemplate {
    return cast { label: 'File', role: Types.WellKnownMenuItemRole.fileMenu, type: 'submenu', submenu: cast ([{ id: 'newFile', label: 'New', type: 'normal', accelerator: 'CmdOrCtrl+N', enabled: true }, { id: 'openFile', label: 'Open…', type: 'normal', accelerator: 'CmdOrCtrl+O', enabled: true }, { type: 'separator', enabled: true }, { id: 'saveFile', label: 'Save', type: 'normal', accelerator: 'CmdOrCtrl+S', enabled: true }, { id: 'saveFileAs', label: 'Save As…', type: 'normal', accelerator: 'Shift+CmdOrCtrl+S', enabled: true }, { type: 'separator', enabled: true }, { id: 'closeFile', label: 'Close', role: Types.WellKnownMenuItemRole.close, accelerator: 'CmdOrCtrl+W', type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createDefaultHelpMenuTemplate():MenuItemTemplate {
    return cast { label: 'Help', role: Types.WellKnownMenuItemRole.helpMenu, type: 'submenu', submenu: cast ([{ id: 'help', label: 'Search', role: Types.WellKnownMenuItemRole.help, type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createDefaultViewMenuTemplate():MenuItemTemplate {
    return cast { label: 'View', role: Types.WellKnownMenuItemRole.viewMenu, type: 'submenu', submenu: cast ([{ id: 'reload', label: 'Reload', role: Types.WellKnownMenuItemRole.reload, accelerator: 'CmdOrCtrl+R', type: 'normal', enabled: true }, { type: 'separator', enabled: true }, { id: 'resetZoom', label: 'Actual Size', role: Types.WellKnownMenuItemRole.resetZoom, accelerator: 'CmdOrCtrl+0', type: 'normal', enabled: true }, { id: 'zoomIn', label: 'Zoom In', role: Types.WellKnownMenuItemRole.zoomIn, accelerator: 'CmdOrCtrl+Plus', type: 'normal', enabled: true }, { id: 'zoomOut', label: 'Zoom Out', role: Types.WellKnownMenuItemRole.zoomOut, accelerator: 'CmdOrCtrl+-', type: 'normal', enabled: true }, { type: 'separator', enabled: true }, { id: 'toggleFullscreen', label: 'Toggle Full Screen', role: Types.WellKnownMenuItemRole.toggleFullscreen, accelerator: 'F11', type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createDefaultWindowMenuTemplate():MenuItemTemplate {
    return cast { label: 'Window', role: Types.WellKnownMenuItemRole.windowMenu, type: 'submenu', submenu: cast ([{ id: 'minimize', label: 'Minimize', role: Types.WellKnownMenuItemRole.minimize, accelerator: 'CmdOrCtrl+M', type: 'normal', enabled: true }, { id: 'close', label: 'Close', role: Types.WellKnownMenuItemRole.close, accelerator: 'CmdOrCtrl+W', type: 'normal', enabled: true }] : Array<Dynamic>), enabled: true };
    return cast null;
  }

  @:keep public static function createMenuItemTemplate(?template:Dynamic):MenuItemTemplate {
    var item:MenuItemTemplate = cast FlightRuntime.UNDEFINED;
    item = FlightRuntime.mergeObjects([{ type: 'normal' }, { enabled: true }, template]);
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(FlightRuntime.field(item, 'submenu'), FlightRuntime.UNDEFINED))) {
  FlightRuntime.setField(item, 'submenu', FlightRuntime.callProperty(FlightRuntime.field(item, 'submenu'), 'map', cast ([function(child:Dynamic) return FlightRuntime.callValue(createMenuItemTemplate, cast ([child] : Array<Dynamic>))] : Array<Dynamic>)));
}
    return cast item;
    return cast null;
  }

  @:keep public static function createWebMenuBackend():MenuBackend {
    return cast { setApplicationMenu: function() {
  return cast false;
}, popupContextMenu: function(items:Dynamic, x:Dynamic, y:Dynamic) {
  return cast FlightRuntime.callValue(Menu.showWebContextMenu__menu, cast ([items, x, y] : Array<Dynamic>));
}, subscribeSelect: function() {
  return cast function() {

};
} };
    return cast null;
  }

  @:keep public static function enableMenuSignals():MenuSignals {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(Menu._menuSignals__menu, null))) {
  (Menu._menuSignals__menu = cast ({ onContextMenuClose: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onContextMenuOpen: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onMenuItemHighlight: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)), onMenuItemSelect: FlightRuntime.callValue(createSignal, cast ([] : Array<Dynamic>)) } : Dynamic));
}
    return cast Menu._menuSignals__menu;
    return cast null;
  }

  @:keep public static function getMenuBackend():MenuBackend {
    if (FlightRuntime.truthy(FlightRuntime.strictEquals(Menu._backend__menu, null))) { (Menu._backend__menu = cast (FlightRuntime.callValue(createWebMenuBackend, cast ([] : Array<Dynamic>)) : Dynamic)); }
    return cast Menu._backend__menu;
    return cast null;
  }

  @:keep public static function getMenuSignals():Null<MenuSignals> {
    return cast Menu._menuSignals__menu;
    return cast null;
  }

  @:keep public static function onMenuSelect(listener:Dynamic):Dynamic {
    return cast FlightRuntime.callProperty(FlightRuntime.callValue(getMenuBackend, cast ([] : Array<Dynamic>)), 'subscribeSelect', cast ([function(id:Dynamic) {
  FlightRuntime.callValue(listener, cast ([id] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(Menu._menuSignals__menu, null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(Menu._menuSignals__menu, 'onMenuItemSelect'), id] : Array<Dynamic>)); }
}] : Array<Dynamic>));
    return cast null;
  }

  @:keep public static function setApplicationMenu(items:Array<MenuItemTemplate>):Bool {
    return cast FlightRuntime.callProperty(FlightRuntime.callValue(getMenuBackend, cast ([] : Array<Dynamic>)), 'setApplicationMenu', cast ([items] : Array<Dynamic>));
    return cast null;
  }

  @:keep public static function setMenuBackend(backend:Null<MenuBackend>):Void {
    (Menu._backend__menu = cast (backend : Dynamic));
  }

  @:keep public static function showContextMenu(items:Array<MenuItemTemplate>, x:Float, y:Float):flight.internal.FlightPromise<Null<String>> {
    var promise:Dynamic = cast FlightRuntime.UNDEFINED;
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(Menu._menuSignals__menu, null))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(Menu._menuSignals__menu, 'onContextMenuOpen')] : Array<Dynamic>)); }
    promise = FlightRuntime.callProperty(FlightRuntime.callValue(getMenuBackend, cast ([] : Array<Dynamic>)), 'popupContextMenu', cast ([items, x, y] : Array<Dynamic>));
    if (FlightRuntime.truthy(!FlightRuntime.strictEquals(Menu._menuSignals__menu, null))) {
  var signals:Dynamic = Menu._menuSignals__menu;
  FlightRuntime.voidValue(FlightRuntime.callProperty(promise, 'then', cast ([function() return FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(signals, 'onContextMenuClose')] : Array<Dynamic>))] : Array<Dynamic>)));
}
    return cast promise;
    return cast null;
  }

  @:keep public static function showWebContextMenu__menu(items:Array<MenuItemTemplate>, x:Float, y:Float):flight.internal.FlightPromise<Null<String>> {
    return cast FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Promise'] : Array<Dynamic>)), [function(resolve:Dynamic) {
  var overlay:Dynamic = cast FlightRuntime.UNDEFINED;
  var menu:Dynamic = cast FlightRuntime.UNDEFINED;
  var clampMenu:Dynamic->Float->Float->Void = cast FlightRuntime.UNDEFINED;
  var close:Null<String>->Void = cast FlightRuntime.UNDEFINED;
  var focusableItems:Dynamic = cast FlightRuntime.UNDEFINED;
  var focusIndex:Dynamic = cast FlightRuntime.UNDEFINED;
  var moveFocus:Float->Void = cast FlightRuntime.UNDEFINED;
  var onKeyDown:Dynamic->Void = cast FlightRuntime.UNDEFINED;
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.callProperty(FlightRuntime, 'typeofGlobal', cast (['document'] : Array<Dynamic>)), 'undefined'))) {
  FlightRuntime.callValue(resolve, cast ([null] : Array<Dynamic>));
  return;
}
  overlay = FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'createElement', cast (['div'] : Array<Dynamic>));
  FlightRuntime.setField(FlightRuntime.field(overlay, 'style'), 'cssText', 'position:fixed;inset:0;z-index:2147483646;');
  menu = FlightRuntime.callValue(Menu.buildWebMenuElement__menu, cast ([items, function(id:Dynamic) return FlightRuntime.callValue(close, cast ([id] : Array<Dynamic>))] : Array<Dynamic>));
  clampMenu = function clampMenu(el:Dynamic, anchorX:Float, anchorY:Float):Void {
  var rect:Dynamic = cast FlightRuntime.UNDEFINED;
  var vw:Dynamic = cast FlightRuntime.UNDEFINED;
  var vh:Dynamic = cast FlightRuntime.UNDEFINED;
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'left', '' + Std.string(anchorX) + 'px');
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'top', '' + Std.string(anchorY) + 'px');
  rect = FlightRuntime.callProperty(el, 'getBoundingClientRect', cast ([] : Array<Dynamic>));
  vw = FlightRuntime.select(!FlightRuntime.strictEquals(FlightRuntime.callProperty(FlightRuntime, 'typeofGlobal', cast (['window'] : Array<Dynamic>)), 'undefined'), function():Dynamic return cast FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['window'] : Array<Dynamic>)), 'innerWidth'), function():Dynamic return cast 0.0);
  vh = FlightRuntime.select(!FlightRuntime.strictEquals(FlightRuntime.callProperty(FlightRuntime, 'typeofGlobal', cast (['window'] : Array<Dynamic>)), 'undefined'), function():Dynamic return cast FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['window'] : Array<Dynamic>)), 'innerHeight'), function():Dynamic return cast 0.0);
  if (FlightRuntime.truthy(FlightRuntime.compare(FlightRuntime.field(rect, 'right'), vw, '>'))) { FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'left', '' + Std.string(FlightRuntime.callProperty(HxMath, 'max', cast ([0.0, (anchorX - FlightRuntime.field(rect, 'width'))] : Array<Dynamic>))) + 'px'); }
  if (FlightRuntime.truthy(FlightRuntime.compare(FlightRuntime.field(rect, 'bottom'), vh, '>'))) { FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'top', '' + Std.string(FlightRuntime.callProperty(HxMath, 'max', cast ([0.0, (anchorY - FlightRuntime.field(rect, 'height'))] : Array<Dynamic>))) + 'px'); }
};
  close = function close(selectedId:Null<String>):Void {
  FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'removeEventListener', cast (['keydown', onKeyDown] : Array<Dynamic>));
  FlightRuntime.callProperty(overlay, 'remove', cast ([] : Array<Dynamic>));
  FlightRuntime.callProperty(menu, 'remove', cast ([] : Array<Dynamic>));
  FlightRuntime.callValue(resolve, cast ([selectedId] : Array<Dynamic>));
};
  focusableItems = FlightRuntime.callProperty(menu, 'querySelectorAll', cast (['li[data-enabled="true"]'] : Array<Dynamic>));
  focusIndex = -1.0;
  moveFocus = function moveFocus(delta:Float):Void {
  var items:Dynamic = cast FlightRuntime.UNDEFINED;
  items = FlightRuntime.toArray(focusableItems);
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(items, 'length'), 0.0))) { return; }
  (focusIndex = cast ((((focusIndex + delta) + FlightRuntime.field(items, 'length')) % FlightRuntime.field(items, 'length')) : Dynamic));
  FlightRuntime.callProperty(items, 'forEach', cast ([function(el:Dynamic, i:Dynamic) {
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(i, focusIndex))) {
  FlightRuntime.callProperty(el, 'setAttribute', cast (['data-focused', 'true'] : Array<Dynamic>));
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'background', '#0066cc');
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'color', '#fff');
} else {
  FlightRuntime.callProperty(el, 'removeAttribute', cast (['data-focused'] : Array<Dynamic>));
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'background', '');
  FlightRuntime.setField(FlightRuntime.field(el, 'style'), 'color', '#111');
}
}] : Array<Dynamic>));
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(Menu._menuSignals__menu, null))) {
  var focused:Dynamic = FlightRuntime.getIndex(items, focusIndex);
  var itemId:Dynamic = FlightRuntime.optionalIndex(FlightRuntime.optionalField(focused, 'dataset'), 'itemId');
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(itemId, FlightRuntime.UNDEFINED))) { FlightRuntime.callValue(emitSignal, cast ([FlightRuntime.field(Menu._menuSignals__menu, 'onMenuItemHighlight'), itemId] : Array<Dynamic>)); }
}
};
  onKeyDown = function onKeyDown(e:Dynamic):Void {
  if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(e, 'key'), 'Escape'))) {
  FlightRuntime.callProperty(e, 'preventDefault', cast ([] : Array<Dynamic>));
  FlightRuntime.callValue(close, cast ([null] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(e, 'key'), 'ArrowDown'))) {
  FlightRuntime.callProperty(e, 'preventDefault', cast ([] : Array<Dynamic>));
  FlightRuntime.callValue(moveFocus, cast ([1.0] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(FlightRuntime.strictEquals(FlightRuntime.field(e, 'key'), 'ArrowUp'))) {
  FlightRuntime.callProperty(e, 'preventDefault', cast ([] : Array<Dynamic>));
  FlightRuntime.callValue(moveFocus, cast ([-1.0] : Array<Dynamic>));
} else { if (FlightRuntime.truthy(FlightRuntime.orValue(FlightRuntime.strictEquals(FlightRuntime.field(e, 'key'), 'Enter'), function():Dynamic return cast FlightRuntime.strictEquals(FlightRuntime.field(e, 'key'), ' ')))) {
  FlightRuntime.callProperty(e, 'preventDefault', cast ([] : Array<Dynamic>));
  var focused:Dynamic = FlightRuntime.getIndex(FlightRuntime.toArray(focusableItems), focusIndex);
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(focused, FlightRuntime.UNDEFINED))) {
  var itemId:Dynamic = FlightRuntime.getIndex(FlightRuntime.field(focused, 'dataset'), 'itemId');
  if (FlightRuntime.truthy(!FlightRuntime.strictEquals(itemId, FlightRuntime.UNDEFINED))) { FlightRuntime.callValue(close, cast ([itemId] : Array<Dynamic>)); }
}
} } } }
};
  FlightRuntime.callProperty(overlay, 'addEventListener', cast (['click', function() return FlightRuntime.callValue(close, cast ([null] : Array<Dynamic>))] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'addEventListener', cast (['keydown', onKeyDown] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'body'), 'appendChild', cast ([overlay] : Array<Dynamic>));
  FlightRuntime.callProperty(FlightRuntime.field(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['document'] : Array<Dynamic>)), 'body'), 'appendChild', cast ([menu] : Array<Dynamic>));
  FlightRuntime.callValue(clampMenu, cast ([menu, x, y] : Array<Dynamic>));
}]);
    return cast null;
  }

  @:keep public static function validateMenuItemTemplate(template:MenuItemTemplate):Null<String> {
    return cast FlightRuntime.callValue(Menu._validateItem__menu, cast ([template, FlightRuntime.construct(FlightRuntime.callProperty(FlightRuntime, 'globalValue', cast (['Set'] : Array<Dynamic>)), [])] : Array<Dynamic>));
    return cast null;
  }
}
