// Generated by flight-hx. Do not edit.
package flight;

import Math as HxMath;
import flight.internal.FlightRuntime;
import flight.Math.TAU;
import flight.Math.approxEqual;
import flight.Math.approxZero;
import flight.Types.Spring;
import flight.Types.Spring2D;
import flight.Types.Spring3D;
import flight.Types.SpringConfig;

#if js
@:build(jsasync.JSAsync.build())
#end
@:expose("flight.SpringApi")
class SpringApi {
  @:keep public static function createSpring(value:Float = 0.0, velocity:Float = 0.0):Spring {
    return cast { value: value, velocity: velocity };
    return cast null;
  }

  @:keep public static function createSpring2D(valueX:Float = 0.0, valueY:Float = 0.0, velocityX:Float = 0.0, velocityY:Float = 0.0):Spring2D {
    return cast { x: FlightRuntime.callValue(createSpring, cast ([valueX, velocityX] : Array<Dynamic>)), y: FlightRuntime.callValue(createSpring, cast ([valueY, velocityY] : Array<Dynamic>)) };
    return cast null;
  }

  @:keep public static function createSpring3D(valueX:Float = 0.0, valueY:Float = 0.0, valueZ:Float = 0.0, velocityX:Float = 0.0, velocityY:Float = 0.0, velocityZ:Float = 0.0):Spring3D {
    return cast { x: FlightRuntime.callValue(createSpring, cast ([valueX, velocityX] : Array<Dynamic>)), y: FlightRuntime.callValue(createSpring, cast ([valueY, velocityY] : Array<Dynamic>)), z: FlightRuntime.callValue(createSpring, cast ([valueZ, velocityZ] : Array<Dynamic>)) };
    return cast null;
  }

  @:keep public static function createSpringConfig(frequency:Float, dampingRatio:Float):SpringConfig {
    return cast { dampingRatio: dampingRatio, frequency: frequency };
    return cast null;
  }

  @:keep public static function createSpringConfigFromPhysical(stiffness:Float, damping:Float, mass:Float):SpringConfig {
    return cast { dampingRatio: (damping / (2.0 * FlightRuntime.callProperty(HxMath, 'sqrt', cast ([(stiffness * mass)] : Array<Dynamic>)))), frequency: (FlightRuntime.callProperty(HxMath, 'sqrt', cast ([(stiffness / mass)] : Array<Dynamic>)) / TAU) };
    return cast null;
  }

  public static final CRITICAL_BAND__updateSpring:Dynamic = 0.0001;

  @:keep public static function isSpring2DSettled(spring2D:Spring2D, targetX:Float, targetY:Float, ?positionEpsilon:Float, ?velocityEpsilon:Float):Bool {
    return cast FlightRuntime.andValue(FlightRuntime.callValue(isSpringSettled, cast ([FlightRuntime.field(spring2D, 'x'), targetX, positionEpsilon, velocityEpsilon] : Array<Dynamic>)), function():Dynamic return cast FlightRuntime.callValue(isSpringSettled, cast ([FlightRuntime.field(spring2D, 'y'), targetY, positionEpsilon, velocityEpsilon] : Array<Dynamic>)));
    return cast null;
  }

  @:keep public static function isSpring3DSettled(spring3D:Spring3D, targetX:Float, targetY:Float, targetZ:Float, ?positionEpsilon:Float, ?velocityEpsilon:Float):Bool {
    return cast FlightRuntime.andValue(FlightRuntime.andValue(FlightRuntime.callValue(isSpringSettled, cast ([FlightRuntime.field(spring3D, 'x'), targetX, positionEpsilon, velocityEpsilon] : Array<Dynamic>)), function():Dynamic return cast FlightRuntime.callValue(isSpringSettled, cast ([FlightRuntime.field(spring3D, 'y'), targetY, positionEpsilon, velocityEpsilon] : Array<Dynamic>))), function():Dynamic return cast FlightRuntime.callValue(isSpringSettled, cast ([FlightRuntime.field(spring3D, 'z'), targetZ, positionEpsilon, velocityEpsilon] : Array<Dynamic>)));
    return cast null;
  }

  @:keep public static function isSpringSettled(spring:Spring, target:Float, positionEpsilon:Float = 0.001, velocityEpsilon:Float = 0.001):Bool {
    return cast FlightRuntime.andValue(FlightRuntime.callValue(approxEqual, cast ([FlightRuntime.field(spring, 'value'), target, positionEpsilon] : Array<Dynamic>)), function():Dynamic return cast FlightRuntime.callValue(approxZero, cast ([FlightRuntime.field(spring, 'velocity'), velocityEpsilon] : Array<Dynamic>)));
    return cast null;
  }

  @:keep public static function resetSpring(spring:Spring, value:Float, velocity:Float = 0.0):Void {
    FlightRuntime.setField(spring, 'value', value);
    FlightRuntime.setField(spring, 'velocity', velocity);
  }

  public static final SPRING_SETTLE_EPSILON__isSpringSettled:Dynamic = 0.001;

  @:keep public static function updateSpring(spring:Spring, target:Float, config:SpringConfig, deltaTime:Float):Void {
    var frequency:Dynamic = cast FlightRuntime.UNDEFINED;
    var value:Dynamic = cast FlightRuntime.UNDEFINED;
    var velocity:Dynamic = cast FlightRuntime.UNDEFINED;
    var dampingRatio:Dynamic = cast FlightRuntime.UNDEFINED;
    var omega:Dynamic = cast FlightRuntime.UNDEFINED;
    var c0:Dynamic = cast FlightRuntime.UNDEFINED;
    var posPosCoef:Float = cast FlightRuntime.UNDEFINED;
    var posVelCoef:Float = cast FlightRuntime.UNDEFINED;
    var velPosCoef:Float = cast FlightRuntime.UNDEFINED;
    var velVelCoef:Float = cast FlightRuntime.UNDEFINED;
    if (FlightRuntime.truthy(FlightRuntime.compare(deltaTime, 0.0, '<='))) { return; }
    frequency = FlightRuntime.field(config, 'frequency');
    if (FlightRuntime.truthy(FlightRuntime.compare(frequency, 0.0, '<='))) { return; }
    value = FlightRuntime.field(spring, 'value');
    velocity = FlightRuntime.field(spring, 'velocity');
    dampingRatio = FlightRuntime.select(FlightRuntime.compare(FlightRuntime.field(config, 'dampingRatio'), 0.0, '<'), function():Dynamic return cast 0.0, function():Dynamic return cast FlightRuntime.field(config, 'dampingRatio'));
    omega = (TAU * frequency);
    c0 = (value - target);
    if (FlightRuntime.truthy(FlightRuntime.compare(dampingRatio, (1.0 + SpringApi.CRITICAL_BAND__updateSpring), '>'))) {
  var zb:Dynamic = (omega * FlightRuntime.callProperty(HxMath, 'sqrt', cast ([((dampingRatio * dampingRatio) - 1.0)] : Array<Dynamic>)));
  var za:Dynamic = (-omega * dampingRatio);
  var z1:Dynamic = (za - zb);
  var z2:Dynamic = (za + zb);
  var e1:Dynamic = FlightRuntime.callProperty(HxMath, 'exp', cast ([(z1 * deltaTime)] : Array<Dynamic>));
  var e2:Dynamic = FlightRuntime.callProperty(HxMath, 'exp', cast ([(z2 * deltaTime)] : Array<Dynamic>));
  var invDenominator:Dynamic = (1.0 / (z2 - z1));
  (posPosCoef = cast ((((z2 * e1) - (z1 * e2)) * invDenominator) : Dynamic));
  (posVelCoef = cast (((e2 - e1) * invDenominator) : Dynamic));
  (velPosCoef = cast ((((z1 * z2) * (e1 - e2)) * invDenominator) : Dynamic));
  (velVelCoef = cast ((((z2 * e2) - (z1 * e1)) * invDenominator) : Dynamic));
} else { if (FlightRuntime.truthy(FlightRuntime.compare(dampingRatio, (1.0 - SpringApi.CRITICAL_BAND__updateSpring), '<'))) {
  var alpha:Dynamic = (dampingRatio * omega);
  var beta:Dynamic = (omega * FlightRuntime.callProperty(HxMath, 'sqrt', cast ([(1.0 - (dampingRatio * dampingRatio))] : Array<Dynamic>)));
  var envelope:Dynamic = FlightRuntime.callProperty(HxMath, 'exp', cast ([(-alpha * deltaTime)] : Array<Dynamic>));
  var cosine:Dynamic = FlightRuntime.callProperty(HxMath, 'cos', cast ([(beta * deltaTime)] : Array<Dynamic>));
  var sine:Dynamic = FlightRuntime.callProperty(HxMath, 'sin', cast ([(beta * deltaTime)] : Array<Dynamic>));
  var invBeta:Dynamic = (1.0 / beta);
  (posPosCoef = cast ((envelope * (cosine + ((alpha * invBeta) * sine))) : Dynamic));
  (posVelCoef = cast (((envelope * invBeta) * sine) : Dynamic));
  (velPosCoef = cast (((((-envelope * omega) * omega) * invBeta) * sine) : Dynamic));
  (velVelCoef = cast ((envelope * (cosine - ((alpha * invBeta) * sine))) : Dynamic));
} else {
  var envelope:Dynamic = FlightRuntime.callProperty(HxMath, 'exp', cast ([(-omega * deltaTime)] : Array<Dynamic>));
  var omegaDt:Dynamic = (omega * deltaTime);
  (posPosCoef = cast ((envelope * (1.0 + omegaDt)) : Dynamic));
  (posVelCoef = cast ((envelope * deltaTime) : Dynamic));
  (velPosCoef = cast ((((-envelope * omega) * omega) * deltaTime) : Dynamic));
  (velVelCoef = cast ((envelope * (1.0 - omegaDt)) : Dynamic));
} }
    FlightRuntime.setField(spring, 'value', ((target + (posPosCoef * c0)) + (posVelCoef * velocity)));
    FlightRuntime.setField(spring, 'velocity', ((velPosCoef * c0) + (velVelCoef * velocity)));
  }

  @:keep public static function updateSpring2D(spring2D:Spring2D, targetX:Float, targetY:Float, config:SpringConfig, deltaTime:Float):Void {
    FlightRuntime.callValue(updateSpring, cast ([FlightRuntime.field(spring2D, 'x'), targetX, config, deltaTime] : Array<Dynamic>));
    FlightRuntime.callValue(updateSpring, cast ([FlightRuntime.field(spring2D, 'y'), targetY, config, deltaTime] : Array<Dynamic>));
  }

  @:keep public static function updateSpring3D(spring3D:Spring3D, targetX:Float, targetY:Float, targetZ:Float, config:SpringConfig, deltaTime:Float):Void {
    FlightRuntime.callValue(updateSpring, cast ([FlightRuntime.field(spring3D, 'x'), targetX, config, deltaTime] : Array<Dynamic>));
    FlightRuntime.callValue(updateSpring, cast ([FlightRuntime.field(spring3D, 'y'), targetY, config, deltaTime] : Array<Dynamic>));
    FlightRuntime.callValue(updateSpring, cast ([FlightRuntime.field(spring3D, 'z'), targetZ, config, deltaTime] : Array<Dynamic>));
  }
}
