// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.VideoApi;
function __syncDependencies() {}
__syncDependencies();

export const canPlayVideoType = api.canPlayVideoType;
export const detectVideoMimeType = api.detectVideoMimeType;
export const inferVideoMimeType = api.inferVideoMimeType;
export const selectVideoResourceUrl = api.selectVideoResourceUrl;
