// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Geolocation;
function __syncDependencies() {}
__syncDependencies();

export const clearGeolocationWatch = api.clearGeolocationWatch;
export const createGeoPosition = api.createGeoPosition;
export const createWebGeolocationBackend = api.createWebGeolocationBackend;
export const getCurrentGeoPosition = api.getCurrentGeoPosition;
export const getCurrentGeoPositionResult = api.getCurrentGeoPositionResult;
export const initializeGeoPosition = api.initializeGeoPosition;
export const initializeWebGeolocationBackend = api.initializeWebGeolocationBackend;
export const isGeolocationAvailable = api.isGeolocationAvailable;
export const watchGeolocationPosition = api.watchGeolocationPosition;
