// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._FontFormats;
function __syncDependencies() {}
__syncDependencies();

export const cffSubroutineBias = api.cffSubroutineBias;
export const runCffCharstring = api.runCffCharstring;
