// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.fontFormats.OpenTypeCmap;
function __syncDependencies() {}
__syncDependencies();

export const findOpenTypeUnicodeSubtable = api.findOpenTypeUnicodeSubtable;
export const rankOpenTypeUnicodeEncoding = api.rankOpenTypeUnicodeEncoding;
export const readOpenTypeCodepointMap = api.readOpenTypeCodepointMap;
