// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostElectron;
function __syncDependencies() {}
__syncDependencies();

export const createElectronDirectoryOpenDialogBackend = api.createElectronDirectoryOpenDialogBackend;
export const createElectronFileOpenDialogBackend = api.createElectronFileOpenDialogBackend;
export const createElectronFileSaveDialogBackend = api.createElectronFileSaveDialogBackend;
export const createElectronMessageDialogBackend = api.createElectronMessageDialogBackend;
