// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.HostElectron;
function __syncDependencies() {}
__syncDependencies();

export const createElectronWindowBackend = api.createElectronWindowBackend;
export const getApplicationWindowForElectronId = api.getApplicationWindowForElectronId;
export const getElectronBrowserWindow = api.getElectronBrowserWindow;
export const getElectronWindowId = api.getElectronWindowId;
