// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._HostElectron;
function __syncDependencies() {}
__syncDependencies();

export const initializeElectronHost = api.initializeElectronHost;
export const registerElectronBackends = api.registerElectronBackends;
