// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.displayobjectGl.GlDefaultMaterial;
function __syncDependencies() {}
__syncDependencies();

export const defaultGlMaterialRenderer = api.defaultGlMaterialRenderer;
export const registerDefaultGlMaterial = api.registerDefaultGlMaterial;
