// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.DisplayObjectGl;
function __syncDependencies() {}
__syncDependencies();

export const drawGlShapeMeshBatch = api.drawGlShapeMeshBatch;
export const drawGlShapeMeshes = api.drawGlShapeMeshes;
export const ensureGlShapeMeshProgram = api.ensureGlShapeMeshProgram;
