// Generated by flight-hx. Do not edit.

function __syncDependencies() {}
__syncDependencies();

export { defaultCanvasBeginFill as defaultGlBeginFill } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasBeginGradientFill as defaultGlBeginGradientFill } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasBeginTextureFill as defaultGlBeginTextureFill } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasCubicCurveTo as defaultGlCubicCurveTo } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasCurveTo as defaultGlCurveTo } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasDrawCircle as defaultGlDrawCircle } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasDrawEllipse as defaultGlDrawEllipse } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasDrawRectangle as defaultGlDrawRectangle } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasDrawRoundRectangle as defaultGlDrawRoundRectangle } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasEndFill as defaultGlEndFill } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasLineStyle as defaultGlLineStyle } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasLineTo as defaultGlLineTo } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasMoveTo as defaultGlMoveTo } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasShapeCommands as defaultGlShapeCommands } from '@flighthq/scene2d-canvas/contract';
export { defaultCanvasTextureShapeCommands as defaultGlTextureShapeCommands } from '@flighthq/scene2d-canvas/contract';
export { registerCanvasShapeCommands as registerGlShapeCommands } from '@flighthq/scene2d-canvas/contract';
