// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene2dGl.EnableGlStrokePathTessellation;
function __syncDependencies() {}
__syncDependencies();

export const enableGlStrokePathTessellation = api.enableGlStrokePathTessellation;
