// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/node/contract';
import * as __dependency1 from '@flighthq/textlayout/contract';

const api = compiled.flight._Scene2DGl;
function __syncDependencies() {
  compiled.flight._Node.getNodeLocalContentRevision = __dependency0.getNodeLocalContentRevision;
  compiled.flight._TextLayout.computeTextLayout = __dependency1.computeTextLayout;
}
__syncDependencies();

export const defaultGlTextLabelRenderer = api.defaultGlTextLabelRenderer;
const __bridgeImplementation_drawGlTextLabel = api.drawGlTextLabel;
export function drawGlTextLabel(...args) { __syncDependencies(); const result = __bridgeImplementation_drawGlTextLabel(...args); return result; }
api.drawGlTextLabel = drawGlTextLabel;
compiled.flight.Scene2DGl.drawGlTextLabel = drawGlTextLabel;
api.defaultGlTextLabelRenderer["submit"] = drawGlTextLabel;
