// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dFormats.Awd2Inflate;
function __syncDependencies() {}
__syncDependencies();

export const inflateAwdDeflate = api.inflateAwdDeflate;
export const registerAwd2DeflateDecompressor = api.registerAwd2DeflateDecompressor;
