// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Scene3DFormats;
function __syncDependencies() {}
__syncDependencies();

export const findScene3DSkeletonJoints = api.findScene3DSkeletonJoints;
