// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dGl.DepthGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const depthGlMeshMaterialRenderer = api.depthGlMeshMaterialRenderer;
export const registerGlDepthMaterial = api.registerGlDepthMaterial;
