// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dGl.GlParticleEmitter3D;
function __syncDependencies() {}
__syncDependencies();

export const destroyGlParticleEmitter3DShader = api.destroyGlParticleEmitter3DShader;
export const drawGlScene3DParticleEmitter3Ds = api.drawGlScene3DParticleEmitter3Ds;
