// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.abc.AbcInstruction;
function __syncDependencies() {}
__syncDependencies();

export const readAbcInstructions = api.readAbcInstructions;
