// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene2dFormats.LottieDocument;
function __syncDependencies() {}
__syncDependencies();

export const applyAnimationClipToLottieDocument = api.applyAnimationClipToLottieDocument;
export const createScene2DFromLottieDocument = api.createScene2DFromLottieDocument;
