// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Gizmo;
function __syncDependencies() {}
__syncDependencies();

export const computeGizmoAlignmentDeltas = api.computeGizmoAlignmentDeltas;
export const findGizmoSmartGuides = api.findGizmoSmartGuides;
