// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.TextureApi;
function __syncDependencies() {}
__syncDependencies();

export const cloneTexture = api.cloneTexture;
export const copyTexture = api.copyTexture;
export const createTexture = api.createTexture;
export const equalsTexture = api.equalsTexture;
export const getTextureHeight = api.getTextureHeight;
export const getTextureInverseUvMatrix = api.getTextureInverseUvMatrix;
export const getTextureUvMatrix = api.getTextureUvMatrix;
export const getTextureWidth = api.getTextureWidth;
export const hasTextureUvTransform = api.hasTextureUvTransform;
export const isTextureReady = api.isTextureReady;
export const resetTextureUvTransform = api.resetTextureUvTransform;
export const setTextureImage = api.setTextureImage;
export const setTextureUvOffset = api.setTextureUvOffset;
export const setTextureUvRotation = api.setTextureUvRotation;
export const setTextureUvScale = api.setTextureUvScale;
export const transformTextureUv = api.transformTextureUv;
