// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.TextureApi;
function __syncDependencies() {}
__syncDependencies();

export const advanceVideoTexture = api.advanceVideoTexture;
export const cloneVideoTexture = api.cloneVideoTexture;
export const copyVideoTexture = api.copyVideoTexture;
export const createVideoTexture = api.createVideoTexture;
export const getVideoTextureHeight = api.getVideoTextureHeight;
export const getVideoTextureInverseUvMatrix = api.getVideoTextureInverseUvMatrix;
export const getVideoTextureUvMatrix = api.getVideoTextureUvMatrix;
export const getVideoTextureWidth = api.getVideoTextureWidth;
export const isVideoTextureFrameReady = api.isVideoTextureFrameReady;
export const resetVideoTextureFrame = api.resetVideoTextureFrame;
export const setVideoTextureSource = api.setVideoTextureSource;
