// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight.ParticleEmitterApi;
function __syncDependencies() {}
__syncDependencies();

export const prewarmParticleEmitter = api.prewarmParticleEmitter;
