// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.particleemitter.UpdateParticleEmitter2D;
function __syncDependencies() {}
__syncDependencies();

export const isParticleEmitter2DComplete = api.isParticleEmitter2DComplete;
export const updateParticleEmitter2D = api.updateParticleEmitter2D;
