// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Accessibility;
function __syncDependencies() {}
__syncDependencies();

export const announceAccessibility = api.announceAccessibility;
export const clearAccessibilityTree = api.clearAccessibilityTree;
export const createWebAccessibilityBackend = api.createWebAccessibilityBackend;
export const explainAccessibilityBackend = api.explainAccessibilityBackend;
export const getAccessibilityBackend = api.getAccessibilityBackend;
export const installAccessibilityHostBackend = api.installAccessibilityHostBackend;
export const observeAccessibilityHostResult = api.observeAccessibilityHostResult;
export const removeAccessibilityNode = api.removeAccessibilityNode;
export const resetAccessibilityBackendForTest = api.resetAccessibilityBackendForTest;
export const setAccessibilityBackend = api.setAccessibilityBackend;
export const setAccessibilityFocus = api.setAccessibilityFocus;
export const setAccessibilityNode = api.setAccessibilityNode;
