// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Accessibility;
function __syncDependencies() {}
__syncDependencies();

export const announceAccessibility = api.announceAccessibility;
export const clearAccessibilityTree = api.clearAccessibilityTree;
export const destroyAccessibility = api.destroyAccessibility;
export const removeAccessibilityNode = api.removeAccessibilityNode;
export const setAccessibilityFocus = api.setAccessibilityFocus;
export const setAccessibilityNode = api.setAccessibilityNode;
