// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Media;
function __syncDependencies() {}
__syncDependencies();

export const enableAudioChannelSignals = api.enableAudioChannelSignals;
export const enableVideoChannelSignals = api.enableVideoChannelSignals;
export const getAudioChannelSignals = api.getAudioChannelSignals;
export const getVideoChannelSignals = api.getVideoChannelSignals;
