// Skunkworks bindings backend: flight-compiler inventory -> Haxe ESM externs + flight.* forwarders.
//
// Pure(ish) driver, mirroring flight-cpp/scripts/sdkGeneration.mjs: it does NOT re-derive names or
// parse TypeScript itself — it lowers Flight source through @flighthq/tool-compiler and reads the IR
// (signatures, type shapes, export names). Bodies are ignored (externs have none). Output is the
// checked-in `flight._js` backing + the backend-agnostic public unifiers.
//
// Scope: currently one slice (geometry Vector2). Unmappable signatures are SKIPPED and reported, so
// the emitted surface always compiles. This is the ESM half of the bindings backend that AGENTS.md
// says promotes upstream to compiler-backend-hx once its shape settles.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolveDependency } from '../../scripts/dependencyLock.mjs';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const flight = resolveDependency(repoRoot, 'flight');
const compiler = resolveDependency(repoRoot, 'flight-compiler');
const compilerEntry = join(
  compiler.directory,
  'packages/tool-compiler/dist/packages/tool-compiler/src/index.js',
);

let tc;
try {
  tc = await import(pathToFileURL(compilerEntry).href);
} catch (error) {
  console.error(`Cannot load @flighthq/tool-compiler at ${compilerEntry}`);
  console.error('Build it first: (cd .dependencies/flight-compiler && npm install && npm run build)');
  console.error(String(error?.message ?? error));
  process.exit(1);
}

// --- the slice to generate -------------------------------------------------
// One function module (geometry) + the type module that defines its value type.
const TYPES = { package: '@flighthq/types', file: 'packages/types/src/Vector2.ts' };
const MODULES = [
  { package: '@flighthq/geometry', specifier: '@flighthq/geometry', file: 'packages/geometry/src/vector2.ts', hxModule: 'Geom' },
];

// --- IR type -> Haxe type --------------------------------------------------
class Unmappable extends Error {}
function mapType(t) {
  if (!t || typeof t !== 'object') throw new Unmappable('missing type');
  if (t.kind === 'primitive') {
    switch (t.name) {
      case 'void': return 'Void';
      case 'number': return 'Float';
      case 'boolean': return 'Bool';
      case 'string': return 'String';
      default: throw new Unmappable(`primitive ${t.name}`);
    }
  }
  if (t.kind === 'named') {
    const ref = t.reference ?? {};
    if (ref.kind === 'ambient' && ref.name === 'Readonly') return mapType(t.typeArguments?.[0]);
    const name = ref.binding?.name ?? (ref.kind === 'ambient' ? ref.name : undefined);
    if (name === 'Vector2' || name === 'Vector2Like') return 'flight.Vector2';
    throw new Unmappable(`named ${name ?? ref.kind}`);
  }
  throw new Unmappable(`kind ${t.kind}`);
}

function lower(entry) {
  const path = join(flight.directory, entry.file);
  const sf = tc.parseTypeScriptSource(path, readFileSync(path, 'utf8'));
  return tc.lowerTypeScriptSource(sf, { packageName: entry.package, upstreamDirectory: flight.directory }).module;
}

function collectFunctions(mod) {
  const kept = [];
  const skipped = [];
  for (const d of mod.declarations) {
    if (d.kind !== 'function' || d.exported !== true) continue;
    try {
      const params = d.parameters.map((p) => {
        if (p.rest) throw new Unmappable('rest param');
        return { name: p.binding.name, type: mapType(p.type), optional: Boolean(p.optional) };
      });
      kept.push({ name: d.binding.name, params, returns: mapType(d.returns) });
    } catch (error) {
      if (error instanceof Unmappable) skipped.push({ name: d.binding?.name, reason: error.message });
      else throw error;
    }
  }
  kept.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return { kept, skipped };
}

const header = (from) =>
  `// Generated by tools/backend-hx from ${from} at flight@${flight.commit.slice(0, 12)}. Do not edit.\n`;
const sig = (f) => `${f.name}(${f.params.map((p) => `${p.optional ? '?' : ''}${p.name}:${p.type}`).join(', ')}):${f.returns}`;

// --- emitters --------------------------------------------------------------
function emitJsBackingType() {
  // Vector2 is structural {x,y} on JS (a plain object; a real Flight Vector2 also carries a hidden
  // EntityRuntime symbol slot, which structural binding neither needs nor sees).
  return `${header(`${TYPES.package}/${TYPES.file}`)}#if js
package flight._js;

typedef Vector2 = {
  var x:Float;
  var y:Float;
}
#end
`;
}

function emitJsBackingModule(mod, fns) {
  const methods = fns.map((f) => `  static function ${sig(f)};`).join('\n');
  return `${header(`${mod.package}/${mod.file}`)}#if js
package flight._js;

// Named ESM exports of ${mod.specifier}, bound as extern statics. @:jsRequire without a member name
// binds each static to the module's like-named named export (require("${mod.specifier}").<name>);
// the vendored ESM generator (tools/esm) later turns that into a static import for tree-shaking.
@:jsRequire("${mod.specifier}")
extern class ${mod.hxModule} {
${methods}
}
#end
`;
}

function emitPublicType() {
  return `${header(`${TYPES.package}/${TYPES.file}`)}package flight;

#if flight_hx
typedef Vector2 = flight._hx.Vector2;
#elseif (js && flight_esm)
typedef Vector2 = flight._js.Vector2;
#elseif cpp
typedef Vector2 = flight._cpp.Vector2;
#elseif js
#error "flight on js: define flight_esm for the hostWeb ESM pipeline, or flight_hx for the transpiled fallback."
#else
#error "flight: no backend for this target — define flight_hx, or target cpp / (js + flight_esm)."
#end
`;
}

function emitPublicModule(mod, fns) {
  const fwd = (f) => {
    const call = `flight._%B%.${mod.hxModule}.${f.name}(${f.params.map((p) => p.name).join(', ')})`;
    const ret = f.returns === 'Void' ? '' : 'return ';
    return `inline function ${sig(f)} {
  #if flight_hx
  ${ret}${call.replace('%B%', 'hx')};
  #elseif (js && flight_esm)
  ${ret}${call.replace('%B%', 'js')};
  #elseif cpp
  ${ret}${call.replace('%B%', 'cpp')};
  #else
  #error "flight.${mod.hxModule}: no backend — define flight_hx, or js+flight_esm, or target cpp.";
  #end
}`;
  };
  return `${header(`${mod.package}/${mod.file}`)}package flight;

${fns.map(fwd).join('\n\n')}
`;
}

// --- run -------------------------------------------------------------------
const outPublic = join(repoRoot, 'generated');
const outJs = join(repoRoot, 'generated/js');
rmSync(join(outPublic, 'flight'), { recursive: true, force: true });
rmSync(join(outJs, 'flight'), { recursive: true, force: true });

function write(base, rel, contents) {
  const target = join(base, rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
  return target;
}

const wrote = [];
const allSkipped = [];
wrote.push(write(outJs, 'flight/_js/Vector2.hx', emitJsBackingType()));
wrote.push(write(outPublic, 'flight/Vector2.hx', emitPublicType()));
for (const entry of MODULES) {
  const mod = lower(entry);
  const { kept, skipped } = collectFunctions(mod);
  allSkipped.push(...skipped.map((s) => ({ module: entry.hxModule, ...s })));
  wrote.push(write(outJs, `flight/_js/${entry.hxModule}.hx`, emitJsBackingModule(entry, kept)));
  wrote.push(write(outPublic, `flight/${entry.hxModule}.hx`, emitPublicModule(entry, kept)));
  console.log(`${entry.hxModule}: ${kept.length} functions bound, ${skipped.length} skipped (unmappable types)`);
}
console.log(`\nwrote ${wrote.length} files:`);
for (const w of wrote) console.log('  ' + w.replace(repoRoot + '/', ''));
if (allSkipped.length) {
  console.log(`\nskipped (out of scope for this slice's type mapping):`);
  for (const s of allSkipped) console.log(`  ${s.module}.${s.name} — ${s.reason}`);
}
