// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.physics3d.ExplainPhysics3DCollision;
function __syncDependencies() {}
__syncDependencies();

export const explainPhysics3DCollision = api.explainPhysics3DCollision;
