// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.physics3d.Physics3DBroadphasePublication;
function __syncDependencies() {}
__syncDependencies();

export const getPhysics3DBroadphaseBodyIndices = api.getPhysics3DBroadphaseBodyIndices;
export const publishPhysics3DBroadphaseBody = api.publishPhysics3DBroadphaseBody;
export const withdrawPhysics3DBroadphaseBody = api.withdrawPhysics3DBroadphaseBody;
