// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dWgpu.ExplainWgpuScene3DCoverage;
function __syncDependencies() {}
__syncDependencies();

export const explainWgpuScene3DCoverage = api.explainWgpuScene3DCoverage;
export const hasWgpuScene3DCoverage = api.hasWgpuScene3DCoverage;
