// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Scene3DWgpu;
function __syncDependencies() {}
__syncDependencies();

export const getWgpuShadedBaseFlags = api.getWgpuShadedBaseFlags;
export const registerWgpuShadedMaterial = api.registerWgpuShadedMaterial;
export const shadedWgpuMeshMaterialRenderer = api.shadedWgpuMeshMaterialRenderer;
