// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.scene3dWgpu.WgpuSkinPalette;
function __syncDependencies() {}
__syncDependencies();

export const destroyWgpuSkinPalette = api.destroyWgpuSkinPalette;
export const ensureWgpuSkinDrawBindGroup = api.ensureWgpuSkinDrawBindGroup;
export const ensureWgpuSkinDrawLayout = api.ensureWgpuSkinDrawLayout;
export const ensureWgpuSkinMeshDrawBindGroup = api.ensureWgpuSkinMeshDrawBindGroup;
export const ensureWgpuSkinMeshDrawLayout = api.ensureWgpuSkinMeshDrawLayout;
export const registerWgpuGpuSkinning = api.registerWgpuGpuSkinning;
export const uploadWgpuSkinNormalPalette = api.uploadWgpuSkinNormalPalette;
export const uploadWgpuSkinPalette = api.uploadWgpuSkinPalette;
