// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Tokens;
function __syncDependencies() {}
__syncDependencies();

export const INVALID_FLIGHT_DOCUMENT_TOKEN_VALUE = api.INVALID_FLIGHT_DOCUMENT_TOKEN_VALUE;
export const isFlightDocumentTokenReference = api.isFlightDocumentTokenReference;
export const readFlightDocumentTokenReferenceKey = api.readFlightDocumentTokenReferenceKey;
export const substituteFlightDocumentTokenValue = api.substituteFlightDocumentTokenValue;
