// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/node';

const api = compiled.flight.DisplayObjectWgpu;
function __syncDependencies() {
  compiled.flight.NodeApi.getNodeLocalBoundsRectangle = __dependency0.getNodeLocalBoundsRectangle;
  compiled.flight.NodeApi.getNodeLocalContentRevision = __dependency0.getNodeLocalContentRevision;
}
__syncDependencies();

export const defaultWgpuShapeRenderer = api.defaultWgpuShapeRenderer;
export const drawWgpuShape = api.drawWgpuShape;
