// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.TextLayout;
function __syncDependencies() {}
__syncDependencies();

export const createTextMetrics = api.createTextMetrics;
export const getTextMetrics = api.getTextMetrics;
