// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneGl.EmissiveGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const emissiveGlMeshMaterialRenderer = api.emissiveGlMeshMaterialRenderer;
export const registerEmissiveGlMaterial = api.registerEmissiveGlMaterial;
