// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.SceneGl;
function __syncDependencies() {}
__syncDependencies();

export const compileGlPbrProgram = api.compileGlPbrProgram;
export const ensureGlPbrProgram = api.ensureGlPbrProgram;
