// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneGl.LambertGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const lambertGlMeshMaterialRenderer = api.lambertGlMeshMaterialRenderer;
export const registerLambertGlMaterial = api.registerLambertGlMaterial;
