// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneGl.PhongGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const phongGlMeshMaterialRenderer = api.phongGlMeshMaterialRenderer;
export const registerPhongGlMaterial = api.registerPhongGlMaterial;
