// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneGl.ShadedGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const registerShadedGlMaterial = api.registerShadedGlMaterial;
export const shadedGlMeshMaterialRenderer = api.shadedGlMeshMaterialRenderer;
