// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.sceneGl.SubsurfacePbrGlMeshMaterialRenderer;
function __syncDependencies() {}
__syncDependencies();

export const registerSubsurfacePbrGlMaterial = api.registerSubsurfacePbrGlMaterial;
export const subsurfacePbrGlMeshMaterialRenderer = api.subsurfacePbrGlMeshMaterialRenderer;
