// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.shape.ExplainShapeTessellation;
function __syncDependencies() {}
__syncDependencies();

export const explainShapeTessellation = api.explainShapeTessellation;
