// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._Shape;
function __syncDependencies() {}
__syncDependencies();

export const appendShapeGeometryCommand = api.appendShapeGeometryCommand;
export const getPathCommandOperandCount = api.getPathCommandOperandCount;
export const getShapeFillRegions = api.getShapeFillRegions;
export const hasNonSolidShapeFill = api.hasNonSolidShapeFill;
export const hasShapeFill = api.hasShapeFill;
