// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.shape.ShapeBounds;
function __syncDependencies() {}
__syncDependencies();

export const computeShapeBoundsRectangle = api.computeShapeBoundsRectangle;
export const defaultShapeBoundsCubicCurveTo = api.defaultShapeBoundsCubicCurveTo;
export const defaultShapeBoundsCurveTo = api.defaultShapeBoundsCurveTo;
export const defaultShapeBoundsDrawCircle = api.defaultShapeBoundsDrawCircle;
export const defaultShapeBoundsDrawEllipse = api.defaultShapeBoundsDrawEllipse;
export const defaultShapeBoundsDrawPath = api.defaultShapeBoundsDrawPath;
export const defaultShapeBoundsDrawRectangle = api.defaultShapeBoundsDrawRectangle;
export const defaultShapeBoundsExpandPointPairs = api.defaultShapeBoundsExpandPointPairs;
export const defaultShapeBoundsFlush = api.defaultShapeBoundsFlush;
export const defaultShapeBoundsLineStyle = api.defaultShapeBoundsLineStyle;
export const defaultShapeBoundsLineTo = api.defaultShapeBoundsLineTo;
export const defaultShapeBoundsMoveTo = api.defaultShapeBoundsMoveTo;
export const explainShapeBounds = api.explainShapeBounds;
export const normalizeShapeStrokeMiterLimit = api.normalizeShapeStrokeMiterLimit;
export const normalizeShapeStrokeWidth = api.normalizeShapeStrokeWidth;
export const setShapeBoundsGuard = api.setShapeBoundsGuard;
