// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsCanvas.CanvasEffectCompositing;
function __syncDependencies() {}
__syncDependencies();

export const drawCanvasAccumulationPass = api.drawCanvasAccumulationPass;
export const drawCanvasEffectPass = api.drawCanvasEffectPass;
export const drawCanvasImageDataPass = api.drawCanvasImageDataPass;
export const passthroughCanvasEffectPass = api.passthroughCanvasEffectPass;
