// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsCanvas.CanvasLensDistortionEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyLensDistortionEffectToCanvas = api.applyLensDistortionEffectToCanvas;
export const defaultCanvasLensDistortionEffectRunner = api.defaultCanvasLensDistortionEffectRunner;
