// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsCanvas.CanvasConvolutionEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyConvolutionEffectToCanvas = api.applyConvolutionEffectToCanvas;
export const defaultCanvasConvolutionEffectRunner = api.defaultCanvasConvolutionEffectRunner;
