// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './canvasEffectCompositing.mjs';
import * as __dependency1 from './canvasRenderEffectPipeline.mjs';
import * as __dependency2 from './canvasSourceModeCompositing.mjs';

const api = compiled.flight._EffectsCanvas;
function __syncDependencies() {
  compiled.flight._EffectsCanvas.drawCanvasEffectPass = __dependency0.drawCanvasEffectPass;
  compiled.flight._EffectsCanvas.acquireCanvasRenderTarget = __dependency1.acquireCanvasRenderTarget;
  compiled.flight._EffectsCanvas.createCanvasRenderTargetPool = __dependency1.createCanvasRenderTargetPool;
  compiled.flight._EffectsCanvas.releaseCanvasRenderTarget = __dependency1.releaseCanvasRenderTarget;
  compiled.flight._EffectsCanvas.clearCanvasTarget = __dependency2.clearCanvasTarget;
  compiled.flight._EffectsCanvas.compositeCanvasImage = __dependency2.compositeCanvasImage;
}
__syncDependencies();

const __bridgeImplementation_applyGradientGlowEffectToCanvas = api.applyGradientGlowEffectToCanvas;
export function applyGradientGlowEffectToCanvas(...args) { __syncDependencies(); const result = __bridgeImplementation_applyGradientGlowEffectToCanvas(...args); return result; }
api.applyGradientGlowEffectToCanvas = applyGradientGlowEffectToCanvas;
compiled.flight.EffectsCanvas.applyGradientGlowEffectToCanvas = applyGradientGlowEffectToCanvas;
const __bridgeImplementation_defaultCanvasGradientGlowEffectRunner = api.defaultCanvasGradientGlowEffectRunner;
export function defaultCanvasGradientGlowEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultCanvasGradientGlowEffectRunner(...args); }
api.defaultCanvasGradientGlowEffectRunner = defaultCanvasGradientGlowEffectRunner;
const __bridgeImplementation_registerCanvasGradientGlowEffect = api.registerCanvasGradientGlowEffect;
export function registerCanvasGradientGlowEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerCanvasGradientGlowEffect(...args); return result; }
api.registerCanvasGradientGlowEffect = registerCanvasGradientGlowEffect;
compiled.flight.EffectsCanvas.registerCanvasGradientGlowEffect = registerCanvasGradientGlowEffect;
