// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './canvasEffectCompositing.mjs';
import * as __dependency1 from './canvasRenderEffectPipeline.mjs';
import * as __dependency2 from './canvasSourceModeCompositing.mjs';

const api = compiled.flighthq.EffectsCanvas;
function __syncDependencies() {
  compiled.flighthq.EffectsCanvas.drawCanvasEffectPass = __dependency0.drawCanvasEffectPass;
  compiled.flighthq.EffectsCanvas.acquireCanvasRenderTarget = __dependency1.acquireCanvasRenderTarget;
  compiled.flighthq.EffectsCanvas.createCanvasRenderTargetPool = __dependency1.createCanvasRenderTargetPool;
  compiled.flighthq.EffectsCanvas.releaseCanvasRenderTarget = __dependency1.releaseCanvasRenderTarget;
  compiled.flighthq.EffectsCanvas.clearCanvasTarget = __dependency2.clearCanvasTarget;
  compiled.flighthq.EffectsCanvas.compositeCanvasImage = __dependency2.compositeCanvasImage;
  compiled.flighthq.EffectsCanvas.compositeCanvasSourceMode = __dependency2.compositeCanvasSourceMode;
  compiled.flighthq.EffectsCanvas.drawCanvasTintedAlphaMask = __dependency2.drawCanvasTintedAlphaMask;
}
__syncDependencies();

export const applyOuterGlowEffectToCanvas = api.applyOuterGlowEffectToCanvas;
export const defaultCanvasOuterGlowEffectRunner = api.defaultCanvasOuterGlowEffectRunner;
