// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './canvasEffectCompositing.mjs';

const api = compiled.flight._EffectsCanvas;
function __syncDependencies() {
  compiled.flight._EffectsCanvas.drawCanvasEffectPass = __dependency0.drawCanvasEffectPass;
}
__syncDependencies();

const __bridgeImplementation_applyBlurEffectToCanvas = api.applyBlurEffectToCanvas;
export function applyBlurEffectToCanvas(...args) { __syncDependencies(); const result = __bridgeImplementation_applyBlurEffectToCanvas(...args); return result; }
api.applyBlurEffectToCanvas = applyBlurEffectToCanvas;
compiled.flight.EffectsCanvas.applyBlurEffectToCanvas = applyBlurEffectToCanvas;
const __bridgeImplementation_defaultCanvasBlurEffectRunner = api.defaultCanvasBlurEffectRunner;
export function defaultCanvasBlurEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultCanvasBlurEffectRunner(...args); }
api.defaultCanvasBlurEffectRunner = defaultCanvasBlurEffectRunner;
const __bridgeImplementation_registerCanvasBlurEffect = api.registerCanvasBlurEffect;
export function registerCanvasBlurEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerCanvasBlurEffect(...args); return result; }
api.registerCanvasBlurEffect = registerCanvasBlurEffect;
compiled.flight.EffectsCanvas.registerCanvasBlurEffect = registerCanvasBlurEffect;
