// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './canvasEffectCompositing.mjs';
import * as __dependency1 from './canvasRenderEffectPipeline.mjs';

const api = compiled.flight._EffectsCanvas;
function __syncDependencies() {
  compiled.flight._EffectsCanvas.drawCanvasEffectPass = __dependency0.drawCanvasEffectPass;
  compiled.flight._EffectsCanvas.acquireCanvasRenderTarget = __dependency1.acquireCanvasRenderTarget;
  compiled.flight._EffectsCanvas.releaseCanvasRenderTarget = __dependency1.releaseCanvasRenderTarget;
}
__syncDependencies();

const __bridgeImplementation_applyFilmGrainEffectToCanvas = api.applyFilmGrainEffectToCanvas;
export function applyFilmGrainEffectToCanvas(...args) { __syncDependencies(); const result = __bridgeImplementation_applyFilmGrainEffectToCanvas(...args); return result; }
api.applyFilmGrainEffectToCanvas = applyFilmGrainEffectToCanvas;
compiled.flight.EffectsCanvas.applyFilmGrainEffectToCanvas = applyFilmGrainEffectToCanvas;
const __bridgeImplementation_defaultCanvasFilmGrainEffectRunner = api.defaultCanvasFilmGrainEffectRunner;
export function defaultCanvasFilmGrainEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultCanvasFilmGrainEffectRunner(...args); }
api.defaultCanvasFilmGrainEffectRunner = defaultCanvasFilmGrainEffectRunner;
const __bridgeImplementation_registerCanvasFilmGrainEffect = api.registerCanvasFilmGrainEffect;
export function registerCanvasFilmGrainEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerCanvasFilmGrainEffect(...args); return result; }
api.registerCanvasFilmGrainEffect = registerCanvasFilmGrainEffect;
compiled.flight.EffectsCanvas.registerCanvasFilmGrainEffect = registerCanvasFilmGrainEffect;
