// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.EffectsCanvas;
function __syncDependencies() {}
__syncDependencies();

export const applyGodRaysEffectToCanvas = api.applyGodRaysEffectToCanvas;
export const defaultCanvasGodRaysEffectRunner = api.defaultCanvasGodRaysEffectRunner;
