// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsCanvas.CanvasGradientGlowEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyGradientGlowEffectToCanvas = api.applyGradientGlowEffectToCanvas;
export const defaultCanvasGradientGlowEffectRunner = api.defaultCanvasGradientGlowEffectRunner;
export const registerCanvasGradientGlowEffect = api.registerCanvasGradientGlowEffect;
