// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsCanvas.CanvasInnerGlowEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyInnerGlowEffectToCanvas = api.applyInnerGlowEffectToCanvas;
export const defaultCanvasInnerGlowEffectRunner = api.defaultCanvasInnerGlowEffectRunner;
export const registerCanvasInnerGlowEffect = api.registerCanvasInnerGlowEffect;
