// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.net.Net;
function __syncDependencies() {}
__syncDependencies();

export const createWebNetBackend = api.createWebNetBackend;
export const getNetBackend = api.getNetBackend;
export const sendNetRequest = api.sendNetRequest;
export const setNetBackend = api.setNetBackend;
