// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.EffectsGl;
function __syncDependencies() {}
__syncDependencies();

export const applyBlendEffectToGl = api.applyBlendEffectToGl;
export const defaultGlBlendEffectRunner = api.defaultGlBlendEffectRunner;
export const getBlendEffectModeIndex = api.getBlendEffectModeIndex;
export const getGlBlendEffectBackdrop = api.getGlBlendEffectBackdrop;
export const registerGlBlendEffectBackdrop = api.registerGlBlendEffectBackdrop;
export const unregisterGlBlendEffectBackdrop = api.unregisterGlBlendEffectBackdrop;
