// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyCameraMotionBlurEffectToGl = api.applyCameraMotionBlurEffectToGl;
export function applyCameraMotionBlurEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyCameraMotionBlurEffectToGl(...args); return result; }
api.applyCameraMotionBlurEffectToGl = applyCameraMotionBlurEffectToGl;
compiled.flight.EffectsGl.applyCameraMotionBlurEffectToGl = applyCameraMotionBlurEffectToGl;
const __bridgeImplementation_defaultGlCameraMotionBlurEffectRunner = api.defaultGlCameraMotionBlurEffectRunner;
export function defaultGlCameraMotionBlurEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlCameraMotionBlurEffectRunner(...args); }
api.defaultGlCameraMotionBlurEffectRunner = defaultGlCameraMotionBlurEffectRunner;
const __bridgeImplementation_registerGlCameraMotionBlurEffect = api.registerGlCameraMotionBlurEffect;
export function registerGlCameraMotionBlurEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlCameraMotionBlurEffect(...args); return result; }
api.registerGlCameraMotionBlurEffect = registerGlCameraMotionBlurEffect;
compiled.flight.EffectsGl.registerGlCameraMotionBlurEffect = registerGlCameraMotionBlurEffect;
