// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyColorMatrixPassToGl = api.applyColorMatrixPassToGl;
export function applyColorMatrixPassToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyColorMatrixPassToGl(...args); return result; }
api.applyColorMatrixPassToGl = applyColorMatrixPassToGl;
compiled.flight.EffectsGl.applyColorMatrixPassToGl = applyColorMatrixPassToGl;
