// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {}
__syncDependencies();

export const applyContactShadowsEffectToGl = api.applyContactShadowsEffectToGl;
export const defaultGlContactShadowsEffectRunner = api.defaultGlContactShadowsEffectRunner;
export const registerGlContactShadowsEffect = api.registerGlContactShadowsEffect;
