// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {}
__syncDependencies();

export const applyCrtEffectToGl = api.applyCrtEffectToGl;
export const defaultGlCrtEffectRunner = api.defaultGlCrtEffectRunner;
export const registerGlCrtEffect = api.registerGlCrtEffect;
