// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

export function applyDirectionalBlurEffectToGl(...args) { __syncDependencies(); const result = api.applyDirectionalBlurEffectToGl(...args); return result; }
const __bridgeImplementation_defaultGlDirectionalBlurEffectRunner = api.defaultGlDirectionalBlurEffectRunner;
export function defaultGlDirectionalBlurEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlDirectionalBlurEffectRunner(...args); }
api.defaultGlDirectionalBlurEffectRunner = defaultGlDirectionalBlurEffectRunner;
export function registerGlDirectionalBlurEffect(...args) { __syncDependencies(); const result = api.registerGlDirectionalBlurEffect(...args); return result; }
