// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyDisplacementEffectToGl = api.applyDisplacementEffectToGl;
export function applyDisplacementEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyDisplacementEffectToGl(...args); return result; }
api.applyDisplacementEffectToGl = applyDisplacementEffectToGl;
compiled.flight.EffectsGl.applyDisplacementEffectToGl = applyDisplacementEffectToGl;
const __bridgeImplementation_defaultGlDisplacementEffectRunner = api.defaultGlDisplacementEffectRunner;
export function defaultGlDisplacementEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlDisplacementEffectRunner(...args); }
api.defaultGlDisplacementEffectRunner = defaultGlDisplacementEffectRunner;
const __bridgeImplementation_registerGlDisplacementEffect = api.registerGlDisplacementEffect;
export function registerGlDisplacementEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlDisplacementEffect(...args); return result; }
api.registerGlDisplacementEffect = registerGlDisplacementEffect;
compiled.flight.EffectsGl.registerGlDisplacementEffect = registerGlDisplacementEffect;
