// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {}
__syncDependencies();

export const applyFxaaEffectToGl = api.applyFxaaEffectToGl;
export const defaultGlFxaaEffectRunner = api.defaultGlFxaaEffectRunner;
export const registerGlFxaaEffect = api.registerGlFxaaEffect;
