// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flighthq.effectsGl.GlGodRaysEffect;
function __syncDependencies() {
  compiled.flighthq.renderGl.GlFullscreenPass.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flighthq.effectsGl.GlEffectProgramCache.getGlEffectProgram = __dependency1.getGlEffectProgram;
  compiled.flighthq.renderGl.GlRenderState.getGlRenderStateRuntime = __dependency0.getGlRenderStateRuntime;
}
__syncDependencies();

export const applyGodRaysEffectToGl = api.applyGodRaysEffectToGl;
export const defaultGlGodRaysEffectRunner = api.defaultGlGodRaysEffectRunner;
export const registerGlGodRaysEffect = api.registerGlGodRaysEffect;
