// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';

const api = compiled.flighthq.effectsGl.GlGradientGlowEffect;
function __syncDependencies() {}
__syncDependencies();

export const applyGradientGlowEffectToGl = api.applyGradientGlowEffectToGl;
export const defaultGlGradientGlowEffectRunner = api.defaultGlGradientGlowEffectRunner;
