// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectBlitShader.mjs';
import * as __dependency2 from './glEffectBoxBlur.mjs';
import * as __dependency3 from './glEffectTintShader.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.acquireGlRenderTarget = __dependency0.acquireGlRenderTarget;
  compiled.flight._RenderGl.clearGlRenderTarget = __dependency0.clearGlRenderTarget;
  compiled.flight._RenderGl.compileGlFullscreenProgram = __dependency0.compileGlFullscreenProgram;
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._RenderGl.releaseGlRenderTarget = __dependency0.releaseGlRenderTarget;
  compiled.flight._EffectsGl.applyGlEffectBlitPass = __dependency1.applyGlEffectBlitPass;
  compiled.flight._EffectsGl.applyGlEffectBoxBlur = __dependency2.applyGlEffectBoxBlur;
  compiled.flight._EffectsGl.applyGlEffectInvertTintPass = __dependency3.applyGlEffectInvertTintPass;
}
__syncDependencies();

const __bridgeImplementation_applyInnerGlowEffectToGl = api.applyInnerGlowEffectToGl;
export function applyInnerGlowEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyInnerGlowEffectToGl(...args); return result; }
api.applyInnerGlowEffectToGl = applyInnerGlowEffectToGl;
compiled.flight.EffectsGl.applyInnerGlowEffectToGl = applyInnerGlowEffectToGl;
const __bridgeImplementation_defaultGlInnerGlowEffectRunner = api.defaultGlInnerGlowEffectRunner;
export function defaultGlInnerGlowEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlInnerGlowEffectRunner(...args); }
api.defaultGlInnerGlowEffectRunner = defaultGlInnerGlowEffectRunner;
const __bridgeImplementation_registerGlInnerGlowEffect = api.registerGlInnerGlowEffect;
export function registerGlInnerGlowEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlInnerGlowEffect(...args); return result; }
api.registerGlInnerGlowEffect = registerGlInnerGlowEffect;
compiled.flight.EffectsGl.registerGlInnerGlowEffect = registerGlInnerGlowEffect;
