// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyMedianEffectToGl = api.applyMedianEffectToGl;
export function applyMedianEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyMedianEffectToGl(...args); return result; }
api.applyMedianEffectToGl = applyMedianEffectToGl;
compiled.flight.EffectsGl.applyMedianEffectToGl = applyMedianEffectToGl;
const __bridgeImplementation_defaultGlMedianEffectRunner = api.defaultGlMedianEffectRunner;
export function defaultGlMedianEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlMedianEffectRunner(...args); }
api.defaultGlMedianEffectRunner = defaultGlMedianEffectRunner;
export const MAX_MEDIAN_EFFECT_GL_RADIUS = api.MAX_MEDIAN_EFFECT_GL_RADIUS;
const __bridgeImplementation_registerGlMedianEffect = api.registerGlMedianEffect;
export function registerGlMedianEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlMedianEffect(...args); return result; }
api.registerGlMedianEffect = registerGlMedianEffect;
compiled.flight.EffectsGl.registerGlMedianEffect = registerGlMedianEffect;
