// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from './glEffectBlitShader.mjs';
import * as __dependency1 from './glEffectBoxBlur.mjs';
import * as __dependency2 from './glEffectTintShader.mjs';

const api = compiled.flighthq.effectsGl.GlOuterGlowEffect;
function __syncDependencies() {
  compiled.flighthq.effectsGl.GlEffectBlitShader.applyGlEffectBlitPass = __dependency0.applyGlEffectBlitPass;
  compiled.flighthq.effectsGl.GlEffectBlitShader.applyGlEffectErasePass = __dependency0.applyGlEffectErasePass;
  compiled.flighthq.effectsGl.GlEffectBoxBlur.applyGlEffectBoxBlur = __dependency1.applyGlEffectBoxBlur;
  compiled.flighthq.effectsGl.GlEffectTintShader.applyGlEffectTintPass = __dependency2.applyGlEffectTintPass;
}
__syncDependencies();

export const applyOuterGlowEffectToGl = api.applyOuterGlowEffectToGl;
export const defaultGlOuterGlowEffectRunner = api.defaultGlOuterGlowEffectRunner;
export const registerGlOuterGlowEffect = api.registerGlOuterGlowEffect;
