// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyScanlinesEffectToGl = api.applyScanlinesEffectToGl;
export function applyScanlinesEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyScanlinesEffectToGl(...args); return result; }
api.applyScanlinesEffectToGl = applyScanlinesEffectToGl;
compiled.flight.EffectsGl.applyScanlinesEffectToGl = applyScanlinesEffectToGl;
const __bridgeImplementation_defaultGlScanlinesEffectRunner = api.defaultGlScanlinesEffectRunner;
export function defaultGlScanlinesEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlScanlinesEffectRunner(...args); }
api.defaultGlScanlinesEffectRunner = defaultGlScanlinesEffectRunner;
const __bridgeImplementation_registerGlScanlinesEffect = api.registerGlScanlinesEffect;
export function registerGlScanlinesEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlScanlinesEffect(...args); return result; }
api.registerGlScanlinesEffect = registerGlScanlinesEffect;
compiled.flight.EffectsGl.registerGlScanlinesEffect = registerGlScanlinesEffect;
