// Generated by flight-hx. Do not edit.
import compiled from '../../../../build/haxe-js/flight.cjs';
import * as __dependency0 from '@flighthq/render-gl/contract';
import * as __dependency1 from './glEffectProgramCache.mjs';

const api = compiled.flight._EffectsGl;
function __syncDependencies() {
  compiled.flight._RenderGl.drawGlFullscreenPass = __dependency0.drawGlFullscreenPass;
  compiled.flight._EffectsGl.getGlEffectProgram = __dependency1.getGlEffectProgram;
}
__syncDependencies();

const __bridgeImplementation_applyToneMapEffectToGl = api.applyToneMapEffectToGl;
export function applyToneMapEffectToGl(...args) { __syncDependencies(); const result = __bridgeImplementation_applyToneMapEffectToGl(...args); return result; }
api.applyToneMapEffectToGl = applyToneMapEffectToGl;
compiled.flight.EffectsGl.applyToneMapEffectToGl = applyToneMapEffectToGl;
const __bridgeImplementation_defaultGlToneMapEffectRunner = api.defaultGlToneMapEffectRunner;
export function defaultGlToneMapEffectRunner(...args) { __syncDependencies(); return __bridgeImplementation_defaultGlToneMapEffectRunner(...args); }
api.defaultGlToneMapEffectRunner = defaultGlToneMapEffectRunner;
const __bridgeImplementation_registerGlToneMapEffect = api.registerGlToneMapEffect;
export function registerGlToneMapEffect(...args) { __syncDependencies(); const result = __bridgeImplementation_registerGlToneMapEffect(...args); return result; }
api.registerGlToneMapEffect = registerGlToneMapEffect;
compiled.flight.EffectsGl.registerGlToneMapEffect = registerGlToneMapEffect;
